### ISSUE TITLE
当路由设置为hash模式时，点击左上角logo会导致整个页面刷新，而不是跳转到首页。

### ISSUE THREAD

**Issue by woohs** [ant-design/ant-design-pro-layout#100]
问题：
当路由设置为hash模式时，点击左上角logo会导致页面整个刷新，而不是跳转到首页。

个人理解：
左上角header-logo的a标签href='/'写死了，当路由设置为hash模式时，就会导致页面整个刷新。
尝试用onMenuHeaderClick属性覆盖，依然不行

期望：
能不能不要写死这个a标签？

![image](https://user-images.githubusercontent.com/31387031/64521159-10798f80-d32a-11e9-944e-f5882732a1ed.png)

**Comment by ZuhuaLiu** [comment]
额，我也遇到这样的问题，早上找源码发现是写死的，希望早早更新为可配置的吧

**Comment by woohs** [comment]
> 额，我也遇到这样的问题，早上找源码发现是写死的，希望早早更新为可配置的吧

是呀，个人感觉v4封装了layout，降低了一定灵活性。实在不行，用回原来的layout算了。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro-layout/issues/50

**Comment by chenshuai2144** [comment]
可以通过 menurender 来进行修改
