### ISSUE TITLE
Breadcrumbs Custom Seperator

### ISSUE THREAD

**Issue by vaibhavhrt** [ant-design/ant-design-pro-layout#104]
How can I use custom separator for breadcrumbs rendered by ProLayout.

Right now my Basic layout looks like this :point_down: , basically the same as default.
How can I use custom separator for the breadcrumbs instead of `/`. We are trying to use some svg icon as the separator.

```
<ProLayout
    ...
      breadcrumbRender={(routers = []) => [
        {
          path: '/',
          breadcrumbName: formatMessage({
            id: 'menu.home',
            defaultMessage: 'Home',
          }),
        },
        ...routers,
      ]}
      itemRender={(route, params, routes, paths) => {
        const first = routes.indexOf(route) === 0;
        return first ? (
          <Link to={paths.join('/')}>{route.breadcrumbName}</Link>
        ) : (
          <span>>{route.breadcrumbName}</span>
        );
      }}
      footerRender={GlobalFooter}
      menuDataRender={menuDataRender}
      formatMessage={formatMessage}
      rightContentRender={rightProps => <RightContent {...rightProps} />}
      {...props}
      {...settings}
    >
      {children}
</ProLayout>
```

**Comment by chenshuai2144** [comment]
you can  use  [pageheaderwrapper](https://github.com/ant-design/ant-design-pro-layout#pageheaderwrapper)

**Comment by vaibhavhrt** [comment]
Thanks, will try it later.

**Comment by summmmer** [comment]
试了各种方法，还是不能改

**Comment by summmmer** [comment]
<PageHeaderWrapper
                title={false}
                pageHeaderRender={({ breadcrumb }: any) => (
                  <Breadcrumb itemRender={breadcrumb.itemRender} routes={breadcrumb.routes} separator=">"/>
                )}
              >
暂时解决了问题

**Comment by vaibhavhrt** [comment]
> you can use [pageheaderwrapper](https://github.com/ant-design/ant-design-pro-layout#pageheaderwrapper)

Got it to work. Thanks, closing.
