### ISSUE TITLE
PageHeaderWrapper 返回按钮与 Tabs 的样式问题

### ISSUE THREAD

**Issue by XuToTo** [ant-design/ant-design-pro-layout#105]
当前版本：
"@ant-design/pro-layout": "^4.5.15"
"antd": "^3.23.2"

![image](https://user-images.githubusercontent.com/8039013/64918055-69827100-d7cb-11e9-9ac6-8158ab0db50a.png)

Tabs 距离底部产生了一段距离，这与 Pro 官网的 demo 表现不一致：
![image](https://user-images.githubusercontent.com/8039013/64918102-45735f80-d7cc-11e9-8866-9997989ae54b.png)

返回图标的样式也与之前的不同：
![image](https://user-images.githubusercontent.com/8039013/64918174-4b1d7500-d7cd-11e9-9e74-f0e939d75433.png)

另外，我发现在 ant-design 这个 PR 里给出的样式已经发生变更了：
https://github.com/ant-design/ant-design/pull/18128

请问是更换了新样式，还是样式设计上的问题呢？

**Comment by chenshuai2144** [comment]
新的设计就是这样。最近还会改回来🤧
