### ISSUE TITLE
约定路由下无法显示菜单

### ISSUE THREAD

**Issue by ChasLui** [ant-design/ant-design-pro-layout#108]
生成的.umi/router.js 里面已将有了路由配置信息, 但是还是无法生成菜单
![image](https://user-images.githubusercontent.com/10083758/65006798-bdf62f80-d936-11e9-8963-77f7a2172726.png)
![image](https://user-images.githubusercontent.com/10083758/65006822-d2d2c300-d936-11e9-967e-135cc3969f8f.png)
![image](https://user-images.githubusercontent.com/10083758/65006830-dc5c2b00-d936-11e9-87c7-be5c671877ed.png)
![image](https://user-images.githubusercontent.com/10083758/65006855-f3028200-d936-11e9-991b-732a064b48b1.png)
![image](https://user-images.githubusercontent.com/10083758/65006902-13cad780-d937-11e9-9ec3-03ec0854de9a.png)

**Comment by ChasLui** [comment]
发现因为约定路由生成的路由名称是 title 字段,而 ant-desin-pro-layout 使用的是 name 字段, 最终导致不一致, 现在只能在 app.js 里面去修改动态生成的 routes 了
```js
# app.js
export const patchRoutes = routes => {
  routes.forEach(item => {
    const { name, path, _title, title } = item;
    // 根目录不用命名
    if (!name && path && path.length > 1) item.name = title || _title || '';
    if (item.routes) patchRoutes(item.routes);
  });
};

```

**Comment by chenshuai2144** [comment]
现在还是不支持约定路由的
