### ISSUE TITLE
固定 Header 下，header与 antd input 的 prefix 和 suffix 内容重合

### ISSUE THREAD

**Issue by iwyvi** [ant-design/ant-design-pro-layout#109]
layout 的 header 的 z-index 和 antd input 前后缀内容的 z-index 都是 2，当使用固定 Header 模式时，会出现重合情况。

ant-design-pro-layout 版本：v4.5.16
ant-design 版本：v3.23.3

<img width="297" alt="QQ20190917-190849@2x" src="https://user-images.githubusercontent.com/12790101/65036736-b195c500-d97e-11e9-8777-f07320f94968.png">

**Comment by chenshuai2144** [comment]
fixed in 4.7.0

现在可以支持自定义 className，并且默认设置为 9
