### ISSUE TITLE
提供一个 codesandbox 的例子放在 README 里

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro-layout#110]
方便展示能力、基本用法和调试。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro-layout/issues/93

**Comment by chenshuai2144** [comment]
加了个 stroybook

**Comment by afc163** [comment]
这个 storybook 貌似样式出不来。

**Comment by chenshuai2144** [comment]
father doc 更棒

**Comment by afc163** [comment]
codesandbox 更接近实际使用场景，用户可以依样画瓢。

**Comment by chenshuai2144** [comment]
https://prolayout.ant.design/base
也可以看代码。

而且 layout 没有打包 css 出来。codesandbox 里面用起来比较困难。我先打css包出来

**Comment by afc163** [comment]
codesandbox 用起来比较困难的话 ，用户本地单独用起来也困难的。

**Comment by chenshuai2144** [comment]
https://unpkg.com/browse/@ant-design/pro-layout@5.0.13/dist/
已经支持
