### ISSUE TITLE
希望 menuProps 可以支持更多参数

### ISSUE THREAD

**Issue by wangjianio** [ant-design/ant-design-pro-layout#116]
[API 文档](https://github.com/ant-design/ant-design-pro-layout/blob/master/README.zh-CN.md#api) 的最下面有提到
> 在 4.5.13 以后 Layout 支持 Menu 的大部分 props。

但看代码实现 https://github.com/ant-design/ant-design-pro-layout/blob/master/src/SiderMenu/BaseMenu.tsx#L291-L300 并没有支持很多属性。

比如 defaultOpenKeys，还是我使用上有问题？

**Comment by chenshuai2144** [comment]
支持了所有的参数了。
defaultOpenKeys 可以试试 
https://prolayout.ant.design/example?anchor=%E6%90%9C%E7%B4%A2%E8%8F%9C%E5%8D%95#%E9%BB%98%E8%AE%A4%E6%89%93%E5%BC%80%E6%89%80%E6%9C%89%E8%8F%9C%E5%8D%95
