### ISSUE TITLE
Some Layout menuProps don't seem to be working

### ISSUE THREAD

**Issue by stevenhales** [ant-design/ant-design-pro-layout#117]
As of ProLayout version "4.5.16"

The ones I have tried are:

selectedKeys: [0],
onClick: () => alert("clicked"),
onSelect: () => alert("selected")

Is there a plan to include these in the near future? Also, I maybe missing something here perhaps, but some of the others props work fine, such as 'theme', and 'mode'. I am using the ProLayout component as a direct import into a non umi project. Thanks for checking

**Comment by chenshuai2144** [comment]
try menuProps. layout only support openKeys and selectKeys

**Comment by ywy94ywy** [comment]
> try menuProps. layout only support openKeys and selectKeys

how to get menu keys
