### ISSUE TITLE
react 高版本出现待废弃声明周期的 warnings，componentWillMount、componentWillReceiveProps

### ISSUE THREAD

**Issue by lijinpengFj** [ant-design/ant-design-pro-layout#127]
React 版本： 16.10.2

pro-layout 版本：4.5.16

本地开发环境下，出现 warnings，以下仅为一个示例

Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

全部 warnings 如图

![image](https://user-images.githubusercontent.com/10599551/66388673-3b263900-e9f9-11e9-9107-1533474cfe66.png)

这两个 warnings 为 pro-layout 依赖的 react-document-title、react-conatiner-query 导致，对应的问题的 issue 为 [document-title](
https://github.com/gaearon/react-document-title/issues/62)、[container-query](
https://github.com/d6u/react-container-query/issues/78)，建议持续关注

**Comment by afc163** [comment]
react-document-title 可以换成 react-helmet，来个 PR 吧~
