### ISSUE TITLE
面包屑导航链接地址如何改为 'browser'方式

### ISSUE THREAD

**Issue by 389567702** [ant-design/ant-design-pro-layout#128]
通过PageHeader添加的面包屑导航生效，但面包屑导航跳转地址是hash模式，config里面已经将history改为brower，请问此问题如何解决？@chenshuai2144

**Comment by chenshuai2144** [comment]
试试这个 demo
https://ant-design.github.io/ant-design-pro-layout/?path=/story/basiclayout--custom-header
