### ISSUE TITLE
没有menuData属性，动态展示菜单如何实现

### ISSUE THREAD

**Issue by yisufei** [ant-design/ant-design-pro-layout#13]
我记得之前版本中的BasicLayout中是有menuData属性的，这样方便将从后端获取到的用户菜单信息直接更新上去，现在只能通过调整props.route.routes来实现吗？

**Comment by chenshuai2144** [comment]
现在也有 menuData .
https://github.com/ant-design/ant-design-pro-layout#prolayout

**Comment by chenshuai2144** [comment]
搞错了 现在的 menudata 是通过 routers 来自动生成的。

**Comment by yisufei** [comment]
> 搞错了 现在的 menudata 是通过 routers 来自动生成的。

根据route生成的是固定的，但是每个用户的菜单基本都是不一样的，因为权限不同。让用户看到没有操作权限的菜单很不合适的。

**Comment by chenshuai2144** [comment]
你可以自己传入 routers。 按照标准的数据格式

**Comment by qiulin** [comment]
> 你可以 按照标准的数据格式自己传入 routers。

请问怎么传，从哪里传？
