### ISSUE TITLE
PageHeaderWrapper怎么隐藏title

### ISSUE THREAD

**Issue by junhui75165** [ant-design/ant-design-pro-layout#133]
PageHeader 里面不设置title会隐藏标题，但我试了一下title=null效果，请教下这个是如何设置的，第一次使用见谅！
![image](https://user-images.githubusercontent.com/3411959/66741923-1aeaf400-eea9-11e9-8a8d-15293f421cc4.png)

**Comment by chenshuai2144** [comment]
title = false
即可

**Comment by li5tun** [comment]
但是仍然会留下一条空白的区域

**Comment by LinuxGod** [comment]
> 但是仍然会留下一条空白的区域

title={false} content={child component}
