### ISSUE TITLE
build 生成 es 和 lib 或者说 在 yarn add @ant-design/pro-layout 中的样式 能否编译成 css文件先？

### ISSUE THREAD

**Issue by LengYXin** [ant-design/ant-design-pro-layout#134]
准备把这个布局加到项目中来。yarn 安装的 模块中的 布局样式 还是 less 文件。能否设置成 css 的在发布？这对于默认使用 less 编译的用户可能没啥。但是使用 sass 的用户又得在当前项目的基础上添加  less 的解析。虽然不是什么大问题。也挺麻烦的。
查看源码打包用的是 father-build build 配置了 .fatherrc.js 文件中的 lessInBabelMode: true,
发现npm run build 又是报错了。不明所以然。所有总的来说。项目在发布 打包的同时 把 less 编译成 css ？

**Comment by baiy** [comment]
同求  create-react-app 不支持less 要 eject 很纠结

**Comment by chenshuai2144** [comment]
create-react-app  有 less 的模板的。

layout 如果导出 css ，需要一些复杂的编译，并且无法修改主题。

**Comment by chenshuai2144** [comment]
added
