### ISSUE TITLE
ProLayout 中 设置  title 想修改 左侧菜单顶部 的 title 无效，会被defaultSetting 给覆盖调。

### ISSUE THREAD

**Issue by jefferyssy** [ant-design/ant-design-pro-layout#135]
菜单右上角的内容，能否自定义呢，比如  logo 和 title 封装成一个自定义组件

**Comment by chenshuai2144** [comment]
https://ant-design.github.io/ant-design-pro-layout/?path=/story/basiclayout--custom-header

**Comment by kqzh** [comment]
> 菜单右上角的内容，能否自定义呢，比如 logo 和 title 封装成一个自定义组件

hei !  我也遇到了相同的问题，请问兄弟是怎么解决的

**Comment by HullQin** [comment]
奇怪，我按照demo这样写，title也没有生效：
```
<ProLayout
      logo={logo}
      title="我的标题"
      menuHeaderRender={(logoDom, titleDom) => (
        <Link to="/">
          {logoDom}
          {titleDom}
        </Link>
      )}
...
</ProLayout>
```
迫于无奈，我只好这样写了：
```
<ProLayout
      logo={logo}
      // title="我的标题"
      menuHeaderRender={(logoDom, titleDom) => (
        <Link to="/">
          {logoDom}
          {titleDom && <h1>我的标题</h1>}
        </Link>
      )}
...
</ProLayout>
```

**Comment by HullQin** [comment]
我刚看到这个[issue](https://github.com/ant-design/ant-design-pro-layout/issues/161)，看来是demo地址变了。
这个[https://ant-design.github.io/ant-design-pro-layout/?path=/story/basiclayout--custom-header](https://ant-design.github.io/ant-design-pro-layout/?path=/story/basiclayout--custom-header)进去后是文档地址。

**Comment by HullQin** [comment]
醉了，今天才发现`<ProLayout>`组件最后面的`{...settings}`（是从`models/setting` connect过来的），难怪之前设置title会被覆盖掉。所以要改title，直接去改defaultSetting里面的title就好了。
