### ISSUE TITLE
Breadcrumb面包屑导航如何添加？

### ISSUE THREAD

**Issue by zywkuo** [ant-design/ant-design-pro-layout#14]
面包屑导航是哪个参数控制，如何修改面包屑的位置呢？

**Comment by zywkuo** [comment]
breadcrumbRender这个参数，但是我的一直显示不了。
<img width="409" alt="WX20190605-174241@2x" src="https://user-images.githubusercontent.com/21994183/58946878-6550bb80-87b9-11e9-926e-b2203ef970ce.png">
还有我想挪位置可以自定义吗？比如放在这里
<img width="514" alt="WX20190605-174303@2x" src="https://user-images.githubusercontent.com/21994183/58946975-94ffc380-87b9-11e9-909e-09638355b76a.png">

**Comment by chenshuai2144** [comment]
PageHeader 在这里。
https://github.com/ant-design/ant-design-pro-layout/tree/master/src/PageHeaderWrapper

如果你要自定义，可以用 headerRender 方法

**Comment by well-monkey** [comment]
> breadcrumbRender这个参数，但是我的一直显示不了。
> <img alt="WX20190605-174241@2x" width="409" src="https://user-images.githubusercontent.com/21994183/58946878-6550bb80-87b9-11e9-926e-b2203ef970ce.png">
> 还有我想挪位置可以自定义吗？比如放在这里
> <img alt="WX20190605-174303@2x" width="514" src="https://user-images.githubusercontent.com/21994183/58946975-94ffc380-87b9-11e9-909e-09638355b76a.png">

请问你解决了么。我也遇到相同的问题了。而且在另外一个回复中 https://github.com/ant-design/ant-design-pro/issues/4693  开发者回复不同

**Comment by zilingziling** [comment]
@well-monkey 你好 在header添加面包屑的问题，你解决了吗？

**Comment by coderxuli** [comment]
我通过 重写头来解决了。
