### ISSUE TITLE
🧐[问题] 怎样在onTitleClick里把菜单关闭？

### ISSUE THREAD

**Issue by n313893254** [ant-design/ant-design-pro-layout#144]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
目标: 我想要实现subMenu的跳转功能

目前可以通过 `onTitleClick` 进行页面跳转，但是无法把菜单关闭

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
```
              onTitleClick: () => {
                router.push(`/rancher/${s.id}`)
              },
```

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/18737885/67634263-821a9680-f8f4-11e9-9267-f2b6f3272d02.png)
点击 `rancher16`(subMenu) 无法使菜单像点击 Menu.Item 一样关闭

**Comment by chenshuai2144** [comment]
可以使用 openKeys 来进行判断
