### ISSUE TITLE
🐛[BUG] 自定义菜单问题

### ISSUE THREAD

**Issue by leshalv** [ant-design/ant-design-pro-layout#149]
目前使用自定义菜单的时候发现了一个问题，比如在约定路由中配置在organization下
![image](https://user-images.githubusercontent.com/30397655/67743609-21a56980-fa5a-11e9-8b87-aa93fc438ff5.png)

自定义菜单的时候我们把他放置到了manage下面
![image](https://user-images.githubusercontent.com/30397655/67743593-15211100-fa5a-11e9-8f77-4484cc7585ba.png)

菜单可以展示正确，但是当点击的时候，当前所在的父节点会关闭，去展开了organization，但是蓝色选中还是有的，所以我想选中问题解决了，现在目前自定义菜单就剩下折叠问题了

**Comment by leshalv** [comment]
> 你点击 /a/b 的时候 会打开 /a 和 /a/b
> 
> 你现在是 /a/ 下的 /b/c ，他会打开 /b/和 /b/c ，所以会把 a折叠起来。
> 
> 最好把第一个菜单前缀也改为 /mange/

这样不就不灵活了，后端配置了，前端也要跟着更改

**Comment by chenshuai2144** [comment]
你可以用另外一个 key 来进行这个嵌套的设置，但是希望还是能规范一些。
强大和灵活不可兼得。我也没有精力搞的非常强大
