### ISSUE TITLE
👑 [需求]Header 组件的z-index

### ISSUE THREAD

**Issue by shawbena** [ant-design/ant-design-pro-layout#152]
问题：
需要可以设置Header组件的zindex, 但现在z-index 在内联的样式，无法在外边设置
解决方法：
将 Header 内联的z-index样式写在外部样式表中

**Comment by chenshuai2144** [comment]
可以用 className 来自定义一下

**Comment by ywy94ywy** [comment]
> 可以用 className 来自定义一下。
> 你碰到了什么需求？

antpro是上下结构，他估计想是左右结构的，那么sider的box-shadow之类的属性就不会覆盖到header上去了

**Comment by shawbena** [comment]
@chenshuai2144 样式内联的用className 不行的

**Comment by chenshuai2144** [comment]
让所有的组件都支持  style 和 className 吧
你有兴趣搞个 pr 吗？

**Comment by chenshuai2144** [comment]
fixed in 4.7.0
