### ISSUE TITLE
关于BasicLayout的一点疑惑

### ISSUE THREAD

**Issue by kqzh** [ant-design/ant-design-pro-layout#161]
### 🧐 问题描述
我使用的是ant design pro v4 ，当我试图修改侧边menu的title时，我找到了layout/BasicLayout.jsx,
在ProLayout中修改了title, 但是reload后，菜单栏的menu并没有变化，请问实际应该如何修改
### 💻 示例代码
```js
<ProLayout
      title={"hello"}
      logo={logo}
      onCollapse={handleMenuCollapse}
      ...
</ProLayout>
```

**Comment by chenshuai2144** [comment]
emm， 这个 api 需要做一点改动了 
你可以使用  menuHeaderRender 来 很好的自定义。
这里是demo
https://ant-design.github.io/ant-design-pro-layout/?path=/story/basiclayout--custom-header

**Comment by kqzh** [comment]
> emm， 这个 api 需要做一点改动了
> 你可以使用 menuHeaderRender 来 很好的自定义。
> 这里是demo
> https://ant-design.github.io/ant-design-pro-layout/?path=/story/basiclayout--custom-header

ok 我试着使用了您给的demo, 问题暂时解决啦, 但这样写会多报一些warning
```js
<ProLayout
...
     menuHeaderRender={(logo, title) => {
        const newTitle = {...title,props:{...props,children:"Hello"}};
        console.log();
      return(
        <div>
          {logo}
          {newTitle}
        </div>)
      }}
...
</ProLayout>
```
