### ISSUE TITLE
umi build后缺少部分css样式

### ISSUE THREAD

**Issue by zhoujun165** [ant-design/ant-design-pro-layout#165]
antd-pro build之后，发现界面布局有问题，查看之后发现编译好的css文件中缺少一些样式，例如：.ant-pro-sider-menu-logo。本地开发时是有的。

**Comment by chenshuai2144** [comment]
试着升级一下最新的版本。 4.6.1 中修复了
https://github.com/ant-design/ant-design-pro-layout/blob/v4.6.1/changelog.en-US.md#461

**Comment by zhoujun165** [comment]
> 试着升级一下最新的版本。 4.6.1 中修复了
> https://github.com/ant-design/ant-design-pro-layout/blob/v4.6.1/changelog.en-US.md#461

升级后解决了。太感谢了。今天折腾了大半天。
