### ISSUE TITLE
🐛[BUG] 4.6.2以后的版本PageHeaderWrapper不再生成面包屑

### ISSUE THREAD

**Issue by Nokecy** [ant-design/ant-design-pro-layout#170]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
需要先用 Pro-Layout 包裹

**Comment by coffee377** [comment]
> 需要先用 Pro-Layout 包裹

包裹了任然不行，需要修改 breadcrumb 至 defaultProps 后

**Comment by Nokecy** [comment]
@coffee377  怎么修改~~~

**Comment by coffee377** [comment]
> @coffee377 怎么修改~~~

提了 PR
