### ISSUE TITLE
🧐[问题]  PageHeaderWrapper  修改默认的 margin 值？

### ISSUE THREAD

**Issue by zhangjie2012** [ant-design/ant-design-pro-layout#182]
PageHeaderWrapper  默认的外边距是：`margin: -24px -24px 0px;` ，想改掉这个值。

我看源代码，似乎可以通过 `className` 的方式覆盖掉，但尝试之后不生效。

@ant-design/pro-layout 版本：`4.6.2`

**Comment by coffee377** [comment]
> PageHeaderWrapper 默认的外边距是：`margin: -24px -24px 0px;` ，想改掉这个值。
> 
> 我看源代码，似乎可以通过 `className` 的方式覆盖掉，但尝试之后不生效。
> 
> @ant-design/pro-layout 版本：`4.6.2`

应该使用 style 修改覆盖掉原始值，优先级高于 className，如 
`<PageHeaderWrapper content="欢迎您的使用" style={{ margin: 0 }}>
            {props.children}
          </PageHeaderWrapper>`

**Comment by zhangjie2012** [comment]
@coffee377 

这样可以改掉 `ant-pro-page-header-wrap-page-header-warp` 的样式，但是使用 `PageHeaderWrapper` ，外面会自动增加一层布局:
![Uploading image.png…]()

这并不是我加的，而是使用组件自动生成的，令人不解。

**Comment by coffee377** [comment]
全局样式文件，修改覆盖原有样式

![image](https://user-images.githubusercontent.com/13707072/68725052-3ce6ac00-05f8-11ea-8c95-c1c62f10b077.png)

**Comment by zhangjie2012** [comment]
这个只能改 `ant-pro-page-header-wrap-page-header-warp`，但是上面的 `margin` 是包在他外层的

**Comment by zhangjie2012** [comment]
因为默认他以为 `.ant-pro-basicLayout-content` 的外边距为 `24px`，所以这块相当于是想抵消掉。
但是我把默认的 `.ant-pro-basicLayout-content` 的外边局改为了 `16px`，如果不改这个 `-24px` 就对不齐了。

**Comment by coffee377** [comment]
> 因为默认他以为 `.ant-pro-basicLayout-content` 的外边距为 `24px`，所以这块相当于是想抵消掉。
> 但是我把默认的 `.ant-pro-basicLayout-content` 的外边局改为了 `16px`，如果不改这个 `-24px` 就对不齐了。

@zhangjie2012 你想改的是这吧……，没有改不了的，只是你没找对地方而已
![image](https://user-images.githubusercontent.com/13707072/68729870-162f7200-0606-11ea-9dc7-22a39430f2b2.png)

**Comment by zhangjie2012** [comment]
![image](https://user-images.githubusercontent.com/2450412/68730010-7c1bf980-0606-11ea-8d9c-dbbf47ee02db.png)
我一直问的是上面截图的 `-24px`，不是你箭头指的地方。

**Comment by chenshuai2144** [comment]
@zhangjie2012  试试 beta 版本 支持 style。
https://github.com/ant-design/ant-design-pro-layout/releases/tag/v4.7.0-3
<PageHeaderWarpper style={{}}

**Comment by zhangjie2012** [comment]
> @zhangjie2012 试试 beta 版本 支持 style。
> https://github.com/ant-design/ant-design-pro-layout/releases/tag/v4.7.0-3
> `<PageHeaderWarpper style={{}} />`

可以的，但是代码不兼容，面包屑没了... 回退了，不折腾这个了。

@coffee377 
你用的版本是最新的，我用的是 `4.6.2`，版本不一样，所以行为不一样。

**Comment by chenshuai2144** [comment]
fix in 4.7.0
