### ISSUE TITLE
4.7.0颜色变了

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro-layout#186]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
![image](https://user-images.githubusercontent.com/18542211/68820734-47bc4200-06c7-11ea-9d7e-f031da9047ff.png)
![image](https://user-images.githubusercontent.com/18542211/68820746-54d93100-06c7-11ea-829d-f40fc9750788.png)
![image](https://user-images.githubusercontent.com/18542211/68820792-6d494b80-06c7-11ea-81b6-9a9e029a70f4.png)
![image](https://user-images.githubusercontent.com/18542211/68820818-7c2ffe00-06c7-11ea-89cb-b7f4cb17157f.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
![image](https://user-images.githubusercontent.com/18542211/68820765-602c5c80-06c7-11ea-817e-b63623ad4e2d.png)
_4.6.0一样的，在topmenu下还少了 ..._

**可能有问题的 pr 
https://github.com/ant-design/ant-design-pro-layout/pull/151**

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
@chenshuai2144

**Comment by afc163** [comment]
bug 啦！@chenshuai2144

**Comment by kaoding** [comment]
bothmenu 这个 菜单布局增加了，在readme中没有说明。可能是这个pr 产生的问题

**Comment by hhking** [comment]
> bothmenu 这个 菜单布局增加了，在readme中没有说明。可能是这个pr 产生的问题

这个 pr 已经  revert 了重新实现了，没有新增 bothmenu

**Comment by chenshuai2144** [comment]
这个导致的 

https://github.com/ant-design/ant-design-pro-layout/commit/24bce4f13e449c58ad8df9789e39b9d492bba74e

相关 issue
https://github.com/ant-design/ant-design-pro/issues/5603#issuecomment-554189690

**Comment by afc163** [comment]
能否找到办法向下兼容呢？

**Comment by chenshuai2144** [comment]
不好兼容，不然会发一个小版本。
或者样式上下一下功夫。让不要变成蓝色

**Comment by hua11018818** [comment]
> 不好兼容，不然会发一个小版本。
> 或者样式上下一下功夫。让不要变成蓝色
> 
> 如果不变成蓝色，用户可能发现不了行为变化

不光是蓝色问题，现在蓝色菜单已经有链接了，折叠菜单点击会导致404

**Comment by xzylogic** [comment]
![image](https://user-images.githubusercontent.com/25906872/69048687-0adeab00-0a39-11ea-8b71-705bbfb0803a.png)
![image](https://user-images.githubusercontent.com/25906872/69048703-16ca6d00-0a39-11ea-9595-e94d10d02532.png)
点击会有链接跳转了都。。

**Comment by blackcater** [comment]
So, how to resolve this problem?

**Comment by SilkageNet** [comment]
So, how to resolve this problem?

**Comment by dimasusername** [comment]
@blackcater @SilkageNet 
https://github.com/ant-design/ant-design-pro/issues/5603#issuecomment-554189690
https://github.com/ant-design/ant-design-pro/blob/2569beb30c52118855bb3be6ad8d79d4b2c2d747/src/layouts/BasicLayout.tsx#L155

**Comment by zhenzhen-H** [comment]
现在有什么解决办法吗？可以锁定版本吗？现在有两层menu的情况下 一级菜单都有链接了 @chenshuai2144

**Comment by zhenzhen-H** [comment]
我这边用的是bigfish构建的项目使用的antd pro的模版

**Comment by chenshuai2144** [comment]
@zhenzhen-H  看这行代码
ant-design/ant-design-pro#5603 (comment)
https://github.com/ant-design/ant-design-pro/blob/2569beb30c52118855bb3be6ad8d79d4b2c2d747/src/layouts/BasicLayout.tsx#L155

**Comment by ilaipi** [comment]
跑过来看看，没看到明确的解决方案啊？

![image](https://user-images.githubusercontent.com/1689135/69417298-5fdd3280-0d53-11ea-9e75-2928ab4729ed.png)

**Comment by zhenzhen-H** [comment]
楼上可以回退锁定一下版本 也可以看看这个https://github.com/ant-design/ant-design-pro/blob/2569beb30c52118855bb3be6ad8d79d4b2c2d747/src/layouts/BasicLayout.tsx#L155

**Comment by miaozilong** [comment]
抄一下代码就好了  感谢ant design pro

**Comment by tranducit95** [comment]
> 跑过来看看，没看到明确的解决方案啊？
> 
> ![image](https://user-images.githubusercontent.com/1689135/69417298-5fdd3280-0d53-11ea-9e75-2928ab4729ed.png)

How to fix this error?

**Comment by ilaipi** [comment]
> > 跑过来看看，没看到明确的解决方案啊？
> > ![image](https://user-images.githubusercontent.com/1689135/69417298-5fdd3280-0d53-11ea-9e75-2928ab4729ed.png)
> 
> How to fix this error?

```
menuItemRender={(menuItemProps, defaultDom) => {
        // add the 3 lines below
        if (menuItemProps.isUrl || menuItemProps.children) {
          return defaultDom;
        }
        return <Link to={menuItemProps.path}>{defaultDom}</Link>;
      }}
```
and Ignore the console warning

**Comment by tranducit95** [comment]
@ilaipi I pulled the latest upstream ant-design-pro code, deleted node_modules and package-lock.json, ran npm i but still showed an error.

**Comment by shabbyaaa** [comment]
> > > 跑过来看看，没看到明确的解决方案啊？
> > > ![image](https://user-images.githubusercontent.com/1689135/69417298-5fdd3280-0d53-11ea-9e75-2928ab4729ed.png)
> > 
> > 
> > How to fix this error?
> 
> ```
> menuItemRender={(menuItemProps, defaultDom) => {
>         // add the 3 lines below
>         if (menuItemProps.isUrl || menuItemProps.children) {
>           return defaultDom;
>         }
>         return <Link to={menuItemProps.path}>{defaultDom}</Link>;
>       }}
> ```
> 
> and Ignore the console warning

我有着三行呀 怎么还有这个bug  是JavaScript版本的

**Comment by fengjiahao** [comment]
我的代码里有这三行，为什么仍然报警？

**Comment by kaoding** [comment]
该问题已解决，请按上面操作或者更新到最新的代码。

**Comment by tranducit95** [comment]
![Screenshot from 2019-11-30 08-30-17](https://user-images.githubusercontent.com/26267956/69893997-ccf05980-134b-11ea-8b51-f237d5a29b21.png)
![Screenshot from 2019-11-30 08-31-13](https://user-images.githubusercontent.com/26267956/69893998-ce218680-134b-11ea-90ad-fbc2ef0119bd.png)
I have added, but it does not work.

**Comment by 544751779** [comment]
为什么我升级了 也加上判断了  还是有这个error的报错 ???

**Comment by chenshuai2144** [comment]
试着升级到最新的版本

**Comment by jiuhwh8** [comment]
我升级了最新版看了下代码依然不知所错

**Comment by chenshuai2144** [comment]
@jiuhwh8  删除 lock 文件 和 所有依赖。
