### ISSUE TITLE
固定Header 样式错乱了，🐛[BUG]

### ISSUE THREAD

**Issue by LengYXin** [ant-design/ant-design-pro-layout#187]
### 🐛 源代码中的 示例  项目中引入ye也是类似情况
![image](https://user-images.githubusercontent.com/19631404/68821771-2446c680-06ca-11ea-9861-bc3f501a6279.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by yoyo837** [comment]
same here

![image](https://user-images.githubusercontent.com/6134547/68822177-3412da80-06cb-11ea-8129-0301b9da8206.png)

**Comment by chenshuai2144** [comment]
@yoyo837  来个pr？

**Comment by yoyo837** [comment]
好的，我先看看...

**Comment by lengthmin** [comment]
我这里确定是这个问题了

**Comment by chenshuai2144** [comment]
新版本修复了，更新一下即可。
忘记 关联issue了
