### ISSUE TITLE
layout 内链接跳转应该使用Link 组件， 比如logo

### ISSUE THREAD

**Issue by yezongyang** [ant-design/ant-design-pro-layout#188]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
项目使用的是hash 路由，layout里部分链接跳转使用的是a 标签， 导致点击menu logo路由不对

### © 版本信息

- Ant Design Pro 版本: [4.0.0]
- 开发环境 [mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![屏幕快照 2019-11-14 12 07 45](https://user-images.githubusercontent.com/8924156/68826119-7e9a5400-06d7-11ea-8deb-e4e9d57422e3.png)

**Comment by chenshuai2144** [comment]
可以通过 menuHeader 来自定义，layout 不希望和 umi 或者 react-router 耦合起来

**Comment by Sean-Snow** [comment]
@chenshuai2144  menuItemRender 方法参数中没有collapsed 状态。如果监听onCollapse 事件，第一次得到的onCollapse并不是当前的collapsed
