### ISSUE TITLE
权限组件能否做成外部插件形式？

### ISSUE THREAD

**Issue by yezongyang** [ant-design/ant-design-pro-layout#189]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
 放在内部感觉还得理解权限组件这块的代码逻辑， 绝大数情况，权限其实是后端控制的。在实际需求上权限控制会更复杂，也需要比较高的灵活度。

**Comment by chenshuai2144** [comment]
你可以通过 renderMenuItem 或者 menuDateRender 来进行截取

**Comment by yezongyang** [comment]
嗯嗯，了解，我想说的是否能在脚手架中让用户选择是否集成Authorized

**Comment by chenshuai2144** [comment]
这是 未来的规划
