### ISSUE TITLE
👑 [需求]三级菜单支持顶部侧栏模式

### ISSUE THREAD

**Issue by EthanOrange** [ant-design/ant-design-pro-layout#199]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
对于sass管理平台，三级菜单是基本刚需🥶，全部放侧栏展开的时候太长，使用起来也没有顶部侧栏联动的舒服。
### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
项目在19年初开始的,基于v2开展，当时layout还可以随意定制，v4单独拿出来封装了，所以一时间不好如何去实现，目前想到的就是考一份layout的代码然后再去改。。
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![pro_1](https://user-images.githubusercontent.com/7098719/69202147-a11aea00-0b7b-11ea-93b6-ee29d1881b2e.png)

**Comment by chenshuai2144** [comment]
有空可以切换一下 ，新的 Layout 方便好多，你的需求现在已经可以实现了。
https://ant-design.github.io/ant-design-pro-layout/
嵌套三个 layout 就能实现你的需求了

**Comment by puce006** [comment]
同求

**Comment by EthanOrange** [comment]
@chenshuai2144 晚上尝试下 看能否满足需求

**Comment by EthanOrange** [comment]
试了下demo嵌套几个layout  在手机端会有几个部render出来...

**Comment by chenshuai2144** [comment]
disableMoblie 就好了。你可以关掉手机模式

**Comment by EthanOrange** [comment]
@chenshuai2144 
pages下组件的props.match和预期中的match值不相符，porps.match永远是跟路由的match。

**Comment by EthanOrange** [comment]
初步实现了
1.当前只有一级时的效果
![antd_pro_top](https://user-images.githubusercontent.com/7098719/69526750-dbceb900-0fa5-11ea-8369-b1681984dee5.png)
2.当前只有两级时的效果
![antd_pro_side1](https://user-images.githubusercontent.com/7098719/69526764-e426f400-0fa5-11ea-97f0-b342a2eecd2e.png)
3.当前有三级时效果
![image](https://user-images.githubusercontent.com/7098719/69526809-f86af100-0fa5-11ea-9fe7-951d72d74420.png)

**Comment by yyhuaisha** [comment]
> 初步实现了
> 1.当前只有一级时的效果
> ![antd_pro_top](https://user-images.githubusercontent.com/7098719/69526750-dbceb900-0fa5-11ea-8369-b1681984dee5.png)
> 2.当前只有两级时的效果
> ![antd_pro_side1](https://user-images.githubusercontent.com/7098719/69526764-e426f400-0fa5-11ea-97f0-b342a2eecd2e.png)
> 3.当前有三级时效果
> ![image](https://user-images.githubusercontent.com/7098719/69526809-f86af100-0fa5-11ea-9fe7-951d72d74420.png)

老哥稳。有实现代码吗？想要参考下
