### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro-layout#2]
- [x] logo 和 renderLogo 职责重复，不如让 logo 多支持一个 function 的用法就够了。
- [x] `lang` 改成 `locale`。
- [x] `onChangeSetting` 改成 `onSettingsChange`，其他 API 类似，Change 要放在最后。
- [x] API 文档直接写到 README 里来吧，把原来 pro 的部分去掉。
- [x] `onLogoClick` 可以用 logo 的 render 方法取代，感觉没啥用。
- [x] `breadcrumbNameMap` 这个 API 有点看不懂，不知道解决什么问题，建议改成更好懂的 API。
- [x] `renderHeader` 最好把左上角和右上角要加的区别开。
- [x] `settings` 直接解构打平和其他 props 放在一起好了，感觉区别不大。
- [ ] 有 `logo` 的话，也应该有 `favicon`。
- [x] SettingsDrawer 变成一个独立组件

**Comment by chenshuai2144** [comment]
settings 主要还是为了方面进行 onchange。配置的时候一般都会设置一个 setting.js 之类的配置。
如果打平。管理 prop 时就会很蛋疼。
```
state = {
  settings:{}
}
<BasicLayout  settings={this.state.settings} onChangeSetting={(settings)=>this.setState({settings})}>

```

**Comment by afc163** [comment]
暴露成 `onXxxxChange` `onYyyyChange` 好了，API 多一点没关系，更清晰一点。

**Comment by chenshuai2144** [comment]
favicon 应该是 html添加的，我们的 logo 是自己定义的一种规范

**Comment by chenshuai2144** [comment]
> 暴露成 onXxxxChange onYyyyChange 好了，API 多一点没关系，更清晰一点。实际上不是所有配置都在 drawer 里。

过于繁杂了。我们有很多配置，以后估计还会增加。

**Comment by afc163** [comment]
breadcrumbNameMap 不写的话，是否有面包屑？

面包屑是否能默认从 config 里的路由 title 里读出来？

breadcrumbNameMap 这样的 API 如何解决国际化问题？

这几个问题没想清楚的话，不要着急加这个 API。现在看不太懂，也不知道怎么用。

**Comment by afc163** [comment]
onSettingsChange 应该是 SettingsDrawer 暴露的 API，Layout 组件里不应该有这个逻辑。如果 SettingsDrawer 是包含在 Layout 里，建议分开，不要放在一起。

**Comment by chenshuai2144** [comment]
breadcrumbNameMap 是 umi 从 config 里面生成的然后注入到 layout 中的。

breadcrumbNameMap 不传的话是没有面包屑的。

全球化原来的解法是根据 menu 的层级拼成一个 locale 字符串。
```
  {
    path: '/user',
    component: '../layouts/UserLayout',
    routes: [
      { path: '/user', redirect: '/user/login' },
      { path: '/user/login', name: 'login', component: './User/Login' },
      { path: '/user/register', name: 'register', component: './User/Register' },
      {
        path: '/user/register-result',
        name: 'register.result',
        component: './User/RegisterResult',
      },
      {
        component: '404',
      },
    ],
  },
```
这个就会生成一个 { locale : user.logon }， 然后从 react-init 里面拿字符串

**Comment by zombieJ** [comment]
也跟着现有的 API 风格来吧：https://github.com/ant-design/ant-design/issues/16048

* onLayoutCollapsedChange => onCollapse
* renderXXX => xxxRender
* breadcrumbNameMap => breadcrumb (PageHeader 里只有 `routes`，可以强化一下继续同一个名字)

**Comment by chenshuai2144** [comment]
headerRender 现在可以支持两个参数。 一个是默认的props。
```
<BasicLayout
  headerRender={(props, defaultDom) => (
    <div>
      {props.logo} {props.rightContentRender(props)}
    </div>
  )}
/>;
```

**Comment by afc163** [comment]
props 命名看上去很奇怪。这样要只修改一部分或者加点东西会变得很难，要嘛不改要嘛全改。

**Comment by chenshuai2144** [comment]
pro 的 header 现在比较复杂。
在topMenu的模式中 header中还有menu ，不只是 left heade 和 right header.
只给 props 让其全部自定义是最合适的方案。大部分的情况使用 rightContentRender 都能解决

**Comment by super918180** [comment]
SettingsDrawer 变成一个独立组件 ，请问如何安装、使用？

**Comment by clanaid** [comment]
breadcrumbNameMap 是umi依据route生成的吗？
