### ISSUE TITLE
🐛[BUG] 在菜单很多的时候，没有隐藏菜单功能【...】

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro-layout#200]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

**在菜单很多的时候，没有隐藏菜单功能**

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

![image](https://user-images.githubusercontent.com/18542211/69215109-bc015480-0ba3-11ea-9604-eab4a8195b0e.png)

### 🏞 期望结果 [描述你原本期望看到的结果]

![image](https://user-images.githubusercontent.com/18542211/69215081-a7bd5780-0ba3-11ea-97c3-17f16d3f02eb.png)

### © 版本信息

**pro-layout 4.7 以后的版本**

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by kaoding** [comment]
在这个 issue [ https://github.com/ant-design/ant-design-pro-layout/issues/186 ] 里也报过这个 bug

**Comment by ZuhuaLiu** [comment]
我的也是这样
![image](https://user-images.githubusercontent.com/40290781/70026334-7b113300-15da-11ea-8599-e8db12b91ae9.png)这个版本的，本地之前装的依赖可以，服务器线上部署下载依赖，菜单很多就没有隐藏菜单...了。求解决

**Comment by ZuhuaLiu** [comment]
锁定版本就好了

**Comment by fengyibo** [comment]
<img width="1376" alt="961C7C9C-ECBD-44EF-AA6F-172F866E7275" src="https://user-images.githubusercontent.com/1573510/70793451-4cfbd200-1dd6-11ea-815f-aca25ad57b04.png">
可以隐藏了，不过调大窗口后菜单没有恢复

**Comment by chenshuai2144** [comment]
fix in 4.10.0
