### ISSUE TITLE
🐛[BUG]自定义菜单icon时，没有生效或错误

### ISSUE THREAD

**Issue by fangaofeng** [ant-design/ant-design-pro-layout#202]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
router中配置路由时：

//   icon: '/favicon.png',                  菜单没有icon
//   icon: <Icon type="setting" />,    无法渲染的错误
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

      {
        path: '/workbench/index',
        name: '工作台',
        icon: <Icon type='setting' />,
        component: './Workbench/Workbench',
      },
配置为  icon: '/favicon.png'，没有错误，但是也没有图标出现。
### 🏞 期望结果 [描述你原本期望看到的结果]
出现setting的图标
### © 版本信息

- Ant Design Pro-layout 版本: [e.g. 4.7.3]
"antd": "^3.23.6",
- umi 版本  "umi": "^2.9.6",
- 浏览器环境 chrom
- 开发环境 [e.g. mac OS]
vscode window 10
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
`icon: <Icon type='setting' />`时
浏览器打印出下面错误×
Objects are not valid as a React child (found: object with keys {key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead.
    in a (created by BaseMenu)
    in li (created by MenuItem)
    in MenuItem (created by Connect(MenuItem))
    in Connect(MenuItem) (created by Context.Consumer)
    in Trigger (created by Tooltip)
    in Tooltip (created by Context.Consumer)
    in Tooltip (created by Context.Consumer)
    in MenuItem (created by BaseMenu)
    in ul (created by DOMWrap)
    in DOMWrap (created by SubPopupMenu)
    in SubPopupMenu (created by Connect(SubPopupMenu))
    in Connect(SubPopupMenu) (created by Menu)
    in Provider (created by Menu)
    in Menu (created by Context.Consumer)
    in InternalMenu (created by Context.Consumer)
    in Menu (created by BaseMenu)
    in BaseMenu (created by SiderMenu)
    in div (created by Context.Consumer)
    in aside (created by Context.Consumer)
    in InternalSider (created by Context.Consumer)
    in Sider (created by SiderMenu)
    in SiderMenu (created by SiderMenuWrapper)
    in SiderMenuWrapper (created by BasicLayout)
    in section (created by BasicLayout)
    in BasicLayout (created by Context.Consumer)
    in Adapter (created by BasicLayout)
    in div (created by BasicLayout)
    in BasicLayout (created by BasicLayout)
    in BasicLayout (created by ConnectFunction)
    in ConnectFunction (created by Component)
    in Component (created by Component)
    in Authorized (created by _default)
    in _default (created by Component)
    in Component (created by Route)
    in Route (created by RouteWithProps)
    in RouteWithProps (created by ret)
    in ret (created by RouterWrapper)
    in Switch (created by RouterWrapper)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by ConnectFunction)
    in ConnectFunction (created by RouterWrapper)
    in sfc (created by LocaleWrapper)
    in IntlProvider (created by LocaleWrapper)
    in LocaleProvider (created by Context.Consumer)
    in LocaleReceiver (created by ConfigProvider)
    in ConfigProvider (created by LocaleWrapper)
    in LocaleWrapper (created by RouterWrapper)
    in RouterWrapper
    in Provider (created by _DvaContainer)
    in _DvaContainer

**Comment by chenshuai2144** [comment]
config.js 不支持 dom，你只能使用 string

**Comment by fangaofeng** [comment]
basemenu中
不是这么注释的吗？
```
var IconFont = _Icon.createFromIconfontCN({
  scriptUrl: defaultSettings.iconfontUrl
}); // Allow menu.js config icon as string or ReactNode
//   icon: 'setting',
//   icon: 'icon-geren' #For Iconfont ,
//   icon: 'http://demo.com/icon.png',
//   icon: '/favicon.png',
//   icon: <Icon type="setting" />,
```

那如果要自定义icon，只能重写menuItemRender传入prolayout?
