### ISSUE TITLE
👑 [需求] 增加状态栏组件

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro-layout#203]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]

类似vs code下的状态栏，如下：
![image](https://user-images.githubusercontent.com/18542211/69313996-018a5400-0c6e-11ea-9b8f-57b8f3d1332b.png)

**Comment by chenshuai2144** [comment]
emmm，这个要求应该去 antd 提拔

**Comment by kaoding** [comment]
https://github.com/ant-design/ant-design/issues/19857

**Comment by chenshuai2144** [comment]
需要设置一个固定的宽度
