### ISSUE TITLE
👑 [需求] 如何在 collapse 旁边加面包屑

### ISSUE THREAD

**Issue by linyoucheng** [ant-design/ant-design-pro-layout#206]
重写了headerRender之后 collapse 该如何保留

**Comment by chenshuai2144** [comment]
试试 

collapsedButtonRender | custom collapsed button method | (collapsed: boolean) => ReactNode | -
-- | -- | -- | --

**Comment by linyoucheng** [comment]
我是想问：如何再headerRender里使用默认的collapse button而不是去自定义渲染一个 collapse button
