### ISSUE TITLE
👑 [需求] 在 collapse button 后面加面包屑

### ISSUE THREAD

**Issue by linyoucheng** [ant-design/ant-design-pro-layout#208]
### 🥰 需求描述

如何再headerRender里使用默认的collapse button而不是去自定义渲染一个 collapse button

**Comment by chenshuai2144** [comment]
headerRender 第二个参数就是 default dom，如果你要做很大的改动，建议自己构造 collapse

**Comment by linyoucheng** [comment]
确定存在第二个参数吗

**Comment by linyoucheng** [comment]
而且需求只是在原来的collapse button后面加点东西 为什么要搞到那么复杂？

**Comment by linyoucheng** [comment]
pro-layout 版本是 4.5.16

**Comment by chenshuai2144** [comment]
@linyoucheng 因为我们不希望在后面加东西。

**Comment by Sean1514** [comment]
> @linyoucheng 因为我们不希望在后面加东西。
可以解释一下这样设计的依据吗  团队中某些人认为在小屏下 现有的设计占据了不必要的空间  希望和楼主一样实现同样的功能 我说服不了他们

**Comment by afc163** [comment]
试试 headerRender
