### ISSUE TITLE
🐛[BUG] v4.8.3 footRender 没有置底

### ISSUE THREAD

**Issue by kelefun** [ant-design/ant-design-pro-layout#214]
### 期望结果  
恢复到跟v4.8.3之前版本一样的效果

### 复现代码 
antd-design-pro示例代码即可复现
```js
 <ProLayout
      //some code
      footerRender={footerRender}
      {...props}
      {...settings}
    >
        {children}
    </ProLayout>
```

### © 版本信息

- Ant Design Pro Layout 4.8.3
- umi 版本
- 浏览器环境 chrome 版本 78.0.3904.108（正式版本） （64 位
<img width="934" alt="D6E55599-7D57-4deb-926D-6DD5CBBC621B" src="https://user-images.githubusercontent.com/20576242/69816714-e9996e00-1233-11ea-97c9-bc19a8c051b2.png">

**Comment by chenshuai2144** [comment]
这样比较符合预期，footer 应该在内容的下面。
你可以自己设置一下高度

**Comment by kelefun** [comment]
> 这样比较符合预期，footer 应该在内容的下面。原来设置了 height = 100vh
> 你可以自己设置一下高度

建议大佬把特性变更的东西写到changelog或者文档中  (估计是你们精力有限:joy:
