### ISSUE TITLE
🐛[BUG] SSR SettingDrawer issue

### ISSUE THREAD

**Issue by lluzak** [ant-design/ant-design-pro-layout#217]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
SSR issue: Invariant failed: Browser history needs a DOM

Cause: 
https://github.com/ant-design/ant-design-pro-layout/blob/4ba0802a5dec911be2732d8755ae0f7787056e11/src/SettingDrawer/index.tsx#L50
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
give a pr？

**Comment by joesdu** [comment]
> give a pr？
使用SettingDrawer是可以做到生产环境切换主题的,
![image](https://user-images.githubusercontent.com/13188169/71225198-b1f18380-2312-11ea-805d-7d32838e504d.png)希望能够给一个属性用于开启或者关闭这下边的提示以及复制按钮.

**Comment by chenshuai2144** [comment]
hideHintAlert 即可关闭。

**Comment by joesdu** [comment]
> hideHintAlert 即可关闭。

3Q
