### ISSUE TITLE
🐛[BUG]老哥们 跪求去掉这个error的办法啊

### ISSUE THREAD

**Issue by 544751779** [ant-design/ant-design-pro-layout#218]
老哥们 跪求去掉这个error的办法啊

我手动改代码 之后 每次安装个插件 都会被更新掉 又出现这个error了 

Warning: 
Pro-Layout 在 4.7 中支持了 subMenu 的 render, 会导致 menu 变成蓝色的问题。
解决方案如下：https://github.com/ant-design/ant-design-pro-layout/issues/186

**Comment by chenshuai2144** [comment]
下个版本将会去掉。

**Comment by Imhemers** [comment]
v4.9.1版本  fixSiderbar 设置 false 失效了呢  你们快点修复下呀

**Comment by 544751779** [comment]
> 下个版本将会去掉。

ok 感谢开源奉献

**Comment by miaozilong** [comment]
去掉了吗?

**Comment by chenshuai2144** [comment]
去掉了；
