### ISSUE TITLE
🐛[BUG]v4.9.1版本 fixSiderbar失效

### ISSUE THREAD

**Issue by Imhemers** [ant-design/ant-design-pro-layout#223]
fixSiderbar 设置失效, 一直是 true的状态, 也就是一直是固定的, 设置false没起作用, 望修复

© 版本信息
Ant Design Pro 版本: [e.g. 4.0.0]
ant-design/pro-layout 版本: [e.g. 4.9.1]

**Comment by chenshuai2144** [comment]
https://preview.pro.ant.design/
这里无法复现

**Comment by snowtreetree** [comment]
![image](https://user-images.githubusercontent.com/30932683/70719677-685ed280-1d2d-11ea-81c8-74cf68476c83.png)

**Comment by chenshuai2144** [comment]
@snowtreetree 要想办法处理一下了。😫

**Comment by snowtreetree** [comment]
是否有临时性的解决方案，如果直接在sider-bar上增加max-height:100vh;overflow:auto的话，会在sider-bar上出现滚动条（菜单过长的话）。
@chenshuai2144

**Comment by chenshuai2144** [comment]
layout 有一个 contentStyle 的属性，设置 100% 即可

**Comment by snowtreetree** [comment]
这么设置吗。😂
![image](https://user-images.githubusercontent.com/30932683/70773306-114f1100-1db2-11ea-97b1-17f62dd895da.png)
