### ISSUE TITLE
Ant Design Pro Layout 区分前后端

### ISSUE THREAD

**Issue by kzabc** [ant-design/ant-design-pro-layout#225]
请问如何区分layout   
现在想使用Ant Design Pro 实现前后端页面， 前端想使用topmenu  请问如何实现
export default {
  navTheme: 'dark',
  primaryColor: '#1890FF',
  layout: 'sidemenu',
  contentWidth: 'Fluid',
  fixedHeader: false,
  autoHideHeader: false,
  fixSiderbar: false,
  colorWeak: false,
  menu: {
    locale: true,
  },
  title: 'Optometry',
  pwa: false,
  iconfontUrl: '',
} as DefaultSettings;

**Comment by kzabc** [comment]
前后端不同的DefaultSettings

**Comment by chenshuai2144** [comment]
一个 props 而已。 你可以用 props 来设置不用 DefaultSettings
