### ISSUE TITLE
ant-design-pro官方文档/常见问题示例错误🐛[BUG]

### ISSUE THREAD

**Issue by wangtiegang** [ant-design/ant-design-pro-layout#226]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
在 ```入门/常见问题/如何从服务器请求菜单```  处 ```menuData``` 给的示例中 ```routes``` 属性名应为 ```children``` ，如果不看 ts 定义直接复制数据测试的话，结果不符合预期。
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
![image](https://user-images.githubusercontent.com/20106449/70412303-74c5ff80-1a8f-11ea-9786-74f709fb034e.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
来个 pr 吧？

**Comment by wangtiegang** [comment]
已提交 pr 😄

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro-site/pull/325

**Comment by afc163** [comment]
router-and-nav 的英文没改。
