### ISSUE TITLE
🐛[BUG] 4.9.x 有很多问题

### ISSUE THREAD

**Issue by gluefxu** [ant-design/ant-design-pro-layout#229]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
使用最新的master或者 v4.9.7 运行example
1. 顶部和左侧都出现了菜单
2. 右侧设置没有整体样式黑色的选择按钮
3. 左下角有一个莫名其妙的爱心图标和“name”字样
4. 左侧菜单single点击后提示404

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
拉取最新版代码，运行example
### 🏞 期望结果 [描述你原本期望看到的结果]
期望和4.8.x一样
### © 版本信息

- Ant Design Pro 版本: 无
- umi 版本: 2.12.5
- 浏览器环境: 78.0.3904.108
- 开发环境: mac OS

**Comment by chenshuai2144** [comment]
我故意加的。example 是我为了测试功能搞得，里面使用了几乎所有的api。

**Comment by PawelO511** [comment]
wt., 10 gru 2019, 02:12 użytkownik gluefxu <notifications@github.com>
napisał:
