### ISSUE TITLE
ProLayout组件的 props: location 是必须的,文档没有标出来

### ISSUE THREAD

**Issue by dr2009** [ant-design/ant-design-pro-layout#23]
## 背景:
我是直接ant-design-pro-layout搭架子.没有用 umi 那一套...
路由配置渲染从 umi 的 renderRoutes修改来的(当然这些和 bug无关)

## 现象:
面包屑不出现和侧边菜单的二级菜单一直不选中...

最后来了源码 `SiderMenu.tsx`
```js
const { location = { pathname: '/' }, flatMenuKeys = [] } = props;
```
如果不传..使用默认值..那么菜单选中的值就一直是错误的.
面包屑也是如此 `utils/getBreadcrumbProps.tsx`

**Comment by chenshuai2144** [comment]
我改成默认从 window.location

**Comment by dr2009** [comment]
BrowserRouter 使用window.location是可以的.
HashRouter就┑(￣Д ￣)┍ .
感觉要不要文档提示下什么的🙂
