### ISSUE TITLE
🐛[BUG]使用ant-design-pro，设置global.collapsed=true，然而每次刷新页面，侧栏还是会默认展开

### ISSUE THREAD

**Issue by maxmeng93** [ant-design/ant-design-pro-layout#230]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
使用ant-design-pro，设置global.collapsed=true，然而每次刷新页面，侧栏还是会默认展开，默认好像执行了一次onCollapse，传入的值为false

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
你需要这个 api，设置为 false 即可
breakpoint | breakpoints of the responsive layout | Enum { 'xs', 'sm', 'md', 'lg', 'xl', 'xxl' } | lg
-- | -- | -- | --

**Comment by l745230** [comment]
4.8.7 版本,加了breakpoint={false} 手机端还是默认展开.
