### ISSUE TITLE
🧐[问题]如何在生产环境改变primaryColor对侧边栏生效？

### ISSUE THREAD

**Issue by birdycn** [ant-design/ant-design-pro-layout#231]
如何在生产环境改变primaryColor对侧边栏生效？目前好像只有build后才有效果

**Comment by joesdu** [comment]
'@menu-dark-bg': '#23232E',
'@menu-dark-submenu-bg': '#23232E'
设置这两个属性,就能调整侧边栏的背景色,以及侧边栏子分组中的背景色.
