### ISSUE TITLE
👑 [需求]antd现在有v4.0的预发布版本了，希望能支持下

### ISSUE THREAD

**Issue by JrontEnd** [ant-design/ant-design-pro-layout#233]
### 🥰 需求描述 
如题
BaseMenu.js 里还使用旧的 Icon 使用方式，希望可以更新下。
然后跟随 antd，发一个预发布版本，方便使用。

### 🧐 解决方案
无

### 🚑 其他信息 
无

**Comment by chenshuai2144** [comment]
现在还没想到好的办法支持，你可以使用 4.9.0-1 版本，这个版本去掉了icon 功能，让他能跑起来

**Comment by zhangzhi93** [comment]
4.0-rc发布了，pro-layout啥时候也出个版本

**Comment by chenshuai2144** [comment]
会很快！

**Comment by exvu** [comment]
已经发布

**Comment by exvu** [comment]
pro-layout v5

**Comment by chenshuai2144** [comment]
升级5即可支持
