### ISSUE TITLE
🧐[问题] umi-plugin-antd-theme 在最新的example中为什么被注释了呢

### ISSUE THREAD

**Issue by gluefxu** [ant-design/ant-design-pro-layout#235]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
在 [feat: dark drawer (#207)](https://github.com/ant-design/ant-design-pro-layout/commit/a36f2327e95820a2f5af0872e527201d011cc156#diff-6cf585604ce0f7451e1d1cd80a078b12) 这个commit中，加入了umi-plugin-antd-theme

然后在 [fix: fixed the issue that the margin cannot stretch the element](https://github.com/ant-design/ant-design-pro-layout/commit/0109aef64267543f94f637a7e3f822d49c4ea9ad#diff-6cf585604ce0f7451e1d1cd80a078b12) 中，马上又被注释掉了

原来在4.8.3版本中的SettingDrawer中最上面"整体风格设置"中，有第三个按钮，可以设置全黑的界面。可能是因为这个注释，第三个按钮也没有了。

请问是不是官方不推荐 umi-plugin-antd-theme 这种设置方式，还是说仅仅是example的日常调整而已。

如果可以，还是希望能够加上，动态主题功能还是很重要的，另外全黑的也蛮酷的。
谢谢！

**Comment by chenshuai2144** [comment]
太卡了，调试起来不方便
