### ISSUE TITLE
👑 [需求] 能否考虑左侧菜单支持ROR类型的路由规则

### ISSUE THREAD

**Issue by gluefxu** [ant-design/ant-design-pro-layout#242]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
按照ROR页面的URL方式，例如 /orders 是订单列表页面，/orders/new 是新建订单页面，两个页面其实是并列关系，不是层级关系。
但目前pro-layout中，如果/orders/new是当前页面，则/orders的菜单项同样也是高亮状态，似乎是路由匹配的时候，认为是同一路由或者具有层级关系。
现在如果想显示正常的话，只能改为 /orders/list 和 /orders/new 这样不会冲突的形式。

能否通过某个配置来支持此种URL规则

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
我修改了 SiderMenu/BaseMenu 中的 selectedKeys 相关获取逻辑，能够实现效果。只是不确定对现有功能或者是Ant的设计有没有其他影响

**Comment by chenshuai2144** [comment]
现在已经对 path 进行了解耦，还有问题吗？

**Comment by gluefxu** [comment]
更新到最新代码，确实可以了，非常感谢。
