### ISSUE TITLE
无法与nextjs一起工作

### ISSUE THREAD

**Issue by videni** [ant-design/ant-design-pro-layout#245]
我在nextjs上创建了一个[问题](https://github.com/zeit/next.js/issues/9669)，但这个错误似乎与nextjs无关。请看一下，我基本花了几十个小时来解决这个问题，但感觉自己的知识断片了，不知道问题出在哪里。

[错误演示库](https://github.com/videni/with-ant-design-less)

**Comment by qhanw** [comment]
目前我也遇到这个问题，不过在直接使用antd时正常，只有在使用pro-layout时对报如下错误
![image](https://user-images.githubusercontent.com/10607656/73912917-bdaffe00-48f0-11ea-8ce0-6c803f9f2584.png)
@videni 请问下你现在解决了吗？

**Comment by videni** [comment]
@qhanw, 这 的个根本原因，是要引入antd中的less文件时，引入失败，因为node_module中的less文件，一般而言是不需要在编译的，估计是在哪个地方做了排除。为了解决这个问题，我是这样处理的。

```
/* eslint-disable */
const withLess = require('@zeit/next-less')
const lessToJS = require('less-vars-to-js')
const fs = require('fs')
const path = require('path')

// Where your antd-custom.less file lives
const themeVariables = lessToJS(
  fs.readFileSync(path.resolve(__dirname, './assets/antd-custom.less'), 'utf8')
);

const withTM = require('@weco/next-plugin-transpile-modules');
const withPlugins = require('next-compose-plugins');

module.exports = withPlugins([
  [withTM, {
    transpileModules: [
      '@ant-design/pro-layout',
      'antd',
    ],
  }],

  [withLess, {
    cssLoaderOptions: {
      modules: true,
    },
    lessLoaderOptions: {
      javascriptEnabled: true,
      modifyVars: themeVariables, // make your antd custom effective
    },
  }]
])
```

加我微信，这个账号就是我微信的账号。

**Comment by SolidZORO** [comment]
直接用这个 plugin 就好 [`next-plugin-antd-less`](https://github.com/SolidZORO/next-plugin-antd-less) 支持 next.js 9.5 。
