### ISSUE TITLE
👑 [需求]菜单栏默认全部展开

### ISSUE THREAD

**Issue by ywy94ywy** [ant-design/ant-design-pro-layout#248]
之前展开看了源码，是path作为key，我只要获取所有path就能展开所有菜单，

现在菜单的不知道如何全部展开

**Comment by ywy94ywy** [comment]
或者说如何自己设置菜单的key，在config中配置没有效果

**Comment by chenshuai2144** [comment]
设置 menu.defaultOpenAll 为 true 即可了

**Comment by ywy94ywy** [comment]
```
  <ProLayout
        menu={{
          defaultOpenAll: true,
        }}
        logo={logo}
        menuHeaderRender={(logoDom, titleDom) => (
          <Link to="/">
            {logoDom}
            {titleDom}
          </Link>
        )}
        ......
```
是这样添加么，我拿新生成的antdpro测试了下，没有效果诶

**Comment by chenshuai2144** [comment]
提供了一个demo，你看看

https://prolayout.ant.design/example?anchor=%E6%90%9C%E7%B4%A2%E8%8F%9C%E5%8D%95#%E9%BB%98%E8%AE%A4%E6%89%93%E5%BC%80%E6%89%80%E6%9C%89%E8%8F%9C%E5%8D%95

**Comment by ywy94ywy** [comment]
@chenshuai2144 demo 失效了，少了文件
我再用新的antdpro，获取全部区块后添加menu={{ defaultOpenAll: true }}，还是不能全部展开

**Comment by chenshuai2144** [comment]
你的菜单能发出来看看嘛

**Comment by ywy94ywy** [comment]
@chenshuai2144 大哥我知道什么问题了，反复试验，
我在4.9.11的时候，defaultOpenAll属性无效，但是可以动态获取菜单
![image](https://user-images.githubusercontent.com/22499767/71455586-9b46a300-27d0-11ea-8398-5102bab9ae9c.png)

当我升级到4.10.1的时候，defaultOpenAll属性有效（如果我菜单定死的话），但是想要动态获取菜单就会报如下错误
![image](https://user-images.githubusercontent.com/22499767/71455558-7fdb9800-27d0-11ea-96be-9ec549d15086.png)
