### ISSUE TITLE
期望暴漏 ConfigProvider 的属性支持 👑 [需求]

### ISSUE THREAD

**Issue by yuanguandong** [ant-design/ant-design-pro-layout#250]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
业务对象选择器会包含一个弹窗，业务对象选择器失去焦点的逻辑有一条，点击这个业务对象所包含的弹窗时不去失去焦点。我用了点击事件拦截的方法去做，这时候就需要指定getPopupContainer为父级节点。
### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
查了源码，其中ConfigProvider的getPopupContainer逻辑写死的，期望暴漏出来可以支持用户定义，谢谢了！
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/13197560/71225040-47404800-2312-11ea-81f9-9e8c533e3464.png)

**Comment by chenshuai2144** [comment]
ConfigProvider 是支持嵌套的，你在 modal 里面加一个就可以解决问题了。

**Comment by yuanguandong** [comment]
> ConfigProvider 是支持嵌套的，你在 modal 里面加一个就可以解决问题了。

谢谢，我试试
