### ISSUE TITLE
🧐[问题]打开（hideInMenu:true的）隐藏页面，菜单全部关闭了

### ISSUE THREAD

**Issue by WuTongLife** [ant-design/ant-design-pro-layout#251]

**Comment by chenshuai2144** [comment]
来个重现？
没有理解你的问题

**Comment by WuTongLife** [comment]
大致就是这样子的问题
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"陈帅"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月20日(星期五) 晚上8:47
收件人:&nbsp;"ant-design/ant-design-pro-layout"<ant-design-pro-layout@noreply.github.com&gt;;
抄送:&nbsp;"梧桐樹下的愛ピ"<834659804@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro-layout] 🧐[问题]打开（hideInMenu:true的）隐藏页面，菜单全部关闭了 (#251)




来个重现？
 没有理解你的问题

**Comment by WuTongLife** [comment]
有人提出来了，比我描述的详细得多
