### ISSUE TITLE
👑 [需求] 左侧菜单栏搜索

### ISSUE THREAD

**Issue by iuok1001** [ant-design/ant-design-pro-layout#253]
### 🥰 需求描述

想要【菜单栏搜索】新功能，如果菜单过多，需要有地方可以筛选，支持拼音

### 🧐 解决方案

类似 http://www.zui.sexy/#control/button (右上角-双栏排版)

### 🚑 其他信息

![69496503-db82df00-0f0d-11ea-98a1-539133478cc0](https://user-images.githubusercontent.com/18457259/70814694-fbb80680-1e06-11ea-9485-a935fb9a48ef.png)

拼音筛选
![Snipaste_2019-12-14_00-18-57](https://user-images.githubusercontent.com/18457259/70815511-982ed880-1e08-11ea-8ce5-b2d9a3e707a0.png)

**Comment by chenshuai2144** [comment]
@iuok1001  
写了一个demo 看看
