### ISSUE TITLE
🧐[问题] path 解耦之后无法实现多个路由对应一个菜单项

### ISSUE THREAD

**Issue by shend** [ant-design/ant-design-pro-layout#254]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

4.9.10 及之前版本，可以让多个路由对应一个菜单项，之后的版本则会匹配到根路由 “/” 对应的菜单项，或者无法匹配到菜单项。

为什么要这么做？举个例子，我有3个路由 `/articles` 、 `/articles/new`、`/articles/:id([0-9]+)/edit`，这3个路由对应3个页面，但是我只需要一个菜单，我就会给3个路由相同的name，但是后两个路由配置`hideInMenu: true`，这样后两个路由依旧会使用第一个路由的菜单。

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

菜单配置如下：
```
// .umirc.ts
{
    routes: [
        {
          name: 'articles',
          icon: 'book',
          path: '/articles',
          component: './Articles',
          exact: true,
        },
        {
          path: '/articles/new',
          name: 'articles',
          component: './Articles/New',
          hideInMenu: true,
        },
        {
          path: '/articles/:id([0-9]+)/edit',
          name: 'articles',
          component: './Articles/Edit',
          hideInMenu: true,
        },
    ]
}
```

完整仓库地址：
https://github.com/shend/report01

查看不同效果，请指定旧版本：
`yarn add @ant-design/pro-layout@4.9.10`

**Comment by chenshuai2144** [comment]
你可以自己设置 key，在 congfig.js 中设置相同的 key 即可

**Comment by shend** [comment]
我在 .umirc.ts/congfig.ts  中设置 key 没有用，是否还需要修改其他地方？

**Comment by chenshuai2144** [comment]
我去看看你的重现

**Comment by chenshuai2144** [comment]
算法不够贪心造成的，
/a/b 并不能匹配 /a, 我将很快修复。
