### ISSUE TITLE
👑 [需求]希望SettingDrawer能够提供属性隐藏部分元素

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro-layout#255]
### 🥰 需求描述 [希望可以在SettingDrawer中新增元素hideCopy属性用于隐藏拷贝设置按钮,
同时,当hideCopy与hideHintAlert值都为真的时候隐藏最下边的分割线.]

### 🧐 解决方案 [新增hideCopy或者hideCopyBtn属性用于隐藏途中的按钮
![image](https://user-images.githubusercontent.com/13188169/71305844-498acb00-2414-11ea-9030-4738881fef4b.png)
当hideCopy属性与hideHintAlert属性都为真值时隐藏最下边的分割线,
若是可以希望能够提供属性能够自定义HintAlert元素的文案.
]

**Comment by chenshuai2144** [comment]
来个 pr？

**Comment by joesdu** [comment]
> 来个 pr？

pr已经提交.
