### ISSUE TITLE
🐛[BUG]自定义菜单的icon，出现错误项目不能正常运行

### ISSUE THREAD

**Issue by OutBigpeng** [ant-design/ant-design-pro-layout#257]
使用create-umi初始化项目 ant-pro  -> javascript 
"@ant-design/pro-layout": "^4.9.11"
自定义菜单的icon，出现错误项目不能正常运行
错误截图
![image](https://user-images.githubusercontent.com/23396573/71333260-5c1c1600-2574-11ea-9093-3f6ee4db4a26.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by joesdu** [comment]
菜单按钮好像不支持自定义,我也没试过.留言用来学习自定义方法..

**Comment by chenshuai2144** [comment]
@OutBigpeng 你是如何自定义的？有相关的重现吗？

**Comment by chenshuai2144** [comment]
https://prolayout.ant.design/example#iconfont
这里有个demo
@joesdu  你可以看看

**Comment by OutBigpeng** [comment]
@chenshuai2144  
`<ProLayout
 menuDataRender={this.getMenuData}>
</ProLayout>
`
以下是getMenuData 方法中item，这样的格式就报错，如果将icon替换成icon:'smile'是可以正常运行的。
```
{
          key: menu.id,
          name: menu.name,
          icon: <Icon type={'smile'}  />, 
          path: menu.url, 
          exact: true,
}

```

**Comment by chenshuai2144** [comment]
@OutBigpeng  好，非常感谢。

**Comment by joesdu** [comment]
我在config/default中添加了iconfontUrl的链接,然后在iconfont网站中将项目的名字都改成了icon- 开头的,在路由配置文件中直接输入图标名称无法正常加载,应该是Umi框架的限制.目前智能用AntD中默认的图标内容,看你这个链接中的demo进行在线预览是可以正常显示的.但是我又不希望将url和路由配置写到BaseLayout中.先暂时只用默认图标吧.其他地方可以使用Icon. createFromIconfontCN创建图标,这个问题希望以后Umi社区和AntD Pro 社区能够沟通一下.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: 陈帅<mailto:notifications@github.com>
发送时间: 2019年12月24日 10:07
收件人: ant-design/ant-design-pro-layout<mailto:ant-design-pro-layout@noreply.github.com>
抄送: Joe Du<mailto:dygood@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [ant-design/ant-design-pro-layout] 🐛[BUG]自定义菜单的icon，出现错误项目不能正常运行 (#257)


https://prolayout.ant.design/example#iconfont
这里有个demo
@joesdu<https://github.com/joesdu> 你可以看看
