### ISSUE TITLE
👑更好的主题 [需求]

### ISSUE THREAD

**Issue by aishen1874** [ant-design/ant-design-pro-layout#260]
### 🥰 需求描述
导航栏的颜色是有一点偏蓝的（颜色偏冷），如果配置的主题 primary-color 是暖色的话，那么导航栏的颜色就会显得很不协调，特别是在整体暗色的主题下。希望能改善一下

**Comment by kaoding** [comment]
能否增加接口可以修改“导航栏”的背景色（或者增加背景图片）

**Comment by chenshuai2144** [comment]
will fix in 6.x
