### ISSUE TITLE
🐛[BUG] 路由里有可选参数的时候，面包屑数据不对

### ISSUE THREAD

**Issue by yunwuxin** [ant-design/ant-design-pro-layout#261]
路由里有可选参数的时候 
访问带参数的地址的时候生成的面包屑数据不对
产生了两个一样的
![image](https://user-images.githubusercontent.com/2168125/71446058-68fa5e80-275a-11ea-9e5d-8284dedf2153.png)
![image](https://user-images.githubusercontent.com/2168125/71446078-921aef00-275a-11ea-845f-cee4601405e6.png)
![image](https://user-images.githubusercontent.com/2168125/71446099-c1316080-275a-11ea-9cca-21e0b501fc9e.png)

**Comment by chenshuai2144** [comment]
去了一下重，4.10.3 已经修复。
