### ISSUE TITLE
🧐[问题]logo和title的边距问题

### ISSUE THREAD

**Issue by phoema** [ant-design/ant-design-pro-layout#263]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
在4.10.0中
边距是 
.ant-pro-sider-menu-logo：padding-left:24px

在4.10.1中 修改为了
.ant-pro-sider-menu-logo：padding: 0 24px

导致之前的文字长度由于少的24px出现折行
请问如何自定义这个样式
.ant-pro-sider-menu-logo

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
    "@ant-design/pro-layout": "4.10.0",
    "@ant-design/pro-layout": "4.10.1",

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/8730272/71452975-edcd9280-27c3-11ea-8145-39804e61d049.png)

**Comment by chenshuai2144** [comment]
```
.ant-pro-sider-menu-logo{}
```
这些用这个吧

**Comment by ilaipi** [comment]
> ```
> .ant-pro-sider-menu-logo{}
> ```

怎么能覆盖这个class呢，我想把padding去掉。。

**Comment by chenshuai2144** [comment]
在 global 里面写死

**Comment by phoema** [comment]
好的，我以为不用写在通用样式里，能够通过传入配置改写。

**Comment by ilaipi** [comment]
> 在 global 里面写死

我在`src/global.less`里面，加了：

```
.ant-pro-sider-menu-logo {
  padding: 0 !important;
}
```

解决了

**Comment by chenshuai2144** [comment]
@ilaipi important 太危险了。

```
.ant-pro-basicLayout .ant-pro-sider-menu-logo{
  padding: 0;
}
```

**Comment by ilaipi** [comment]
好的 谢谢  我试试 对前端不太懂的😬

陈帅 <notifications@github.com> 于2019年12月31日周二 上午11:15写道：
