### ISSUE TITLE
🐛[BUG]s升级到4.10.1后，动态获取menuData报错

### ISSUE THREAD

**Issue by ywy94ywy** [ant-design/ant-design-pro-layout#264]
版本从4.9.11 => 4.10.1后
我想动态获取菜单，从[] 变成 [...something] 报错
![image](https://user-images.githubusercontent.com/22499767/71455318-700f8400-27cf-11ea-86ba-80db136cdcc3.png)
![image](https://user-images.githubusercontent.com/22499767/71455291-566e3c80-27cf-11ea-8b3a-ee0e77264308.png)

**Comment by ywy94ywy** [comment]
退回4.9.11后，动态获取菜单恢复作用

**Comment by chenshuai2144** [comment]
menu 的数据给我一下

**Comment by ywy94ywy** [comment]
const menu = [
  {
    path: '/a',
    name: 'a',
    children: [
      {
        path: '/aa',
        name: 'aa',
      },
    ],
  },
  {
    path: '/b',
    name: 'b',
    children: [
      {
        path: '/bb',
        name: 'bb',
      },
    ],
  },
]

**Comment by chenshuai2144** [comment]
修复了，非常感谢。
