### ISSUE TITLE
🐛[BUG] 从服务器请求菜单 报错

### ISSUE THREAD

**Issue by Wildlifes** [ant-design/ant-design-pro-layout#266]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
通过ant design pro 官网的例子 ，后台获取菜单报错
![image](https://user-images.githubusercontent.com/26505011/71461941-a0195000-27ec-11ea-835f-8dfb3079b1d3.png)

项目之前使用layout版本是4.9.11， 升级4.10.1报错

### 🏞 期望结果 [描述你原本期望看到的结果]
渲染正常

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
通过ant design pro 官网的例子

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
@Wildlifes  重装一下依赖

**Comment by Wildlifes** [comment]
多谢
