### ISSUE TITLE
🐛[BUG]隐藏子菜单后，路由定位到子菜单，左侧的一级菜单不是选中状态

### ISSUE THREAD

**Issue by zhangzhi93** [ant-design/ant-design-pro-layout#270]
### 🐛 bug 描述 

隐藏子菜单后，路由定位到子菜单，左侧的一级菜单不是选中状态

### 📷 复现步骤
设置```hideChildrenInMenu: true```不显示子菜单，子菜单写在了pageHeader里面的tabs，当路由到子菜单时，左侧的父菜单不被选中。

### 🏞 期望结果
当路由到统计或者项目设置时能选中项目名称

### 💻 复现代码 
```jsx
<ProLayout/>
```
config.js
```js
{
  path: '/:id/dashboard',
  name: '项目名称',
  component: './Base/BaseLayout',
  hideChildrenInMenu: true,
  routes: [
    {
      path: '/:id/dashboard',
      redirect: '/:id/dashboard/statistics',
    },
    {
      path: '/:id/dashboard/statistics',
      name: '统计',
      component: './Base/Statistics',
    },
    {
      path: '/:id/dashboard/project',
      name: '项目设置',
      component: './Base/ProjectSetting',
    },],
},
```

### © 版本信息

- Ant Design Pro 版本: [4.0.0]
- umi 版本 [2.12.6]
- 浏览器环境 [chrome]
- 开发环境 [windows]

### 🚑 其他信息 
除此之外还想请教一个问题，其中的项目名称是动态的，菜单的选中状态是根据config.js中的name吗？这样的话怎样动态改变config里面的name值，或者能通过什么方法能实现选中

**Comment by chenshuai2144** [comment]
是 根据 path 来的、


我无法重现无法选中拿到的问题。
