### ISSUE TITLE
🧐[问题]移动端,默认会展开左侧菜单栏,如何设置为默认不展开?

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design-pro-layout#271]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
更新到最新的4.10.2
在BasicLayout.tsx中配置了breakpoint={false}
每次刷新页面都会展开左侧菜单栏.

**Comment by l745230** [comment]
![image](https://user-images.githubusercontent.com/15940920/71710835-16dfca00-2e39-11ea-86fb-38ab4c234913.png)
@chenshuai2144  
V4怎么才能在像V2那样,在移动端访问时
1.默认不展开左侧菜单. 
2.点击菜单时,菜单自动隐藏.

![image](https://user-images.githubusercontent.com/15940920/71710912-645c3700-2e39-11ea-88c3-57963a878405.png)

**Comment by l745230** [comment]
基本上layout的issue都翻过去了,没找到有效信息..

**Comment by darkfiredarkhalo** [comment]
也在头疼这个问题,感觉新版问题挺多

**Comment by chenshuai2144** [comment]
@l745230  设置 collapsed？

**Comment by darkfiredarkhalo** [comment]
不是,是侧边菜单自动展开,法案可以通过设置`disableMobile`解决

**Comment by chenshuai2144** [comment]
默认不打开比较合理，但是好害怕希望默认打开

**Comment by l745230** [comment]
@chenshuai2144 @darkfiredarkhalo 不能用disableMobile.
disableMobile设置后,侧边菜单栏功能直接没有了.

效果应该是默认不展开侧边栏菜单. 点击
![image](https://user-images.githubusercontent.com/15940920/72500462-7c877980-386f-11ea-84fe-90abf99cd9b6.png)再展开.

**Comment by l745230** [comment]
要多就是像V2版本移动端的交互啊

**Comment by l745230** [comment]
pro-layout更新到4.10.8后,不会再默认展开侧边菜单栏了.
但是还有个问题,点击菜单后,侧边栏不会自动隐藏,
