### ISSUE TITLE
🐛[BUG]缩小屏幕宽度，在fixedHeader模式下header左侧有80px的空白

### ISSUE THREAD

**Issue by zhangzhi93** [ant-design/ant-design-pro-layout#272]
### 🐛 bug 描述 

缩小屏幕宽度，在fixedHeader模式下header左侧有80px的空白

### 📷 复现步骤
设置``` fixedHeader: true,fixSiderbar: true```，调整浏览器宽度，当窄到左侧菜单隐藏后，header左边有80px的空白，查看css，宽度设置为```width:calc(100% - 80px)```

### 🏞 期望结果 [描述你原本期望看到的结果]

缩小屏幕宽度，header为100%

### 💻 复现代码 
[screenshot](https://raw.githubusercontent.com/zhangzhi93/staticResources/master/20191230220143.png)
### © 版本信息

- Ant Design Pro 版本: 4.0.0
- umi 版本 
- 浏览器环境 chrome
- 开发环境  windows

**Comment by chenshuai2144** [comment]
已经修了，一会发版本就好了
