### ISSUE TITLE
🐛[BUG] fixedheader左侧出现空白，width不是100%

### ISSUE THREAD

**Issue by VSir2018** [ant-design/ant-design-pro-layout#274]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
fixedheader的情况下，chrome开发者工具切换为手机模式，不显示侧边栏的时候，header左侧出现空白；原因为：width: calc(100% - 80px)
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
chrome开发者工具切换为手机模式，隐藏侧边栏
### 🏞 期望结果 [描述你原本期望看到的结果]
header width: 100%
### © 版本信息

- Ant Design Pro 版本: 4.10.2
- umi 版本 2.12.7
- 浏览器环境 chrome
- 开发环境 windows 10

**Comment by chenshuai2144** [comment]
已经修复了。
