### ISSUE TITLE
🐛[BUG] 4.10.4版本 异步菜单无法渲染

### ISSUE THREAD

**Issue by beeant0512** [ant-design/ant-design-pro-layout#281]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
index.js:1 Warning: The final argument passed to useEffect changed size between renders. The order and size of this array must remain constant.

Previous: []
Incoming: [[object Object]]
    in SiderMenuWrapper (created by BasicLayout)

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
"@ant-design/pro-layout" 使用 4.10.4版本

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
useEffect(() => {
    if (dispatch) {
      dispatch({
        type: 'user/fetchCurrent',
      });
      dispatch({
        type: 'global/menu',
        callback: res => setMenuData(res),
      });
    }
  }, []);

...

 menuDataRender={() => menuData}

### © 版本信息
    "@ant-design/pro-layout": "^4.10.4",

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 ^2.8.7
- 浏览器环境 chrome
- 开发环境 windows10

**Comment by Simon-Bin** [comment]
同样遇到该问题，试过重新装依赖无效

**Comment by Simon-Bin** [comment]
#264 bug复现

**Comment by 86100488z** [comment]
首次请求的时候能渲染，按F5之后也走网络请求 但是不渲染

**Comment by xuxuMaster** [comment]
我也碰到相同问题，但是我旧版本代码没问题，新安装依赖就出现无法渲染，由此确认为依赖版本导致问题出现。昨天一晚上搞这个，我这个后端愁的头发都快没几根了。
解决方案：package.json中 "@ant-design/pro-layout": "^4.8.3"把版本号前面那个“^”删掉，重新安装依赖，不要使用最新版本

**Comment by chenshuai2144** [comment]
```
menuDataRender={() => [...menuData]}
```
试试这样呢，可能 react 认为返回的 menuData 是 === 的

**Comment by chenshuai2144** [comment]
感觉你们在挖坟，删除 lock 重新安装一下依赖试试

**Comment by 86100488z** [comment]
> 感觉你们在挖坟，删除 lock 重新安装一下依赖试试
> 这个问题应该是 #264 已经修复了

我们每次部署都是删掉旧的docker，重新执行npm install ，lock肯定也是不存在的。所以每次都是安装最新版

**Comment by chenshuai2144** [comment]
我尝试了这个
https://prolayout.ant.design/menu

**Comment by Simon-Bin** [comment]
现在master 分支代码如下
![image](https://user-images.githubusercontent.com/26505011/71951013-66950b80-3214-11ea-9d78-5e924fda752b.png)

#264 修复后的代码应该被覆盖了

**Comment by chenshuai2144** [comment]
@beeant0512  @Simon-Bin 因为发了一个错误版本的依赖包导致的，大家更新一下依赖

**Comment by Simon-Bin** [comment]
奥力给，没问题了

**Comment by chenshuai2144** [comment]
@beeant0512 非常感谢你的 pr
