### ISSUE TITLE
🐛[BUG] 刷新后不能自动根据”路由“定位对应的”菜单项“上

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro-layout#284]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
![image](https://user-images.githubusercontent.com/18542211/71951837-5a5e7d80-3217-11ea-816c-38e94f5d11b0.png)

### 🏞 期望结果 [描述你原本期望看到的结果]

![image](https://user-images.githubusercontent.com/18542211/71951814-461a8080-3217-11ea-87af-2a96c7516553.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by WeCantStop** [comment]
+1，同样的问题

**Comment by qietugou** [comment]
自己撸把 提供了配置 `selectedKeys`

**Comment by kaoding** [comment]
以前的版本是好的，包括预览也是好的（https://preview.pro.ant.design/）
@chenshuai2144

**Comment by chenshuai2144** [comment]
我过度优化了，google reload 竟然不会触发 组件的重新加载。导致没有重新计算。

**Comment by WeCantStop** [comment]
> 我过度优化了，google reload 竟然不会触发 组件的重新加载。导致没有重新计算。

近几天可以发个版优化下么~

**Comment by chenshuai2144** [comment]
4.17 已经发布了

**Comment by l745230** [comment]
@chenshuai2144 
移动端,侧边栏.更新4.1.8后, 刷新,路由会定位到对应的菜单项上.

但是如果二级菜单被定位到, 一级菜单没有自动展开.
