### ISSUE TITLE
Menu customization 🧐[问题]

### ISSUE THREAD

**Issue by harishjus4u** [ant-design/ant-design-pro-layout#285]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
Is it possible to customize side bar menu similar to below screenshot?
(Menu group icon on left and menu items for that group on right)
### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/33625676/71957356-8a0b8680-3213-11ea-98a3-e573367aa472.png)

**Comment by chenshuai2144** [comment]
you can look here
