### ISSUE TITLE
🐛[BUG]抽屉中弹出模态框被盖住的问题

### ISSUE THREAD

**Issue by phoema** [ant-design/ant-design-pro-layout#286]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
在4.5.16中，能够在抽屉中正常弹出模态框
在4.10.5、4.10.5中在抽屉中弹出模态框未正常显示，但是遮罩加黑了，初步判断是盖在了抽屉的后面。

其他组件均未调整版本号，初步定为是proLayout的版本切换导致

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
在列表页面弹出详情的抽屉，在抽屉政打开模态框出现此问题

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
4.10.5
- umi 版本
2.9.6
- 浏览器环境

- 开发环境 [e.g. mac OS]

**Comment by phoema** [comment]
初步分析问题出在WrapContent.tsx

        getPopupContainer: function getPopupContainer() {
          if (!isChildrenLayout && _this2.ref) {
            return _this2.ref;
          }

          return document.body;

这段代码更改了antd的默认属性

在antd中getPopupContainer
弹出框（Select, Tooltip, Menu 等等）渲染父节点，默认渲染到 body 上。

而我们基于antd的默认属性是没有再次显性指定的，当我显性指定了抽屉中弹出的modal的
getContainer={document.body}后，会正常，但是项目中存在大量antd默认则我们不显性指定的modal。

另外 if (!isChildrenLayout && _this2.ref) {这句话是说不是子布局且有ref吗？为什么是!isChildrenLayout 呢？

**Comment by chenshuai2144** [comment]
@phoema  layout 嵌套 layout 才会这样的。默认是不会覆盖的。你可以自行设置，

**Comment by phoema** [comment]
是的，BasicLayout外面包裹了一层SecurityLayout
isChildrenLayout设置为true是为了描述这个问题的吗，
setting的配置属性说明可以多写写，跟代码才发现这个属性。

**Comment by chenshuai2144** [comment]
@phoema  里面会吃掉 render dom。所以才会这样默认不要设置 isChildrenLayout

**Comment by phoema** [comment]
很抱歉，我现在有点不太明白
1、目前路由是BasicLayout外面包裹了一层SecurityLayout
2、ProLayout最新版本4.10.7，我不设置isChildrenLayout的情况下，抽屉中弹出模态框被盖住显示在后面
3、昨天我跟踪了ProLayout的源码，设置了isChildrenLayout，解决了盖住的问题。

4、您说所以才会这样默认不要设置 isChildrenLayout，请问设置了吃掉了 render dom会产生什么问题？

我现在两难，请问我该如何处理，设置isChildrenLayout: true，解决了modal的问题会产生其他不可预料的情况吗？

**Comment by chenshuai2144** [comment]
@phoema  是我的 bug，你可以稍微等一下吗？

**Comment by phoema** [comment]
好的，非常感谢，辛苦了

**Comment by chenshuai2144** [comment]
@phoema  发了版本了，你再试试看

**Comment by phoema** [comment]
已解决
