### ISSUE TITLE
🐛[BUG] Style is messed up

### ISSUE THREAD

**Issue by leon0707** [ant-design/ant-design-pro-layout#287]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
<img width="1920" alt="Screen Shot 2020-01-08 at 12 53 50 PM" src="https://user-images.githubusercontent.com/523684/72003053-98a76d00-3216-11ea-8603-f54e7a0b2e19.png">

The layout is messed up. Height is not 100%.
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
Install the latest v4.10.5
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import ProLayout from '@ant-design/pro-layout';

import 'antd/dist/antd.css';

ReactDOM.render(<ProLayout />, document.getElementById('root'));
```
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
you must config less-loader.
prolayout not support layout.css
