### ISSUE TITLE
🐛[BUG] 刷新一下浏览器，页面组件渲染14次

### ISSUE THREAD

**Issue by winter-ice** [ant-design/ant-design-pro-layout#288]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
刷新一下浏览器，页面组件渲染14次
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
新建页面组件，在渲染函数中随便打印什么东西
### 🏞 期望结果 [描述你原本期望看到的结果]
希望能优化一下，有点夸张
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
应该是 4 次，剩下的应该是你自己触发的。
你发现了 function 组件的一个特性。要是在意这个可以用 class 组件，心态会好很多

**Comment by winter-ice** [comment]
dev 环境下 热更新是打印3次，手动点击浏览器刷新是打印十几次，另外点击菜单即使路由没变还是会打印，感觉这里可以优化下

**Comment by winter-ice** [comment]
function组件的渲染也是有优化空间的吧不是可以传值来确定是否触发更新么

**Comment by chenshuai2144** [comment]
function 现在没有优化的方法的，只要更新整个树都会触发更新。但是都是 update 不是重新创建。
但是 dom 是没有变化的，所以性能是差不多的。

**Comment by xiaohuoni** [comment]
应该会重复触发 `useEffect`

**Comment by chenshuai2144** [comment]
useEffect 不会的。

**Comment by xiaohuoni** [comment]
我写过一个类似的bug

**Comment by winter-ice** [comment]
useEffect 不传 `[]` 的话也会触发多次

**Comment by chenshuai2144** [comment]
useEffect 一定要传 [], 不然就是一个普通的 function 了
