### ISSUE TITLE
菜单栏点击后路由如何跳转

### ISSUE THREAD

**Issue by Luxiaoshi** [ant-design/ant-design-pro-layout#289]
菜单栏点击后路由如何跳转，以下是我的配置，但是点击菜单栏不会进行路由跳转，是有其他需要配置的吗
![image](https://user-images.githubusercontent.com/8713879/72044458-bfd16d80-32ee-11ea-97cf-a0f7bc6e431a.png)

**Comment by xiaohuoni** [comment]
怎么处理的，我也想问这个问题

**Comment by fanlide** [comment]
在[文章](https://pro.ant.design/docs/layout-component-cn#prolayout)中有举例

![image](https://user-images.githubusercontent.com/20534139/77603345-cdd87700-6f4a-11ea-98e3-d820e1466847.png)
