### ISSUE TITLE
🐛[BUG]ProLayout@4.10.0,DatePicker选择器组件在移动端无法左右滑动,造成无法在移动端选择日期

### ISSUE THREAD

**Issue by darkfiredarkhalo** [ant-design/ant-design-pro-layout#293]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解] 

直接使用ant-design-pro模板创建项目,@ant-design/pro-layout的版本是`^4.10.0`,当在移动端运行时,日期选择器组件展开之后无法左右滑动,造成移动端无法选择时间

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

新建ant-design-pro模板项目,移动端运行项目;或者将老项目的pro-layout换成新版

### 🏞 期望结果 [描述你原本期望看到的结果]

不影响移动端选择时间

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

参考复现步骤

### © 版本信息

- Ant Design Pro 版本:  4.10.0
- umi 版本:  2.8.7
- 浏览器环境:  移动端
- 开发环境 : mac OS 10.15.2

**Comment by chenshuai2144** [comment]
没有看懂，来个截图？

**Comment by darkfiredarkhalo** [comment]
<img width="724" alt="WeChat5d4461c0b742273c204e6b10aac1366d" src="https://user-images.githubusercontent.com/13959162/72237838-cde8fc00-3616-11ea-822e-b77edf7042f4.png">
红框所示组件为ant design的日期选择器组件,在移动端弹出之后,如果使用最新的`@ant-design/pro-layout`,在移动端无法左右滑动时间选择器,造成移动端无法选择时间,降低`pro-layout`版本,问题解决

**Comment by chenshuai2144** [comment]
具体排查一下原因好了。是因为没有出现滚动条吗?

**Comment by darkfiredarkhalo** [comment]
同样的代码,切换`ant-design/pro-layout`的版本(4.9.0-0/4.10.0),日期选择器的表现不一致,算了,我还是关了吧

**Comment by chenshuai2144** [comment]
@darkfiredarkhalo 最好找一下问题是什么，不然可能在别的地方坑了你

**Comment by darkfiredarkhalo** [comment]
嗯嗯,现在时间有点紧,等后边有时间了吧,非常感谢!
