### ISSUE TITLE
异步获取菜单没有选中当前路由的菜单

### ISSUE THREAD

**Issue by Luxiaoshi** [ant-design/ant-design-pro-layout#297]
![image](https://user-images.githubusercontent.com/8713879/72408111-cbb0aa00-379c-11ea-8179-6e126e4ab927.png)
这是我的代码，请求菜单以后，希望/users/list对应的用户列表菜单可以被选中，但是目前没有被选中，应该如何操作。

**Comment by chenshuai2144** [comment]
模仿这个写吧
https://prolayout.ant.design/menu#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8A%A0%E8%BD%BD-menu

**Comment by Luxiaoshi** [comment]
@chenshuai2144 
demo上也是这样的啊，首次加载不会选中当前路由的菜单
只有做了一些操作才会选中
![image](https://user-images.githubusercontent.com/8713879/72590350-6f828d00-3938-11ea-88bd-d1589cc91b5b.png)
![image](https://user-images.githubusercontent.com/8713879/72590433-9ccf3b00-3938-11ea-9a06-1532b4bc7c8e.png)
