### ISSUE TITLE
👑 [需求]如何禁止菜单自动隐藏（sideMenu）

### ISSUE THREAD

**Issue by WeCantStop** [ant-design/ant-design-pro-layout#299]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
目前sideMenu是根据屏幕大小来的，当屏幕小于一定宽度时候会展示icon形式，如何禁止sideMenu自动收缩成icon形式。

**Comment by chenshuai2144** [comment]
breakpoint={false}

**Comment by WeCantStop** [comment]
> breakpoint={false}

tks
