### ISSUE TITLE
V4.11版本和V4.5.5版本不兼容，导致最新版create-umi创建的项目通过区块插入空白页失败。

### ISSUE THREAD

**Issue by zhangbo0724** [ant-design/ant-design-pro-layout#301]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
已经修复了，可以在试试

**Comment by zhangbo0724** [comment]
ok,3ks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"陈帅"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月20日(星期一) 上午10:25
收件人:&nbsp;"ant-design/ant-design-pro-layout"<ant-design-pro-layout@noreply.github.com&gt;;
抄送:&nbsp;"张波"<37738055@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro-layout] V4.11版本和V4.5.5版本不兼容，导致最新版create-umi创建的项目通过区块插入空白页失败。 (#301)




Closed #301.
