### ISSUE TITLE
🐛[BUG]顶部导航布局下,菜单问题

### ISSUE THREAD

**Issue by MLDIE** [ant-design/ant-design-pro-layout#302]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
处于顶部导航布局的时候, 菜单数量过多后面会用 `···` 来省略, 但是显示的菜单是根据浏览器宽度来定的, 所以当二级菜单过多导致浏览器出现竖向滚动条的时候, 最后一个菜单被省略, 然后出现不停地显示消失的情况

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

下面动图有体现

### 🏞 期望结果 [描述你原本期望看到的结果]

给menu宽度留一个阈值, 不会因为出现滚动条而导致某个菜单被隐藏

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]  "@ant-design/pro-layout": "^4.10.8"
- umi 版本 "^2.8.7"
- 浏览器环境 Google Chrome 79.0.3945.88
- 开发环境 [win 10]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![hello](https://user-images.githubusercontent.com/13941674/72604072-2d1b7900-3955-11ea-8083-274837e139e7.gif)

**Comment by chenshuai2144** [comment]
fixed in 5.x
