### ISSUE TITLE
🐛[BUG]不兼容antd4

### ISSUE THREAD

**Issue by ywy94ywy** [ant-design/ant-design-pro-layout#303]
![image](https://user-images.githubusercontent.com/22499767/72674086-bd6cd180-3aad-11ea-87e3-eaf300ead82d.png)
应该是icon的引用方式变化造成的

**Comment by ywy94ywy** [comment]
求兼容antd4和father-doc，3个都是我喜欢的工具，不能一起用好难受啊

**Comment by chenshuai2144** [comment]
@ywy94ywy  看看这个文章，layout 要使用 beta 版本
https://pro.ant.design/blog/antd-4.0-cn

**Comment by birdycn** [comment]
> @ ywy94ywy 看看这个文章，layout要使用beta版本
> https://pro.ant.design/blog/antd-4.0-cn

已经使用antd4-codemod src运行了，还是报错antd_es_icon__WEBPACK_IMPORTED_MODULE_1__.default.createFromIconfontCN is not a function

**Comment by KoalaHui** [comment]
> > @ ywy94ywy 看看这个文章，layout要使用beta版本
> > https://pro.ant.design/blog/antd-4.0-cn
> 
> 已经使用antd4-codemod src运行了，还是报错antd_es_icon__WEBPACK_IMPORTED_MODULE_1__.default.createFromIconfontCN is not a function

把@ant-design/pro-layout升级到最新版本，如果还报错的话把@ant-design/pro-table也升级到最新版本，我都升级后就可以了
