### ISSUE TITLE
menu数据从后台获取，menu数据里的网页面包屑显示OK，不在menu数据里的页面就没有面包屑

### ISSUE THREAD

**Issue by huagnshiren2014** [ant-design/ant-design-pro-layout#304]
我的menu数据是通过接口获取的，但是还有很大一部分网页配置数据不在menu数据里，如果是menu数据里包含的页面就有面包屑，其他不在menu数据里的页面就没有面包屑，大佬们有处理过这样的问题吗？

![图片](https://user-images.githubusercontent.com/22445536/72677852-9b8a4380-3adb-11ea-9ea8-92c3353524a0.png)

**Comment by chenshuai2144** [comment]
你不想显示的可以用 hideInMenu ,但是数据还是要给的。不然无法计算面包屑

**Comment by summmmer** [comment]
> 你不想显示的可以用 hideInMenu ,但是数据还是要给的。不然无法计算面包屑
请问，菜单数据是从后台获取的，使用了menuDataRender，点击菜单就会折叠，如何解决

**Comment by chenshuai2144** [comment]
每个菜单都配置一个key就好了
