### ISSUE TITLE
🧐[问题]与father-doc不兼容？

### ISSUE THREAD

**Issue by ywy94ywy** [ant-design/ant-design-pro-layout#305]
在安装Pro和father-doc后，md中写jsx就会报错
![image](https://user-images.githubusercontent.com/22499767/72696358-d2f9fe00-3b76-11ea-9ab1-36f33b2f5139.png)

是pro的问题还是father-doc的问题呀？

**Comment by chenshuai2144** [comment]
看起来是你哪里写的有问题，应该是路径为空了。
layout 的官网就是 father-doc 发布的

**Comment by ywy94ywy** [comment]
![image](https://user-images.githubusercontent.com/22499767/72696757-74358400-3b78-11ea-958d-a1e0abb7c3cf.png)
![image](https://user-images.githubusercontent.com/22499767/72696774-7ac3fb80-3b78-11ea-9860-f051af91bb0b.png)
这是我的写法和配置
我不知道哪里写的不对，只要把<code>哪行代码注释了就能运行

**Comment by ywy94ywy** [comment]
![image](https://user-images.githubusercontent.com/22499767/72697675-aac0ce00-3b7b-11ea-9b4e-fea4e89a1864.png)
对了，我这样写也是一样的错误，jsx删掉就好了，好奇怪啊，是我route还是path没写好么

**Comment by ywy94ywy** [comment]
@chenshuai2144 https://codesandbox.io/s/loving-lalande-s2zb7这是复现地址，在端口8000页面上，能不能帮我看下

**Comment by ywy94ywy** [comment]
> @chenshuai2144 https://codesandbox.io/s/loving-lalande-s2zb7 这是复现地址，在端口8000页面上，能不能帮我看下

真的不不兼容，能不能再看下
