### ISSUE TITLE
support Footer

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro-layout#31]
现在是通过下面两种方式提供 footer：

```js
import ProLayout, { DefaultFooter } from '@ant-design/pro-layout';

<DefaultFooter />
<ProLayout
  footerRender={((_, defaultDom) => {
    return defaultDom;
  }
/>
```

### 问题

- 难以修改 footer：
  - https://github.com/ant-design/ant-design-pro/issues/4585
  - https://github.com/ant-design/ant-design-pro/issues/4414
  - https://github.com/ant-design/ant-design-pro/issues/4391
  - https://github.com/ant-design/ant-design-pro/issues/4006
- 内建 footer 不应该有默认内容，这些内容应该放到 pro 里来。

### 方案

直接把 https://github.com/ant-design/ant-design-pro-layout/blob/master/src/GlobalFooter/index.tsx 对外暴露，default 内容移出。

```js
import ProLayout, { Footer } from '@ant-design/pro-layout';

<Footer
  links={[...]}
  copyright={...}
/>

<ProLayout
  footerRender={(() => {
    return (
      <Footer
        links={[...]}
        copyright={...}
      />
    );
  }
/>
```

## 兼容性

会是一个 break change，需要升级 pro-layout 大版本，并补齐相关 API 文档和 changelog。

**Comment by chenshuai2144** [comment]
新版本的footer 已经支持这种用法了。
```
<Footer
  links={[...]}
  copyright={...}
/>
```

需要删除默认的吗？对于用户来说总要写一次  footerRender

**Comment by afc163** [comment]
应该暴露 Footer 而不是 DefaultFooter，不同之处是 Footer 没有默认内容。

**Comment by afc163** [comment]
- DefaultFooter 直接改名为 Footer 好了。
- ProLayout 不写 footerRender 时，直接读 Footer，这个和目前一致。
- ProLayout 在 pro.ant.design 自定义时，不要读 defaultDom（多余的），而是读 Footer，这两个是一致的。

**Comment by chenshuai2144** [comment]
这样就不是一个 breakchange 了。

**Comment by omarc1492** [comment]
How can I modify this to change copyright and links?

> `const footerRender: BasicLayoutProps['footerRender'] = (_, defaultDom) => {`
 `  if (!isAntDesignPro()) {`
 `    return defaultDom;`
 `  }`
 `...`
 `footerRender={footerRender}`
 `...`

Nothing I do to pass props to `footerRender` is working, can you give an example?

**Comment by chenshuai2144** [comment]
https://prolayout.ant.design/footer
这里

**Comment by legitcode267** [comment]
Thanks. I was searching for customizing footer for 3 hours.
I wish if there is more better way than using footerRender.
