### ISSUE TITLE
I could'nt use pro layout this tutorial is not enough

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/ant-design-pro-layout#311]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
Hello, I have been reviewing the documentation for 3 days but I could not install it. 
I have a simple application, I want to use token based authorization in this application. I also want to create menus myself, but I couldn't find any examples.
This documentation, which is very difficult to understand, I just want to use the responsive menu there.

**Comment by chenshuai2144** [comment]
https://prolayout.ant.design/menu#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8A%A0%E8%BD%BD-menu
look here？

**Comment by xXAvoraXx** [comment]
Yeah I found it before you said, I think you should add more detail how to create menu elements in the documentation. Based on this page, I was able to solve the sample. It took me a long time. https://prolayout.ant.design/example -- For example, Menu elements are produced by the MenuDataItem interface. So, I couldn't find any example about it on this page. I had to find this by tampering with the codes. Other problem is how can I use RouteContext, There is only a description about routecontext on this page, there is no example. The other question is how can I implement my token based authorization system ?

In fact, you have prepared a very useful beautiful UI kit. If this becomes widespread in my country, it is used too much.
Thx.

**Comment by chenshuai2144** [comment]
RouteContext can be used to read some data without affecting the UI. Tokens and other functions have nothing to do with the layout, you need to cooperate with your back-end classmates to implement.
