### ISSUE TITLE
How can I implement ant design pro on my .net core web api backend server ?

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/ant-design-pro-layout#312]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
Hello, Finally, I was finally able to install it. Then, After I wrote npm start, It worked. Now, I would like to implement with my backend server, but I couldn't it.

How can I implement ?

**Comment by chenshuai2144** [comment]
https://prolayout.ant.design/menu#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8A%A0%E8%BD%BD-menu
look here？
