### ISSUE TITLE
When route path change, Page title and Menu hover color does not change

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/ant-design-pro-layout#315]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
Why page title and menu hover color does not change while routing change ?

route ---> [react-router-dom]

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
```
<BasicLayout title="Test Layout"
            menuHeaderRender={(logoDom, titleDom) => (
                <Link to="/">
                    {logoDom}
                    {titleDom}
                </Link>
            )}

            menuItemRender={(menuItemProps, defaultDom) => {
                if (menuItemProps.isUrl || menuItemProps.children || !menuItemProps.path) {
                    return defaultDom;
                }

                return <Link to={menuItemProps.path}>{defaultDom}</Link>;
            }}

            route={{
                routes: [
                    {
                        key: 'Home',
                        path: '/',
                        name: 'Home',
                        exact: true
                    },
                    {
                        key: 'page2',
                        name: 'page2',
                        path: '/page2',
                        exact: true
                    }
                ],
            }}

        >
            <Switch>
                <Route exact path="/" component={Page1} />
                <Route exact path="/page2" component={Page2} />
                <Route component={ErrorCom} />
            </Switch>
        </BasicLayout>
```

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![sc](https://user-images.githubusercontent.com/6988989/73174969-2beb0880-411a-11ea-9782-16ca9e925bf7.png)

**Comment by xXAvoraXx** [comment]
up+++

**Comment by xXAvoraXx** [comment]
up+++

**Comment by chenshuai2144** [comment]
Have a minimal reproduction?

**Comment by xXAvoraXx** [comment]
No,I setuped this short example for testing, but I solved the problem.

**Comment by rejochandran** [comment]
Hey @xXAvoraXx  How did you resolve this issue?

**Comment by xXAvoraXx** [comment]
Yes, @rejochandran you should update ant design V4

**Comment by rejochandran** [comment]
I'm already on V4 
<img width="477" alt="Screenshot 2020-03-09 at 8 59 39 PM" src="https://user-images.githubusercontent.com/4696985/76229892-e9543a00-6248-11ea-9bda-ce330a905652.png">

One thing I tried was when I change the current `path` to any other MenuItem, the active class moves to that item. So, I presume the `<ProLayout ... />` component is not getting the path update

any ideas?

**Comment by liu-dongyu** [comment]
antd v4.1.0 still facing this issue

**Comment by xXAvoraXx** [comment]
@liu-dongyu do you use react-router-dom ? If yes, did you get it in the container with prolayout?

**Comment by ylhb** [comment]
> antd v4.1.0 still facing this issue

#422
