### ISSUE TITLE
🧐[问题]如何使content占满剩余全部空间

### ISSUE THREAD

**Issue by johnnylc** [ant-design/ant-design-pro-layout#323]
pro-layout版本： 4.10.13

请问如何实现content占据整个剩余空间？

      <ProLayout
        navTheme='dark'
        layout='sidemenu'
        fixedHeader={true}
        fixSiderbar={true}
        title="监测系统"
        footerRender={false}
      >
      <div style={styles.container}>container</div>
      </ProLayout>

目的是使以上 container的div可以填满空间，请问有什么比较好的实现方式，谢谢

生成的页面结构如下：
<img width="391" alt="layout" src="https://user-images.githubusercontent.com/12717523/74029583-f5e63800-49e7-11ea-8ac6-5fc5ecf1238b.png">

**Comment by arvinxx** [comment]
+1 同样遇到这个问题了 之前版本还正常的

**Comment by exvu** [comment]
原因是新版加入rc-resize-observer 。解决思路：在子元素设置固定高度 比如calc(100vh-60px) 60px除去header的高度

**Comment by exvu** [comment]
@johnnylc 希望能让开发者自行配置resize开关状态，

**Comment by chenshuai2144** [comment]
@exvu  可以直接 contentStyle={{ height : "100vh" }} 就会撑满整个屏幕，但是这样会有别的问题。比如嵌套，高度自适应等。
推荐你设置父节点的的高度为100%，这样layout 就会自动撑满父节点
