### ISSUE TITLE
设置 二级子域不生效？ 🐛[BUG] 

### ISSUE THREAD

**Issue by huyansheng3** [ant-design/ant-design-pro-layout#328]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

![image](https://user-images.githubusercontent.com/11534583/74501680-d4c0a280-4f25-11ea-93b2-d89f2a187c8e.png)

![image](https://user-images.githubusercontent.com/11534583/74501693-e30ebe80-4f25-11ea-9653-8ba8646c0190.png)

顶层path 设置为二级域名， 实际发现在生成的 flatMenus未使用该path，导致路径未匹配上

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by thomaszdxsn** [comment]
你需要的是[这个](https://pro.ant.design/docs/deploy-cn#%E9%83%A8%E7%BD%B2%E5%88%B0%E9%9D%9E%E6%A0%B9%E7%9B%AE%E5%BD%95)吗？

你描述的「二级子域」原意好像不是你说的意思：[二级域名](https://baike.baidu.com/item/%E4%BA%8C%E7%BA%A7%E5%9F%9F%E5%90%8D)
