### ISSUE TITLE
为什么npm i @ant-design/pro-layout --save与github的代码不一致

### ISSUE THREAD

**Issue by tangtanglove** [ant-design/ant-design-pro-layout#33]
为什么npm i @ant-design/pro-layout --save与github的代码不一致

**Comment by tangtanglove** [comment]
![image](https://user-images.githubusercontent.com/2425371/60149837-b1b37800-9808-11e9-824c-dcfc9824bd43.png)
新拉取的代码，设置了<PageHeaderWrapper title={false}> 并没有生效

**Comment by xiaohuoni** [comment]
版本号？

**Comment by tangtanglove** [comment]
"@ant-design/pro-layout": "^4.5.7"
![image](https://user-images.githubusercontent.com/2425371/60167652-13d6a200-9836-11e9-842f-2c9cf5be9d72.png)
但是不生效啊
![image](https://user-images.githubusercontent.com/2425371/60167686-2a7cf900-9836-11e9-83cc-6b4a480682c9.png)

**Comment by tangtanglove** [comment]
我看这里已经修复了。
![image](https://user-images.githubusercontent.com/2425371/60167822-7039c180-9836-11e9-9b5b-29619875765f.png)
为啥拉取的代码，设置不生效呢

**Comment by xiaohuoni** [comment]
@chenshuai2144 是不是还没发包？

**Comment by tangtanglove** [comment]
@chenshuai2144 这个问题纠结了好长时间，大哥，帮忙看看吧。

**Comment by chenshuai2144** [comment]
@tangtanglove  我给你发个 beta 版本吧

**Comment by tangtanglove** [comment]
> @tangtanglove 我给你发个 beta 版本吧

如何拉取

**Comment by tangtanglove** [comment]
@chenshuai2144 我应该如何拉取代码

**Comment by chenshuai2144** [comment]
```
npm i @ant-design/pro-layout@beta
```
这样安装

**Comment by tangtanglove** [comment]
> ```
> npm i @ant-design/pro-layout@beta
> ```
> 
> 这样安装

安装了，但是还是不起作用，而且页面加载过程中还会先跑版，过1秒后版式才能恢复正常。

**Comment by tangtanglove** [comment]
页面先这样
![image](https://user-images.githubusercontent.com/2425371/60173321-096dd580-9841-11e9-8962-a02a18a4f795.png)
然后变正常了
![image](https://user-images.githubusercontent.com/2425371/60173350-1f7b9600-9841-11e9-8a0f-7a5004615473.png)

**Comment by afc163** [comment]
本地 `@ant-design/pro-layout` 版本是 `4.5.8-beta0` 么？

**Comment by tangtanglove** [comment]
是的，确认过

**Comment by chenshuai2144** [comment]
@tangtanglove  闪一下是 umi 的 dll 改动造成的只有在开发环境才会这样

**Comment by tangtanglove** [comment]
但是，我设置   <PageHeaderWrapper title={false}>并没有生效

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-layout/blob/d9f1e6893964fb479c835f688ff3856c9c022468/_test_/pageHeaderWarp.test.tsx#L36

看一下这个测试用例。

**Comment by tangtanglove** [comment]
![image](https://user-images.githubusercontent.com/2425371/60173695-eee82c00-9841-11e9-99f4-0470d7549605.png)

**Comment by tangtanglove** [comment]
![image](https://user-images.githubusercontent.com/2425371/60173948-864d7f00-9842-11e9-9d7a-a4ca89bf8b0b.png)
这种引用方式正确吗？

**Comment by chenshuai2144** [comment]
应该没有问题的，但是你为什么要这么用。。。你上面用的 es 这里用的 lib

**Comment by tangtanglove** [comment]
![image](https://user-images.githubusercontent.com/2425371/60174696-2eb01300-9844-11e9-93fd-44bced16ba78.png)

改成es就啥也没有了

**Comment by tangtanglove** [comment]
我npm update一下页面变成这样了
![image](https://user-images.githubusercontent.com/2425371/60175134-42a84480-9845-11e9-8601-38acfef20bec.png)

**Comment by chenshuai2144** [comment]
`import { PageHeaderWrapper } from @ant-design/pro-layout`
是这样用的

**Comment by tangtanglove** [comment]
![image](https://user-images.githubusercontent.com/2425371/60175260-99158300-9845-11e9-8b6c-faf19dfe2e56.png)

**Comment by billwing** [comment]
我也正在看这个问题，`title={false}`的时候应该要把面包屑的`margin-bottom`设为0。
![image](https://user-images.githubusercontent.com/3411815/60175625-a8490080-9846-11e9-9f2e-8dec0cda1ee6.png)

**Comment by afc163** [comment]
margin 应该要 `breadcrumb + title { margin-top: xxx }` 这样设置，这样灵活很多。

**Comment by tangtanglove** [comment]
@afc163 @chenshuai2144 菜单的a标签的颜色是不是有问题呀

**Comment by tangtanglove** [comment]
我还是先把版本撤回去吧，等您把问题调整完了，我再更新。

**Comment by chenshuai2144** [comment]
@afc163  我在 antd 里面提交一下 pr

**Comment by afc163** [comment]
@tangtanglove 把问题整理一下，不然你一撤我们就可能忘了。

**Comment by tangtanglove** [comment]
![image](https://user-images.githubusercontent.com/2425371/60225733-929fff00-9877-11e9-8791-034c1f8d0e80.png)
beta.1，菜单栏A标签颜色有问题。
