### ISSUE TITLE
路径相似时，高亮的菜单与实际点击菜单不匹配🐛[BUG]

### ISSUE THREAD

**Issue by WanAn0902** [ant-design/ant-design-pro-layout#333]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
两个同级菜单，一个路径是repertoryFw，另一个是repertory，点击repertoryFw时，菜单栏高亮的是repertory的菜单，页面渲染没有问题；
同理，part与partType的菜单也只高亮part的菜单栏

### © 版本信息

- antd 版本: 4.0.0-rc.1
-  "@ant-design/pro-layout": "4.11.0-1",
-   "umi": "2.10.7",
     "umi-plugin-pro-block": "1.3.6",
     "umi-plugin-react": "1.12.8"
- 开发环境 [ mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/38753567/74906221-4186e180-53eb-11ea-8da5-dde99b7816dc.png)

**Comment by zhengqz** [comment]
如何解决？？升级版本吗
