### ISSUE TITLE
🐛[BUG]更新5.0.0后,切换路由,页面高度不会自适应

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design-pro-layout#334]
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
切换路由后,页面高度始终变为最大的页面高度,希望能够自适应, 每个页面都出现滚动条不好看

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
来几个截图吧

页面高度始终变为最大的页面高度 是指什么
