### ISSUE TITLE
🐛[BUG] 从 v4 升到 v5 之后，菜单项的图标不显示了，显示成了图标的名称

### ISSUE THREAD

**Issue by glacjay** [ant-design/ant-design-pro-layout#335]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

![图片](https://user-images.githubusercontent.com/292719/75005930-021fca00-54ab-11ea-89ff-d18ce6ffc984.png)

### © 版本信息

- Ant Design Pro 版本: 3.26.11
- umi 版本: 2.13.3
- 浏览器环境: firefox 73.0.1
- 开发环境: windows 10

**Comment by xXAvoraXx** [comment]
+++++++

**Comment by austin-zy** [comment]
You can try this: [UMI Plugin Icon Config](https://github.com/umijs/umi-plugin-antd-icon-config)

**Comment by xXAvoraXx** [comment]
> You can try this: [UMI Plugin Icon Config](https://github.com/umijs/umi-plugin-antd-icon-config)

I don't use umiJs

**Comment by dmwin72015** [comment]
++++++

**Comment by glacjay** [comment]
@austin-zy 试了，可以

**Comment by xXAvoraXx** [comment]
without umijs ? any solution

**Comment by chenshuai2144** [comment]
看看这个demo
look here demo 
https://prolayout.ant.design/menu#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8A%A0%E8%BD%BD-menu-%E5%B9%B6%E4%B8%94%E4%BD%BF%E7%94%A8-icon

**Comment by xXAvoraXx** [comment]
I solved the problem when I update antdv4

**Comment by chenshuai2144** [comment]
https://pro.ant.design/blog/antd-4.0-cn
