### ISSUE TITLE
🐛[BUG]菜单搜索,结果为空时面包屑消失

### ISSUE THREAD

**Issue by duwei54** [ant-design/ant-design-pro-layout#336]
做搜索菜单的时候,如果结果为空,右侧面包屑会消失
https://prolayout.ant.design/example?anchor=%E6%90%9C%E7%B4%A2%E8%8F%9C%E5%8D%95#%E6%90%9C%E7%B4%A2%E8%8F%9C%E5%8D%95
官方网站可看到效果

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![test](https://user-images.githubusercontent.com/8448880/75020553-f265ad00-54cd-11ea-9e65-fcf6a4786b2e.gif)

**Comment by chenshuai2144** [comment]
因为面包屑是跟着菜单的，我来想个别的办法

**Comment by duwei54** [comment]
@chenshuai2144 谢谢大佬

**Comment by chenshuai2144** [comment]
找不到好办法，只能加 API 了

**Comment by duwei54** [comment]
@chenshuai2144 官方会考虑支持么
