### ISSUE TITLE
安装@ant-design/pro-layout在安装其他插件，启动会报错

### ISSUE THREAD

**Issue by laiwoyaojubaoni** [ant-design/ant-design-pro-layout#340]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
yarn create umi创建项目，接着下载@ant-design/pro-layout，运行项目正常，然后安装sass，重新运行报错了：plugin built-in:plugins/afwebpack-config initialize failed，重新更新安装@ant-design/pro-layout，运行又正常了，接下来安装一个umi-request，重新运行又报错了：plugin built-in:plugins/afwebpack-config initialize failed，  我想在安装@ant-design/pro-layout之后在安装其他插件可能也会出现这个问题

**Comment by chenshuai2144** [comment]
看起来是依赖的问题，@ant-design/pro-layout 是 ui 库，不会操作 node，试着用 tyarn 一下
