### ISSUE TITLE
👑 [需求]增加对低分辨率屏幕 可设置自动收起

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro-layout#345]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
增加对低分辨率屏幕 可设置自动收起（比如 低于1366px 宽屏幕自动可设置收起）

**Comment by chenshuai2144** [comment]
现在是 575，你可以人肉设置 

breakpoint | 触发响应式布局的断点 | Enum { 'xs', 'sm', 'md', 'lg', 'xl', 'xxl' } | lg
-- | -- | -- | --



来实现
