### ISSUE TITLE
👑 [需求] 增加多Tab标签页面快速切换，增加自定义滚动条样式

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro-layout#347]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
 增加多Tab标签页面快速切换，增加自定义滚动条样式
Windows浏览器自带滚动条样式太丑

**Comment by chenshuai2144** [comment]
可以自己用 css hack，默认不会做的太过
