### ISSUE TITLE
想问一下，为什么我采用es6模版字符串拼接生成class的名字时出错

### ISSUE THREAD

**Issue by coderhn** [ant-design/ant-design-pro-layout#350]
这是.less样式文件
![image](https://user-images.githubusercontent.com/47112336/75738909-7d506e00-5d3e-11ea-8bdb-6cde17c75c10.png)
这是在antdpro架子中引用
![image](https://user-images.githubusercontent.com/47112336/75739336-960d5380-5d3f-11ea-8ed4-5103d88a6541.png)

这是在浏览器开发者工具中显示的结果
![image](https://user-images.githubusercontent.com/47112336/75739222-49297d00-5d3f-11ea-8d42-4a3962118154.png)

我不知道为什么会出现这样的问题，因为当我单个使用es6模版字符串拼接class名时不会出现，只有遍历拼接时报错。

**Comment by chenshuai2144** [comment]
styles估计为空了，你为什么要这么写，这些预发估计 babel 处理不了。

**Comment by coderhn** [comment]
> styles是从less注入进去的，你这么写估计babel支持不了。
> 最好不要这样用css，没法维护的
> 
> 如果非要这么写可以用：global。className = { `chanxian${i}`}

谢谢指点迷津，我懂了！
