### ISSUE TITLE
🧐Error with build

### ISSUE THREAD

**Issue by AngeloReppucci** [ant-design/ant-design-pro-layout#355]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

I try to build thw library with "npm run build", but i receive the following error:

`src\PageHeaderWrapper\index.tsx(21,5): error TS2304: Cannot find name 'Omit'.`

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

It fails to build the types with the typescript Omit:

```
export interface PageHeaderWrapperProps
  extends PageHeaderTabConfig,
    Omit<PageHeaderProps, 'title'> {
  title?: React.ReactNode | false;
  content?: React.ReactNode;
  extraContent?: React.ReactNode;
  pageHeaderRender?: (props: PageHeaderWrapperProps) => React.ReactNode;
}
```

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

I've globally installed typescript. The version i use is 3.8.3.

Can someone help me please?

**Comment by chenshuai2144** [comment]
升级一下 ts 的版本，这个是新版本的 ts 提供的支持

**Comment by AngeloReppucci** [comment]
This not worked. I solved changig to `"target": "es6",` in the tsconfig.json file.

**Comment by chenshuai2144** [comment]
😯， good job
