### ISSUE TITLE
希望加个tabs标签页切换👑 [需求]

### ISSUE THREAD

**Issue by hyx0217** [ant-design/ant-design-pro-layout#357]
### 🥰 需求描述
觉得差个tabs标签切换路由，这样操作更友好些。使用headerRender代价有点太大了。
![image](https://user-images.githubusercontent.com/45928314/76064781-5192e980-5fc5-11ea-926b-73b47c616ba6.png)

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/issues/6126
