### ISSUE TITLE
👑 [疑问] prolayout里的面包屑问题

### ISSUE THREAD

**Issue by zhfish** [ant-design/ant-design-pro-layout#358]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
```
itemRender={(route, params, routes, paths) => {
  const first = routes.indexOf(route) === 0
  return first ? (
    <Link to={paths.join('/')}>{route.breadcrumbName}</Link>
  ) : (
    <span>{route.breadcrumbName}</span>
  )
}}
```
还是这段代码，有三个疑问  
1. 为什么设计只有首页才能被Link
2. 为什么Link-to是用paths.join而不是用route.path ？ 尽管首页的paths是空数组，和route.path结果一致
3. route是有 component 的，ts没有定义
 感觉#352 应该是同一个问题
### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
```
        const first = routes.indexOf(route) === 0;
        console.log(route, paths);
        // @ts-ignore
        return first || !!route.component ? (
          <Link to={route.path}>{route.breadcrumbName}</Link>
        ) : (
          <span>{route.breadcrumbName}</span>
        );
```
我的改动如下，首页和有component的路由都可以被Link

**Comment by chenshuai2144** [comment]
>  为什么设计只有首页才能被Link

因为只有首页才有路由，比如 a/b 其实是没有 compents 的

> 为什么Link-to是用paths.join而不是用route.path ？ 

如果使用了相对路径的话 route.path 和 paths.join 是不等于的。

> route是有 component 的，ts没有定义

component  是给框架用的，不推荐给用户使用

**Comment by thomaszdxsn** [comment]
> > 为什么设计只有首页才能被Link
> 
> 因为只有首页才有路由，比如 a/b 其实是没有 compents 的

不好意思，这句话没有看懂。

**Comment by zhfish** [comment]
> > > 为什么设计只有首页才能被Link
> > 
> > 
> > 因为只有首页才有路由，比如 a/b 其实是没有 compents 的
> 
> 不好意思，这句话没有看懂。

其实我也没太看懂  
Home / A / B / C
其中A没有compents，B是列表，C是详情
我的概念里 Home和B都应该是可以Link的
事实我也是这么改了

**Comment by thomaszdxsn** [comment]
按照 [antd: Breadcrumb 组件的示例](https://ant.design/components/breadcrumb-cn/)，应该 last 才应该渲染为 span。这也符合一般的 UI 惯例。

这个应该和 component 是无关的，只要设定了 path 就应该为 Link 标签吧
