### ISSUE TITLE
🐛[BUG]当fixedHeader为ture时，dom出现两个Header

### ISSUE THREAD

**Issue by hzgotb** [ant-design/ant-design-pro-layout#359]
https://github.com/ant-design/ant-design-pro-layout/blob/2c0c42bb1ea3d1689f93c376592e25b147b63391/src/Header.tsx#L79

### © 版本信息

- Ant Design Pro 4
- umi@3
- chrome
- macOS

<img width="391" alt="1" src="https://user-images.githubusercontent.com/50480095/76191787-1a1d7a80-621b-11ea-99b8-32f523c1d980.png">

**Comment by chenshuai2144** [comment]
其中一个是用来占位的，占住顶部的 64px
