### ISSUE TITLE
PageHeaderWrapperProps 没有action

### ISSUE THREAD

**Issue by xoptimal** [ant-design/ant-design-pro-layout#36]
版本  "@ant-design/pro-layout": "^4.5.7",

这里是有的: [umi-blocks](https://github.com/umijs/umi-blocks/blob/master/ant-design-pro/AdvancedProfile/src/index.js)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-blocks/tree/master/ProfileAdvanced
已这个为准，我们迁移到了 ant design 的 pageHeader
