### ISSUE TITLE
👑 [需求]如何实现header在顶部，下面是左右布局的方式？

### ISSUE THREAD

**Issue by codepandy** [ant-design/ant-design-pro-layout#360]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
我想实现上下布局，然后下面又分为左右，左边是menu，右边是内容区域；这个现在支持吗？

下面的方式：
```
    <Layout>
      <Header>Header</Header>
      <Layout>
        <Sider>Sider</Sider>
        <Content>Content</Content>
      </Layout>
    </Layout>
```

**Comment by chenshuai2144** [comment]
https://prolayout.ant.design/example#%E5%8F%A6%E5%A4%96%E4%B8%80%E7%A7%8D%E5%B5%8C%E5%A5%97%E5%B8%83%E5%B1%80
来试试这个
