### ISSUE TITLE
👑 [需求]能否增加一个API，点子菜单的时候，所有展开的菜单不会自动收起来

### ISSUE THREAD

**Issue by aiyuchen** [ant-design/ant-design-pro-layout#361]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
- 问题：目前antd prolayout中，点击左侧任意子菜单，除了当前菜单之外其他菜单都会自动收起来
- 需求：点击左侧任意子菜单，所有展开的菜单不要自动收起来，只有通过手动点下拉，收起图标按钮的时候才会发生收起和展开的动作
- 演示：在antd的menu中有一个“内嵌菜单”示范：https://ant.design/components/menu-cn/#components-menu-demo-inline

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
目前可以默认展开左侧所有菜单，但是点击展开的菜单就自动收起，就造成打开时全部展开的菜单又自动收起了，想再次打开就要一个个点开，希望能够给个Api能够屏蔽菜单自动收起
```
menu: {defaultOpenAll: true}
```

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
现在的菜单，点击任意一个子菜单，只展开当前父级菜单，其他菜单自动收起来
> ![image](https://user-images.githubusercontent.com/578141/76197257-c57ffc80-6226-11ea-92ba-29f895eb28a3.png)

我希望是无论怎么点子菜单，所有菜单都不要自动收起来，在antd的menu中有一个“内嵌菜单”示范：
https://ant.design/components/menu-cn/#components-menu-demo-inline
> ![image](https://user-images.githubusercontent.com/578141/76197312-df214400-6226-11ea-9f20-309ee97574a3.png)

**Comment by chenshuai2144** [comment]
openKeys={false}
https://github.com/ant-design/ant-design-pro-layout/pull/382
