### ISSUE TITLE
🧐[问题]导航菜单项无children时icon与label紧贴

### ISSUE THREAD

**Issue by johnnylc** [ant-design/ant-design-pro-layout#363]
### 🧐 问题描述 
使用pro-layout的自定义菜单形式，渲染中通过Link跳转菜单指定路由，代码如下
menuItemRender = (menuItemProps, defaultDom) => {
    if (menuItemProps.isUrl || menuItemProps.children) {
        return defaultDom
    }
    return <Link to={menuItemProps.path}>{defaultDom}</Link>
}
这段代码在使用pro-layout V4版本时没有问题。升级至V5版本后出现菜单在没有children的情况下，icon与label之间紧贴，margin被覆盖的情况。

![image](https://user-images.githubusercontent.com/12717523/76416294-c2773e80-63d5-11ea-99ef-ff24d679d11c.png)

如果删除Link组件，则渲染正确，但无法跳转路由。
menuItemRender = (menuItemProps, defaultDom) => {
    return defaultDom
}

![image](https://user-images.githubusercontent.com/12717523/76416478-226de500-63d6-11ea-8f18-60ff42a1a374.png)

当前使用pro-layout版本5.0.6，请问该问题如何解决

**Comment by guodong** [comment]
Any solutions?

**Comment by chenshuai2144** [comment]
antd@4.0.3 将会解决
https://github.com/ant-design/ant-design/pull/22217
