### ISSUE TITLE
🧐[问题] pro-layout 怎么调整个性化布局

### ISSUE THREAD

**Issue by hanziyang** [ant-design/ant-design-pro-layout#365]

**Comment by hanziyang** [comment]
大家好，有人调整过这个布局吗？
Ant design 的layout：Header-Content-Footer/Header Sider 2/Header-Sider/Sider/Custom trigger/Responsive/Fixed Header/Fixed Sider
pro-layout 的layout menu mode :sidemenu/ topmenu,
还有其他的布局模式吗？或者可以在哪里更改布局模式

**Comment by chenshuai2144** [comment]
现在只支持这几种布局，我们是中后台的应用Layout ，只提供有限的模式
https://prolayout.ant.design/example
