### ISSUE TITLE
👑 [需求]强烈建议加上tabs选项卡切换路由

### ISSUE THREAD

**Issue by xiayongtian** [ant-design/ant-design-pro-layout#367]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
vue的类似layout的框架都具有这种功能，这是后台管理系统最常见的功能，希望官方加以重视

**Comment by DreamPWJ** [comment]
国内确实很需要

**Comment by chenshuai2144** [comment]
close https://github.com/ant-design/ant-design-pro/issues/6126
