### ISSUE TITLE
breadcrumbRender  issues

### ISSUE THREAD

**Issue by BinaryHao** [ant-design/ant-design-pro-layout#37]
版本："@ant-design/pro-layout": "^4.5.0"
1. breadcrumbRender这个配置主要是用来干吗的，
2. 这个版本怎么添加面包屑

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-layout/blob/master/README.zh-CN.md#pageheaderwrapper

**Comment by mynameismaosheng** [comment]
breadcrumbRender  文档里没有这个 搜不到

**Comment by 389567702** [comment]
通过PageHeader添加的面包屑导航生效，但是跳转地址是hash，config里面已经将history改为brower，此问题如何解决？@chenshuai2144
