### ISSUE TITLE
🐛[BUG]浏览器移动端模式和PC端模式来回切换会导致顶部标题消失

### ISSUE THREAD

**Issue by blackraindrop** [ant-design/ant-design-pro-layout#372]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
![image](https://user-images.githubusercontent.com/1668029/77230235-cf621200-6bcd-11ea-90c6-133fed0f18aa.png)

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
浏览器移动端模式和PC端模式来回切换

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by l745230** [comment]
+1

**Comment by chenshuai2144** [comment]
现在不会了，更新一下依赖
