### ISSUE TITLE
🧐[问题]怎样删除左上角的title？

### ISSUE THREAD

**Issue by fengnex** [ant-design/ant-design-pro-layout#383]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
如题，导航栏已经有了title
没必要加大加粗，多占几行，再显示一遍这个title
如果不想显示title所在的那一行？怎么才能方便的实现？

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
就象下图中的“基础表单”，怎么才能方便地删掉那一行？

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![{HJ6%XJ$ QFRQ(J~{215QCP](https://user-images.githubusercontent.com/26297547/77753930-5d724880-7065-11ea-8d82-b6f739ac09fc.png)

**Comment by fengnex** [comment]
做个记录，这样即可：<PageHeaderWrapper title={false}>

还想请教，下面这些marginmargin该怎么调整：

**Comment by fengnex** [comment]
<img width="775" alt="margin" src="https://user-images.githubusercontent.com/26297547/77773915-3b88be00-7085-11ea-91db-478190d01104.png">

**Comment by chenshuai2144** [comment]
disableContentMargin 有这个隐藏 api，但是建议不要这么做
