### ISSUE TITLE
🧐[问题]请教怎么修改内容区周围的几个样式的margin的值？

### ISSUE THREAD

**Issue by fengnex** [ant-design/ant-design-pro-layout#384]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
请教怎么通过css、less或者修改config.ts、defaultSettings.ts修改上图中的几个margin？谢谢

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![$1H(~85GCA~F4B9~ MQH2(U](https://user-images.githubusercontent.com/26297547/77823195-24ed7000-7134-11ea-978b-fc1bb551b773.png)

**Comment by fengnex** [comment]
整个pro的css样式非常难改。。。。。。

**Comment by chenshuai2144** [comment]
这是我们的设计模式，不希望用户去改动

contentStyle 这可以设置 content 的 style
