### ISSUE TITLE
🐛[BUG]左侧菜单栏的padding样式值通过style写的，而不是class

### ISSUE THREAD

**Issue by fengnex** [ant-design/ant-design-pro-layout#386]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
如下图所示：
ul及其li是左边菜单栏的完整菜单实现，再通过一个div把ul包围起来，这个实现本身没有问题。但是整个菜单区域的padding样式，是通过style="padding: 16px 0px; width: 100%;"这样来限定的，而不是class。建议改成class。

### 🏞 期望结果 [描述你原本期望看到的结果]
通过css的class来控制样式，而不是style字节写。

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/26297547/77843421-b958e080-71cf-11ea-90c4-e013d855a4b3.png)

**Comment by chenshuai2144** [comment]
这是antd的实现，因为这个宽度是可以通过props动态改变的，所以才会这样
