### ISSUE TITLE
🐛[BUG] ProLayout 设置 title 后无效

### ISSUE THREAD

**Issue by xiaopanghhh** [ant-design/ant-design-pro-layout#392]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
![image](https://user-images.githubusercontent.com/24469601/78123613-01cb0500-7441-11ea-9f6e-4e34c00ca662.png)
代码是这样的。

显示为
![image](https://user-images.githubusercontent.com/24469601/78123668-1a3b1f80-7441-11ea-8a00-f9e0294ae573.png)

![image](https://user-images.githubusercontent.com/24469601/78123693-23c48780-7441-11ea-8435-716c51c6dc2a.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 3.0.16
- 浏览器环境  Chrome
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
估计你的代码下面有个 {...setting} 把titile 覆盖了

**Comment by xiaopanghhh** [comment]
确实是这样的，非常感谢。
