### ISSUE TITLE
👑 [需求] 双导航布局

### ISSUE THREAD

**Issue by playedclass** [ant-design/ant-design-pro-layout#397]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
这个组件没有封装的时候，自己实现过双导航，一级目录在上面，其他级在侧边栏，现在单独抽成组件了，有没有好的扩展方式，还是建议自己fork，二次开发

**Comment by hhking** [comment]
我 fork 实现过双导航布局 [header-sider-layout](https://github.com/hhking/header-sider-layout)

现在官方已经支持嵌套布局可以实现双导航，推荐使用 [嵌套布局](https://prolayout.ant.design/example#%E5%8F%A6%E5%A4%96%E4%B8%80%E7%A7%8D%E5%B5%8C%E5%A5%97%E5%B8%83%E5%B1%80)
