### ISSUE TITLE
🐛[BUG]document.title切换菜单就为空

### ISSUE THREAD

**Issue by playedclass** [ant-design/ant-design-pro-layout#400]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
没更新到5.0.9之前，点两次或者母版页那种会有问题，更新到最新，只要切换菜单，就为空

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] 4.1.0
- umi 版本 umi3
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS] macos

**Comment by playedclass** [comment]
![image](https://user-images.githubusercontent.com/3337266/78308081-0e9f4400-757a-11ea-84c9-1e0500eb9dbe.png)
title是可以正常设置的，但后面会执行到这里，再向下就被清空了

**Comment by chenshuai2144** [comment]
在这里修复了https://github.com/ant-design/ant-design-pro-layout/pull/391
已经发布了

**Comment by playedclass** [comment]
> 在这里修复了#391
> 已经发布了

我断点调试过 src/utils/hooks.ts 这个，那个错误是在这个文件执行后发生的

**Comment by playedclass** [comment]
现在ant-design-pro项目master分支用最新版本的pro-layout，切换菜单也是这问题

**Comment by kaoding** [comment]
https://github.com/ant-design/ant-design-pro-layout/issues/401 
应该是这类似问题
