### ISSUE TITLE
🐛[BUG]设置fixedHeader之后，通过左侧菜单栏打开页面显示问题

### ISSUE THREAD

**Issue by gb-6k-house** [ant-design/ant-design-pro-layout#402]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
1、设置fixedHeader=true，fixSiderbar=true
2、通过左侧菜单栏打开一个页面，将页面滑动到底部。
3、通过左侧菜单栏打开另外一个页面，新打开的页面没有从开始显示，滑动条还是上一个页面的位置。

### 🏞 期望结果 [描述你原本期望看到的结果]
期望第三步打开的新页面从开始页面开始进行显示，滚动条应新页面在顶部。
### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.9]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by gb-6k-house** [comment]
4.11.0版本存在同样的问题

**Comment by chenshuai2144** [comment]
期望第三步打开的新页面从开始页面开始进行显示，滚动条应新页面在顶部。

这个你可以通过 onPageChange 来自己实现一下，layout 不会管你的滚动条的
