### ISSUE TITLE
[BUG]希望增加一个 prefix 的属性

### ISSUE THREAD

**Issue by GoDotDotDot** [ant-design/ant-design-pro-layout#403]
发现 pro 的 less 样式表里面有取 ant design 的 prefix，但是在 pro 的代码中样式却是写死的，如 `ant-design-pro-layout`。这对于有修改 ant design 样式前缀的需求项目，是个麻烦事。

**Comment by chenshuai2144** [comment]
已经尽量使用了 antd 的 less 变量，我来排查一下，或者你方便给一个问题列表吗

**Comment by GoDotDotDot** [comment]
less 文件中确实尽量使用了，但是组件中有的还是写死的。问题列表的话我建议直接搜索 ant-pro、ant 之类的字眼就可以看到了。

**Comment by chenshuai2144** [comment]
v6 支持了
