### ISSUE TITLE
🧐[问题] sider collapsed 之后 80 px 太宽了，这个属性在哪里调？

### ISSUE THREAD

**Issue by tucke** [ant-design/ant-design-pro-layout#404]

**Comment by chenshuai2144** [comment]
这个不支持的，是 antd 中写死的

**Comment by tucke** [comment]
SiderMenu 组件中使用的 Sider 组件增加 collapsedWidth 属性（默认为80，为 0 会有特殊效果），然后 BasicLayout 和 Header 中写死80的地方改成使用 collapsedWidth，项目配置中 theme 配合 menu-collapsed-width 属性就可以啦！

**Comment by tucke** [comment]
现在很多左边折叠的宽度还是56px或者64px，80确实太宽了，希望作者加入下这个改动，拜托啦！@chenshuai2144

**Comment by chenshuai2144** [comment]
下个版本

**Comment by tucke** [comment]
太好了，点赞

**Comment by chenshuai2144** [comment]
打错字了，暂时应该不会支持的，antd 没有相关计划

**Comment by tucke** [comment]
难受，那只能拷贝一份 ant-design-pro-layout 代码到项目中了！
