### ISSUE TITLE
🧐为什么要判断routes的length为1不展示面包屑

### ISSUE THREAD

**Issue by poyiding** [ant-design/ant-design-pro-layout#405]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
为啥要判断routes的length为1不展示面包屑？可是 antd 的 PageHeader 如果 routes的length为1 还是会展示面包屑的。
应该和PageHeader保持一致吧。
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
https://github.com/ant-design/ant-design-pro-layout/blob/master/src/utils/getBreadcrumbProps.tsx#L173

**Comment by chenshuai2144** [comment]
PageHeader 是最近关掉的，因为呼声太高
pro 这里是考虑如果面包屑只有一级是没必要展示的。
