### ISSUE TITLE
create-react-app中使用ant-pro-layout 添加路由后 点击路由没有加载组件

### ISSUE THREAD

**Issue by SoleilQ** [ant-design/ant-design-pro-layout#406]

**Comment by chenshuai2144** [comment]
来个重现的 demo

**Comment by SoleilQ** [comment]
> 来个重现的 demo
这个问题已经被解决 现在有一个新的问题 
我用了react-router-config 中的renderRoutes方法来渲染menu 用HashRouter包裹
奇怪的是menu缺少了selected的样式 drak主题下 是蓝色的背景
```javascript
<HashRouter>
  <BasicLayout>
     { renderRoutes(defaultMenus) }
  </BasicLayout>
</HashRouter>
```
![image](https://user-images.githubusercontent.com/20468482/78877241-1fbce900-7a83-11ea-87d0-75561bb53d65.png)

但是我用BrowserRouter来包裹 BasicLayout 就没有这个问题
不知道这个原因是什么

**Comment by klzen** [comment]
@SoleilQ 请问,你是如何解决这个问题的?我现在也碰到了Route最后的一个Component无法载入的问题.我使用的是ant-design-pro模板,想参考一下.

**Comment by klzen** [comment]
@SoleilQ 已经解决.我的问题出在,在一级目录的时候,没有指定path,因为没有指定path,所以就没找到组件.添加path后,就解决问题了.
