### ISSUE TITLE
🐛[BUG]https://codesandbox.io/ 例子缺少文件和package.json配置不对

### ISSUE THREAD

**Issue by fangaofeng** [ant-design/ant-design-pro-layout#410]
package.json

Error
Could not fetch dependencies, please try again in a couple seconds: Invalid package name ".": name cannot start with a period
运行例子
https://codesandbox.io/s/kqhgb?module=/demo.tsx&file=/package.json

**Comment by chenshuai2144** [comment]
已经修改了
