### ISSUE TITLE
🧐[需求]侧边菜单栏是否可自定义鼠标移入和鼠标点击事件？

### ISSUE THREAD

**Issue by Emp2612** [ant-design/ant-design-pro-layout#411]
### 🧐 问题描述 
如题，遇到需求需要在侧边路由菜单栏监听鼠标移入事件对当前路由下功能做模态框内容展示，不知道是否有该自定义事件？文档内未找到明确做法，感谢！

**Comment by chenshuai2144** [comment]
menuProps 可以根据 antd 的 menu 做一下
