### ISSUE TITLE
🧐ProLayout collapsed 默认是false而不是ReadMe 的 true

### ISSUE THREAD

**Issue by SherlockHomer** [ant-design/ant-design-pro-layout#413]
### 🧐 问题描述
collapsed 已收缩，如果默认是true ， 应该默认收缩
### 💻 示例代码
`<ProLayout />` 收缩无效
`<ProLayout collapsed />` 收缩无效
### 🚑 其他信息 
![image](https://user-images.githubusercontent.com/8587619/79089288-365f8a80-7d78-11ea-9c66-6012b5082823.png)

**Comment by SherlockHomer** [comment]
看到  #230 
breakpoint 设置为 false 后有效；
应当直接修改文档备注，以免让人困惑，费时

**Comment by chenshuai2144** [comment]
默认是有 breakpoint 的，根据屏幕会自动计算一下。
