### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by jockey100332** [ant-design/ant-design-pro-layout#415]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
返回给menuDataRender 的数据中，我没有添加chiildren 属性，在菜单栏只显示的数组中的第一个，我查看menuItem的 reactnode也是怪异的，我重写了方法，并定义上 为[]解决

希望在menuItemRender方法中可以判断一下传入数据的chiildren是否存在

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
fixed
