### ISSUE TITLE
🧐[问题]当content内容自适应时，可能导致滚动条闪烁

### ISSUE THREAD

**Issue by Liu-Ya** [ant-design/ant-design-pro-layout#416]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
当content中有不定宽高的元素（如<img />）自适应时，可能导致滚动条闪烁，不知道这算不算问题😂
### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![render](https://user-images.githubusercontent.com/23520283/79289880-291fd880-7efd-11ea-960b-65fc94e8fcee.gif)
![render1](https://user-images.githubusercontent.com/23520283/79289997-7c922680-7efd-11ea-8311-30d2e529829c.gif)

**Comment by chenshuai2144** [comment]
算，是严重的 bug，你可以先定住高度来解决问题

**Comment by chenshuai2144** [comment]
算，是严重的 bug，你可以先定住高度来解决问题

**Comment by chenshuai2144** [comment]
给你加了个 api
https://github.com/ant-design/ant-design-pro-layout/pull/505
