### ISSUE TITLE
👑 [需求] 支持根据 prefers-color-scheme 自动切换主题

### ISSUE THREAD

**Issue by jinliming2** [ant-design/ant-design-pro-layout#418]
### 🥰 需求描述
新版浏览器开始支持 prefers-color-scheme 属性，可以根据操作系统设置的主题风格（light 或 dark）来切换浅色模式或深色模式，在系统中配置了根据时间自动切换 dark 模式可以让适配的网页也跟着自动切换为 dark 模式。
如果可以的话，支持使用 CSS 的 `@media (prefers-color-scheme: light)`、`@media (prefers-color-scheme: dark)` 来自动切换深色主题。

**Comment by chenshuai2144** [comment]
需要 antd 支持才行的
