### ISSUE TITLE
🧐[问题]hideInMenu无效

### ISSUE THREAD

**Issue by rilaohn** [ant-design/ant-design-pro-layout#420]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
直接通过umi3搭建的项目，并配置了layout，随便写个路由，给路由添加一个hideInMenu发现无法影藏，是不是需要其他配置

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
  layout: {},
  routes: [
    { path: '/', component: '@/pages/index', name: 'home' },
    { path: '/index', component: '@/pages/index', name: 'index', hideInMenu: true },
  ],

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
第二个路由还是显示了

**Comment by fangaofeng** [comment]
如果没有menu无法显示面包屑了

**Comment by icksky** [comment]
小白鼠不好当啊...还是先用旧版的吧

**Comment by cononota** [comment]
umi3使用了@umijs/plugin-layout简化配置，只支持hideChildren，另外pro-layout默认path和name不为空的才会生成菜单项，可以通过不设置name来去除菜单项。不过两个方案都有面包屑显示的问题。
插件文档链接
[https://umijs.org/zh-CN/plugins/plugin-layout](url)

**Comment by chenshuai2144** [comment]
修复了，是个 bug 导致的
