### ISSUE TITLE
🧐layout为topmenu时menuRender貌似不起作用，连false也不起作用

### ISSUE THREAD

**Issue by ZhangTaibin** [ant-design/ant-design-pro-layout#425]
### 💻 示例代码 
本来是想在官方sandbox的例子上改的，可是貌似报依赖报错。于是下载了代码本地跑的例子：
1、sidemenu模式
![image](https://user-images.githubusercontent.com/34602394/79985409-21ec6200-84dd-11ea-80b3-ccb3ea7ae5ee.png)
![image](https://user-images.githubusercontent.com/34602394/79985657-87d8e980-84dd-11ea-97a4-6d062fe44d0c.png)

2、topmenu模式
![image](https://user-images.githubusercontent.com/34602394/79985719-9e7f4080-84dd-11ea-859d-5772771409b1.png)
![image](https://user-images.githubusercontent.com/34602394/79985746-a6d77b80-84dd-11ea-86de-ce0f49c0ac9a.png)

### 🚑 原先我预想自定义一个类似阿里云首页的菜单例子。
![image](https://user-images.githubusercontent.com/34602394/79985966-edc57100-84dd-11ea-9299-9d4302950df1.png)

**Comment by chenshuai2144** [comment]
有兴趣来来个 pr 吗？
或者直接使用 headerRedner
