### ISSUE TITLE
🐛[BUG]menuDataRender,postMenuData重复执行

### ISSUE THREAD

**Issue by gehaijun** [ant-design/ant-design-pro-layout#429]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
menuDataRender,postMenuData重复执行
第一次进入应用 menuDataRender执行2次，postMenuData执行5次
![image](https://user-images.githubusercontent.com/35563401/80175914-959b8580-8629-11ea-9a7a-0d053f6228d8.png)
每次切换页面时，menuDataRender执行1次，postMenuData执行3次
![image](https://user-images.githubusercontent.com/35563401/80175996-db584e00-8629-11ea-929a-5a88b8df7ff3.png)

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
```
git clone https://github.com/ant-design/ant-design-pro-layout.git
npm install
cd example  
npm install
npm run dev
```
### 🏞 期望结果 [描述你原本期望看到的结果]
在菜单数据不变时，menuDataRender，与postMenuData只执行一次
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
![image](https://user-images.githubusercontent.com/35563401/80176078-0e024680-862a-11ea-9c92-ffe30361523f.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 2.13.13
- 浏览器环境 chrome
- 开发环境 [e.g. win10 x64]

**Comment by chenshuai2144** [comment]
如果配置了 menuDataRender 每次 render 都会执行，因为无法判断function 需要执行
