### ISSUE TITLE
🐛[BUG]添加 base 或者开启 hash 时菜单不能正常选中

### ISSUE THREAD

**Issue by LeeHarlan** [ant-design/ant-design-pro-layout#430]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

- 添加 base 参数点击菜单路由跳转，菜单不会高亮选中
- hash 模式下菜单也不会高亮选中

### 🏞 期望结果 [描述你原本期望看到的结果]

正常高亮选中菜单

### © 版本信息

- Ant Design Pro 版本:  5.0.10
- umi 版本: 3.1.0
- 浏览器环境: chrome
- 开发环境: win10

**Comment by vdfor** [comment]
传入location即可

**Comment by lichangchao15442** [comment]
> 传入location即可

我也遇到了同样的问题，在哪里传入location呢？可以说具体点吗？

**Comment by vdfor** [comment]
> > 传入location即可
> 
> 我也遇到了同样的问题，在哪里传入location呢？可以说具体点吗

```jsx
import BasicLayout from '@ant-design/pro-layout';
const Layout = ({location,children,...restProps}) => (
<BasicLayout location={location}>
{children}
</BasicLayout>
)
```
大概是这样

**Comment by lichangchao15442** [comment]
> > > 传入location即可
> > 
> > 
> > 我也遇到了同样的问题，在哪里传入location呢？可以说具体点吗
> 
> ```js-jsx
> import BasicLayout from '@ant-design/pro-layout';
> const Layout = ({location,children,...restProps}) => (
> <BasicLayout location={location}>
> {children}
> </BasicLayout>
> )
> ```
> 
> 大概是这样

感谢您的回答，但是，我是使用的umi/plugin-layout,又应该在哪里配置呢？
