### ISSUE TITLE
🐛[BUG]最近由于修复右侧内容宽度，而修改了页面结构，强制 content 内容被 GridContent 包裹的问题

### ISSUE THREAD

**Issue by coldice945** [ant-design/ant-design-pro-layout#433]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
最近由于 ”Fix the wrong calculation of the content width on the right“ 这个问题，修改了 WrapContent 结构，增加了 <GridContent> 组件。使得 Content 内容强制被 GridContent 包裹。使得内容的宽度被 GridContent 限定。

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
设置，导航模式 layout 为 topmenu，内容区域宽度 contentWidth 设定为 Fixed，无论是自己写 div 或者使用 PageHeaderWrapper，都不能使宽度展开成浏览器宽度。

<img width="1745" alt="目前效果" src="https://user-images.githubusercontent.com/18394852/80340022-6d628f80-8892-11ea-81d1-371439ad4c1c.png">

<img width="1878" alt="之前的效果" src="https://user-images.githubusercontent.com/18394852/80340994-38573c80-8894-11ea-8f72-8aa9eccc61d0.png">

### 🏞 期望结果 [描述你原本期望看到的结果]

应该和之前的效果类似，是可以让 content 内容，扩充到屏幕宽度的，而不是被定死。

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

[目前的效果](https://preview.pro.ant.design/dashboard/workplace?layout=topmenu&contentWidth=Fixed
)
[之前的效果](https://v2-preview-ant-design-pro.netlify.app/dashboard/workplace?layout=topmenu&contentWidth=Fixed)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by hhking** [comment]
确实有这个问题。这个也导致嵌套布局，被嵌套的会被外层的布局限制住

**Comment by chenshuai2144** [comment]
@hhking  可以强制设置高度，过一段时间过去掉这个逻辑，要退出历史舞台了

**Comment by unliu** [comment]
补充情况：这是 5.0.10 版本引入的问题，我这边项目中由于需要使用上下布局，只好暂时降级为 5.0.9 版本。
没有理解 @chenshuai2144 提到的「强制设置高度」含义哈。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-layout/issues/416

看看这个 应该改能解决部分问题
