### ISSUE TITLE
PageHeaderWrapper组件 如何不要页头只要面包屑部分 还有项目详情页面如何添加 

### ISSUE THREAD

**Issue by xuchao321** [ant-design/ant-design-pro-layout#435]
![image](https://user-images.githubusercontent.com/28084523/80435918-7144ef00-8930-11ea-8466-5d5297c090e3.png)

**Comment by xiaopanghhh** [comment]
title  设置为  false 就不显示页头了。
<PageHeaderWrapper title = {false}/>
也可以自定义页头，如下。
<PageHeaderWrapper title={categoryInfo?.name}

**Comment by xuchao321** [comment]
![image](https://user-images.githubusercontent.com/28084523/81141062-0a61ae80-8f9e-11ea-9cef-22fbe5c991d5.png)
title 设置false  一级面包屑没了

**Comment by xuchao321** [comment]
如何设置面包屑第一个点击没效果

**Comment by chenshuai2144** [comment]
```
  breadcrumbRender={(routers = []) => [
        {
          path: '/',
          breadcrumbName: formatMessage({ id: 'menu.home' }),
        },
        ...routers,
      ]}
```
