### ISSUE TITLE
🧐[问题] 导航栏收起状态，怎么改样式

### ISSUE THREAD

**Issue by codexu** [ant-design/ant-design-pro-layout#436]
### 🧐 导航栏收起状态，怎么改样式
无法覆盖样式，也没有找到设置样式的接口

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![截屏2020-04-2911 13 24](https://user-images.githubusercontent.com/15899990/80557903-04525780-8a0b-11ea-91c2-1556707d65e0.png)
<img width="294" alt="截屏2020-04-2911 13 40" src="https://user-images.githubusercontent.com/15899990/80557905-06b4b180-8a0b-11ea-8d9f-bc70cb435261.png">

**Comment by chenshuai2144** [comment]
这个需要看 antd 的 api，基于 antd 的 menu 实现的。

找到需要的 api 后可以通过 menuProps 传入
