### ISSUE TITLE
🐛[BUG] 通过 history 进行路由导航时，选中的菜单项会跟随路由同步变化

### ISSUE THREAD

**Issue by ILiuDongHui** [ant-design/ant-design-pro-layout#437]
### 🐛 通过 history 进行路由导航时，选中的菜单项会跟随路由同步变化
假设有如下三个路由和菜单：  
/welcome  
/dash/analysis（二级菜单）  
/dash/monitor（二级菜单）

假如从 /dash/analysis 调用 history.push('/dash/monitor') ，这时，/dash 的子菜单会被展开，并且选中 /monitor 

### 期望
不希望通过 history 导航时，弹出子菜单或者选中菜单项

**Comment by chenshuai2144** [comment]
砍掉这个功能 layout 就没有意义了，
你可以通过 openkeys 来手动控制
