### ISSUE TITLE
🐛[BUG]自定义菜单只有一个时，菜单不显示

### ISSUE THREAD

**Issue by effapp** [ant-design/ant-design-pro-layout#439]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
自定义菜单只有一个菜单时，菜单不显示
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 2.13
- 浏览器环境 chrome
- 开发环境 [win10]

**Comment by chenshuai2144** [comment]
show your code
