### ISSUE TITLE
vscode 中 BasicLayoutProps 类型报错

### ISSUE THREAD

**Issue by yugongjie** [ant-design/ant-design-pro-layout#44]
接口“BasicLayoutProps”不能同时扩展类型“BasicLayoutProps”和“Pick<ConnectProps<{}>, "history" | "match" | "staticContext" | "computedMatch" | "route" | "dispatch">”。
  “BasicLayoutProps”和“Pick<ConnectProps<{}>, "history" | "match" | "staticContext" | "computedMatch" | "route" | "dispatch">”类型的命名属性“computedMatch”不完全相同

![image](https://user-images.githubusercontent.com/20796357/60424651-6099ee80-9c23-11e9-9f54-42cc0d7f26e5.png)

**Comment by chenshuai2144** [comment]
看pro中是怎么处理的。
