### ISSUE TITLE
🐛[BUG]运行源码，father build直接报Error: TypeScript: Compilation failed

### ISSUE THREAD

**Issue by confidence68** [ant-design/ant-design-pro-layout#442]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
我clone下来的源码，直接运行npm run build 汇报如下错误

`src/SettingDrawer/index.tsx(299,9): error TS2345: Argument of type 'string | string[] | ParsedQs | ParsedQs[]' is not assignable to parameter of type 'string | undefined'.`

`TypeScript: 1 semantic error
TypeScript: emit succeeded (with errors)
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: TypeScript: Compilation failed
    at Output.mightFinish (/Users/mac/Documents/ant-design-pro-layout/node_modules/gulp-typescript/release/output.js:130:43)
    at applySourceMap.then.appliedSourceMap (/Users/mac/Documents/react/ant-design-pro-layout/node_modules/gulp-typescript/release/output.js:65:22)
Emitted 'error' event at:
    at Duplexify._destroy (/Users/mac/Documents/react/ant-design-pro-layout/node_modules/duplexify/index.js:191:15)
    at /Users/mac/Documents/react/ant-design-pro-layout/node_modules/duplexify/index.js:182:10
    at process._tickCallback (internal/process/next_tick.js:61:11)`

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
1、npm  i

2、npm run build

### 🏞 期望结果 [描述你原本期望看到的结果]

如何能修复此问题？

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

npm run build

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS] node v10.15.1

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![Snip20200506_1](https://user-images.githubusercontent.com/3736355/81191908-25f3a600-8fec-11ea-9b52-1a78089c523c.png)
![Snip20200506_2](https://user-images.githubusercontent.com/3736355/81191914-29872d00-8fec-11ea-9a8e-e4802e0af966.png)

**Comment by confidence68** [comment]
已经解决了！

**Comment by yg0x01** [comment]
@confidence68 请问怎么解决的?

**Comment by chenshuai2144** [comment]
类型错误
更新一下就好
