### ISSUE TITLE
title 默认值

### ISSUE THREAD

**Issue by jockey100332** [ant-design/ant-design-pro-layout#443]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
在刷新的时候，初始化会显示一下ant desgin pro ，才会更新到自己修改指定的 title 内容
### 🏞 期望结果 [描述你原本期望看到的结果]
请将默认值置空
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by kaoding** [comment]
修改 document.ejs 文件里的 <title>你的title</title>

**Comment by mancoxu** [comment]
> 修改 document.ejs 文件里的 <title>你的title</title>

![image](https://user-images.githubusercontent.com/15724205/82552742-48152880-9b95-11ea-88b3-42a3792a0a00.png)

写了 `location` 后会闪一下自己的，然后显示成菜单里的 name（已配置 document.ejs ）

**Comment by jockey100332** [comment]
> 修改 document.ejs 文件里的 <title>你的title</title>

🙏感谢
