### ISSUE TITLE
🧐[问题]不能重新创建基本示例

### ISSUE THREAD

**Issue by daniellowtw** [ant-design/ant-design-pro-layout#445]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

我想跟据https://prolayout.ant.design/ 的指示重新创建示例，但是我不清楚哪里弄错了。希望有人可以指点。

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

https://codesandbox.io/s/dumi-demo-fjf6f

package.json
```
  "dependencies": {
    "react": "^16.8.0",
    "@ant-design/pro-layout": "latest",
    "@babel/runtime": "^7.6.3",
    "react-dom": "^16.8.0",
    "antd": "4.2.0"
  },
```

demo.tsx
```tsx
import React from "react";
import ProLayout, { PageHeaderWrapper } from "@ant-design/pro-layout";

export default () => (
  <div
    style={{
      height: 400,
      overflow: "auto"
    }}
  >
    <ProLayout
      location={{
        pathname: "/articles/new"
      }}
      route={{
        routes: []
      }}
      menu={{ defaultOpenAll: true }}
    >
      <PageHeaderWrapper content="欢迎使用">
        <div>Hello World</div>
      </PageHeaderWrapper>
    </ProLayout>
  </div>
);
```

另外加了以下的资源
https://cdnjs.cloudflare.com/ajax/libs/antd/4.2.0/antd.min.js
https://cdnjs.cloudflare.com/ajax/libs/antd/4.2.0/antd.compact.css

以上创建的是

![image](https://user-images.githubusercontent.com/3450274/81401943-504a7e00-9128-11ea-962f-7b84f4ea008b.png)

但是我想要看到的是

![image](https://user-images.githubusercontent.com/3450274/81402036-8a1b8480-9128-11ea-9ea4-f4325b95c106.png)

**Comment by chenshuai2144** [comment]
需要引入 

import  "/@ant-design/pro-layout@6.2.2/dist/prolayout.min.css";
