### ISSUE TITLE
👑 [需求] Header中可以配置左边导航按钮旁边的title。

### ISSUE THREAD

**Issue by ZilinZhou1995** [ant-design/ant-design-pro-layout#448]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]

Header中可以配置左边导航按钮旁边的title。

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/10460047/81524190-3bcfd680-931e-11ea-8f90-27557b9efb3f.png)

**Comment by chenshuai2144** [comment]
collapsedButtonRender 可以 hack 一下，这个按钮 6.0 更换掉
