### ISSUE TITLE
🧐[问题] v5.0.11 路由配置里icon自动继承了吗？

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro-layout#450]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

v5.0.11 路由配置里icon自动继承了吗？
还是保持以前一样的好，不要继承 icon

![image](https://user-images.githubusercontent.com/18542211/81525248-a74d8e80-9386-11ea-8930-6c69337ec32b.png)

**Comment by Michaelooo** [comment]
v 5.0.12 同样遇到了这个问题

**Comment by zhangyu1818** [comment]
我也是这样，mac下正常，linux和windows都有这问题，不知道怎么解决
