### ISSUE TITLE
🐛[BUG]Check the render method of `ResizeObserver`.

### ISSUE THREAD

**Issue by zlyyyy** [ant-design/ant-design-pro-layout#452]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
layout: 'topmenu'报这个错
![image](https://user-images.githubusercontent.com/22760932/81541743-2dc59880-93a6-11ea-8c24-424f2072b0cb.png)
版本5.0.10

**Comment by wxx2258** [comment]
同样错误，求解

**Comment by jockey100332** [comment]
我的也是，解决了  吗

**Comment by zlyyyy** [comment]
> 我的也是，解决了吗

并没有，我版本后退了

**Comment by jockey100332** [comment]
> > 我的也是，解决了吗
> 
> 并没有，我版本后退了

ant pro v5 升级之后就没有这个问题，降低版本也会没了这个警告

**Comment by chenshuai2144** [comment]
fixed
