### ISSUE TITLE
🐛[BUG] 修改 BasicLayout 中的 DefaultFooter 参数不生效

### ISSUE THREAD

**Issue by mago960806** [ant-design/ant-design-pro-layout#456]
### © 版本信息

- Ant Design Pro 版本: master
- umi 版本 v3
- 浏览器环境 Chrome latest
- 开发环境 mac OS 10.14

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/18606660/81649046-485d4780-9462-11ea-9e10-11abde1e8297.png)
![image](https://user-images.githubusercontent.com/18606660/81649251-9a9e6880-9462-11ea-866d-8cc7f365481a.png)

**Comment by chenshuai2144** [comment]
来个重现网址吧，试了试试可以的
