### ISSUE TITLE
🐛[BUG] 5.0.12 版本PageHeaderWrapper 面包屑不显示

### ISSUE THREAD

**Issue by aikin-vip** [ant-design/ant-design-pro-layout#457]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
umi3 中 启用 plugin-layout插件 包裹 PageHeaderWrapper 顶部无法看到面包屑 
### 🏞 期望结果 [描述你原本期望看到的结果]

pageHeaderWrapper 中可以看到动态的面包屑

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
***src/app.tsx 中
```
export const layout = {
  childrenRender: (children: any) => {
      return <PageHeaderWrapper title={false}>{children}</PageHeaderWrapper>
  }
}
```
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] 4.2.0
- umi 版本 3.1.4
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS] macos

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
@ant-design/pro-layout  版本为 5.0.10 时
![image](https://user-images.githubusercontent.com/64122272/81721438-70749700-94b2-11ea-8761-e266db411a43.png)

@ant-design/pro-layout  版本为 5.0.12 时
![image](https://user-images.githubusercontent.com/64122272/81721663-d06b3d80-94b2-11ea-8b61-6bec5f7c3bfa.png)

只切换prolayout 的版本就会出现这个问题

**Comment by maidiwen** [comment]
同样遇到这个问题。
退回版本为pro-layout@5.0.10、@umijs/plugin-layout@0.10.0，问题暂时解决。

**Comment by chenshuai2144** [comment]
fixed

**Comment by tommyspot** [comment]
Hi @chenshuai2144 ,

I updated to version 5.0.15 but this issue still appears. Any configuration?

**Comment by chenshuai2144** [comment]
you can try git clean -dfx && npm  i

**Comment by tommyspot** [comment]
Hi @chenshuai2144 ,

I used `yarn` instead of `npm`. For yarn, it doesn't work currently.

**Comment by chenshuai2144** [comment]
mybe  disableContentMargin ?
```
export const layout = ({
  initialState,
}: {
  initialState: { settings?: LayoutSettings };
}): BasicLayoutProps => {
  return {
    rightContentRender: () => <RightContent />,
    disableContentMargin: false,
    footerRender: () => <Footer />,
    menuHeaderRender: undefined,
    ...initialState?.settings,
  };
};
```

**Comment by tommyspot** [comment]
<img width="408" alt="Screen Shot 2020-06-08 at 05 50 52" src="https://user-images.githubusercontent.com/7645519/83981872-15687f80-a94c-11ea-9a61-66e44eb7c9a3.png">

It still doesn't work with `yarn` @chenshuai2144 .
