### ISSUE TITLE
侧边导航收起宽度自定义， collapsedWidth

### ISSUE THREAD

**Issue by lefter** [ant-design/ant-design-pro-layout#46]
现在是80写死了，

collapsedWidth | 收缩宽度，设置为 0 会出现特殊 trigger | number | 80

**Comment by chenshuai2144** [comment]
你需要完全收起？

**Comment by lefter** [comment]
> 你需要完全收起？
不是，觉得80太宽了，改成其他值。

**Comment by chenshuai2144** [comment]
这个需要用css自己调整了，应为还有icon和动画这些的

**Comment by leiliangGit** [comment]
css自己如何调整呢，好像直接在ProLayout组件上写className和style都不行

**Comment by mozillo** [comment]
同样的问题, customize style.

**Comment by Lumend** [comment]
collapsedWidth 在哪里设置？

**Comment by chenshuai2144** [comment]
支持了

**Comment by HangIn-There** [comment]
如何支持的？哪个版本？@ant-design/pro-layout": "^4.10.0  这个版本还是没办法设置collapsedWidth

**Comment by chenshuai2144** [comment]
看这个demo
https://prolayout.ant.design/menu#%E5%85%B3%E9%97%AD%E6%97%B6%E5%AE%8C%E5%85%A8%E6%94%B6%E8%B5%B7-menu
