### ISSUE TITLE
ProLayout怎么关掉国际化

### ISSUE THREAD

**Issue by ffalconjs** [ant-design/ant-design-pro-layout#460]
<ProLayout
  menu={{ locale: false }}
/>
无法关掉国际化
[React Intl] Missing message: "menu.权限测试" for locale: "zh-CN", using default message as fallback.

**Comment by chenshuai2144** [comment]
是不是低版本？升级一下版本。formartmessage 也需要不传入

**Comment by ffalconjs** [comment]
"@ant-design/pro-layout": "^5.0.8",

**Comment by ffalconjs** [comment]
没有手动传入formartmessage，menuData是直接从路由配置自动生成的

**Comment by chenshuai2144** [comment]
是个 bug，最新的版本修复了
