### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by hanxinimm** [ant-design/ant-design-pro-layout#461]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

页面Title无法正确显示
![image](https://user-images.githubusercontent.com/13499426/82025344-c79d8600-96c3-11ea-94c7-973df97c0fc7.png)

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

设置 hideInMenu 属性后无法正确显示标题头

![image](https://user-images.githubusercontent.com/13499426/82025405-e26ffa80-96c3-11ea-9fbc-2046190383e1.png)

### 🏞 期望结果 [描述你原本期望看到的结果]

![image](https://user-images.githubusercontent.com/13499426/82025709-47c3eb80-96c4-11ea-99f9-9d92575f63e1.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by zhouzebin** [comment]
我跟你遇到同样的问题，我的面包屑也不正常，你的是正常的吗，如果填写了hideInMenu，那一层的面包屑就没了吧

**Comment by hanxinimm** [comment]
> 我跟你遇到同样的问题，我的面包屑也不正常，你的是正常的吗，如果填写了hideInMenu，那一层的面包屑就没了吧
不正常，反正我就那样放着，等着官方更新~

**Comment by chenshuai2144** [comment]
fixed in  5.0.14
