### ISSUE TITLE
🧐[问题]也有可能是BUG,v4版本为什么route配置中添加了hideInMenu后，title和面包屑都不对

### ISSUE THREAD

**Issue by zhouzebin** [ant-design/ant-design-pro-layout#464]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
      为了让详情页面不显示在菜单中必须要给route配置中添加hideInMenu：true
然而添加后，ProLayout的breadcrumbRender函数参数routes就拿不到当前详情页面的那个route，因为他已经被menu过滤掉了，导致最后面包屑少了最后一层，而且title也不对。
      目前为了解决这个问题，我在页面的pageHeader单独设置了breadcrumb，除此之外有更好的解决办法吗

**Comment by xuchao321** [comment]
请问解决了吗

**Comment by qianxiaowu0520** [comment]
@umijs/route-utils下的transformRoute函数加了一个参数
ignoreFilter 是否筛选掉不展示的 menuItem 项

**Comment by xielhjia** [comment]
是的，楼上正解， 暂时可修改 node_modules/@ant-design/pro-layout/es/utils/getMenuData.js文件中，最后一个方法中_transformRoute 和renderData变量生成时，参数由三个变为四个，第四个参数传true 
 var _transformRoute = transformRoute(routes, (menu === null || menu === void 0 ? void 0 : menu.locale) || false, formatMessage， true)
  var renderData = transformRoute(menuDataRender(menuData), (menu === null || menu === void 0 ? void 0 : menu.locale) || false, formatMessage， true);

改完之后重新run工程， 二级面包屑可正常展示

改完之后可坐等官方更新

**Comment by chenshuai2144** [comment]
@xielhjia  来个 pr？ 这么熟练不来个pr 可惜了
