### ISSUE TITLE
侧栏菜单不能正确选中，PageHeaderWrapper标题高度异常

### ISSUE THREAD

**Issue by zim-lee** [ant-design/ant-design-pro-layout#465]
![捕获](https://user-images.githubusercontent.com/6970789/82343995-1762b100-9a26-11ea-8aee-76612fff5dae.PNG)
如图，
1. PageHeaderWrapper标题栏高度异常  
2. 侧栏菜单不能正确选中，第一个一直会选中  

`yarn create @umijs/umi-app`, 默认的项目即可复现

`json
"dependencies": {
    "@ant-design/pro-layout": "^5.0.12",
    "@umijs/preset-react": "1.x",
    "@umijs/test": "^3.2.1",
    "lint-staged": "^10.0.7",
    "prettier": "^1.19.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "umi": "^3.2.1",
    "yorkie": "^2.0.0"
  }
`

**Comment by xuchao321** [comment]
您好，问题解决了吗

**Comment by zim-lee** [comment]
@xuchao321 没有，回退到5.0.8了，这个版本没这些问题

**Comment by xuchao321** [comment]
您好  版本回退管事了  下面chu xian出现空白了 遇到了么
![image](https://user-images.githubusercontent.com/28084523/82784848-f372f580-9e93-11ea-8237-01b4ac174168.png)

**Comment by Hencky** [comment]
> 您好 版本回退管事了 下面chu xian出现空白了 遇到了么
> ![image](https://user-images.githubusercontent.com/28084523/82784848-f372f580-9e93-11ea-8237-01b4ac174168.png)

同遇到，自己搞下样式解决。style={{ height: '100vh'}}

**Comment by zim-lee** [comment]
`5.0.15`经验证，已经修复了这个问题，高度需要设置`disableContentMargin=false`，这个参数文档没有提及，以前是有margin值的

其他人要是还有问题，另开issue吧
