### ISSUE TITLE
🐛[BUG]6.0.0-1版本bug

### ISSUE THREAD

**Issue by xiexingen** [ant-design/ant-design-pro-layout#466]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
1.配置layout:{locale:false} 不会生效，还是会去找本地化相关的东西
2.图标会多了一份应用到子层级去了
![image](https://user-images.githubusercontent.com/7939085/82400598-4e6aae00-9a8a-11ea-983e-99fa9d7ed064.png)
![image](https://user-images.githubusercontent.com/7939085/82400605-562a5280-9a8a-11ea-8046-e94464f9b7f9.png)
3.折叠后再打开，选中的子菜单不会自动展开
![image](https://user-images.githubusercontent.com/7939085/82400829-d2bd3100-9a8a-11ea-9064-dbc48eb3de6e.png)

4.折叠侧滑菜单，菜单项不能点击
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
6.0.0-5 已经修复

**Comment by xiexingen** [comment]
![image](https://user-images.githubusercontent.com/7939085/83621782-b6101580-a5c1-11ea-8957-8a6a11e6063a.png)

![image](https://user-images.githubusercontent.com/7939085/83621715-9f69be80-a5c1-11ea-8614-090fc3a2830f.png)
如图所示，点左下角折叠后不会在展开选中的菜单
