### ISSUE TITLE
🧐[问题]umi中layout的默认值问题

### ISSUE THREAD

**Issue by ikun** [ant-design/ant-design-pro-layout#469]
### umi中的layout默认值和文档中的不一致

文档中显示`fixedHeader`和`fixSiderbar`的默认值为false，但是实际umi中的默认值为true

另外`ant-pro-basicLayout-content` 这个元素上被加入了一个类名`ant-pro-basicLayout-content-disable-margin`；

这个结果和 https://preview.pro.ant.design/ 中显示的不一致；

多出的这个类名通过一个`disableContentMargin=false`的参数才可以关闭，但是这个配置并未出现在文档中。

umi中的layout的默认配置是否有文档可以提供

**Comment by sxxhlx** [comment]
遇到了同样的问题，另外关于logo的配置是否可以有更详细的说明？

**Comment by laomaner** [comment]
"另外ant-pro-basicLayout-content 这个元素上被加入了一个类名ant-pro-basicLayout-content-disable-margin；"    +1

**Comment by laomaner** [comment]
> "另外ant-pro-basicLayout-content 这个元素上被加入了一个类名ant-pro-basicLayout-content-disable-margin；" +1

![image](https://user-images.githubusercontent.com/32118623/84131000-f3bbe500-aa7e-11ea-965c-86ec8fac23ed.png)
貌似新的脚手架直接生成了disableContentMargin: false 这个配置

**Comment by chenshuai2144** [comment]
楼上正解，被插件给覆盖了
