### ISSUE TITLE
🐛[BUG] pro-layout 6.0.0-2 无法点击一级菜单

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro-layout#470]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
pro-layout 6.0.0-2 无法点击一级菜单，手机下无法唤出菜单
![QQ浏览器截图20200520192347](https://user-images.githubusercontent.com/3166799/82441627-cb207b00-9ad0-11ea-8805-0f344dd7a3c4.png)
![微信截图_20200520192522](https://user-images.githubusercontent.com/3166799/82441634-ccea3e80-9ad0-11ea-9e78-1c5f0258890d.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 3.2.1
- 浏览器环境 Chrome 80
- 开发环境 Windows 10

**Comment by zlyyyy** [comment]
看了下代码，包裹问题，a链接现在只包裹了文字
![image](https://user-images.githubusercontent.com/22760932/82885123-483b6c80-9f77-11ea-8eee-6a6c97ec0f0b.png)
现在的icon是传过去的了，导致没a包裹
![image](https://user-images.githubusercontent.com/22760932/82885648-0232d880-9f78-11ea-8537-3a9e09647d18.png)
之前是这样
![image](https://user-images.githubusercontent.com/22760932/82885763-268eb500-9f78-11ea-9394-c42a764d7526.png)

![image](https://user-images.githubusercontent.com/22760932/82885971-6f466e00-9f78-11ea-8b35-a6cb2ddb1b01.png)

现在长这样
![image](https://user-images.githubusercontent.com/22760932/82885815-373f2b00-9f78-11ea-8de8-e13fd0e3cac3.png)

**Comment by chenshuai2144** [comment]
6.0.0-5 修复了，回滚了用法
