### ISSUE TITLE
🐛[BUG]5.0.11引入@umijs/route-utils后sidermenu的openkeys无法正确计算

### ISSUE THREAD

**Issue by johnnylc** [ant-design/ant-design-pro-layout#472]
### 🐛 bug 描述 
采用服务器渲染方式定义：
menuDataRender={() => menuData}
menuData定义为：
[{
  name: "人员组织管理",
  path: "admin/userMng/",
  children: [
    {name: "人员管理", path: "/admin/userMng/users"}
    {name: "单位管理", path: "/admin/userMng/companies"}
  ]
}] 

若访问路径pathname为 /admin/userMng/companies，对应于二级菜单“单位管理”，
在5.0.10中展示如图
![image](https://user-images.githubusercontent.com/12717523/82586499-3bf78e00-9bca-11ea-8bdd-ef49110fb740.png)
在5.0.12中展示如图
![image](https://user-images.githubusercontent.com/12717523/82586543-516cb800-9bca-11ea-836a-16cb6d3ce2d8.png)
可以发现在5.0.12中一级菜单没有正确展开。

对pro-layout进行调试, 发现src/SiderMenu/BaseMenu中调用函数getSelectedMenuKeys计算openKeys时的计算结果存在差异，
输入路径为 location.pathname='/admin/userMng/companies'时，
5.0.10输出keys为 ["/", "admin/userMng/", "/admin/userMng/companies"]
5.0.12输出keys为 ["/admin/userMng/companies"]
因此，导致了在5.0.12中无法正确展开父级菜单项。

### © 版本信息
- Ant Design Pro Layout版本:  5.0.12
- Antd 版本 4.2.4
- 浏览器环境 81.0.4044.138
- 开发环境 mac OS

**Comment by xuchao321** [comment]
解决了吗

**Comment by heyepeng** [comment]
遇到了同样的问题，目前还没修复pro-layout@5.0.17

**Comment by LiUhoNgDan222** [comment]
解决了吗？我也遇到这个问题了
