### ISSUE TITLE
 pro layout does not work in SSR because of useAntdMediaQuery

### ISSUE THREAD

**Issue by dugagjin** [ant-design/ant-design-pro-layout#473]
pro-layout does not work in SSR.

It breaks due to `useAntdMediaQuery` https://github.com/ant-design/ant-design-pro-layout/blob/3570b645914caf24c4fa2bcfc5d3864d19192420/src/BasicLayout.tsx#L245 which uses the global window object without checking if it exists.

I just did a merge request to fix this: https://github.com/chenshuai2144/useMediaQuery/pull/3

But someone else also did a PR https://github.com/chenshuai2144/useMediaQuery/pull/2 2 months ago but it wasn't followed/merged...

**Comment by jwalton** [comment]
Super hacky wordaround:

```js
import * as useMedia from 'use-media-antd-query';

// Monkey patch use-media-antd-query to make it SSR friendly
// See https://github.com/ant-design/ant-design-pro-layout/issues/473.
useMedia.default = () => 'xl';
```

(Obviously, you want to do this somewhere on your server, and not include this on your client. :)

**Comment by dugagjin** [comment]
@jwalton thanks, it works. 

If working with umijs 3.2, instead of creating a plugin it can be added in `app.(ts|js)` like this:

```ts
// https://github.com/ant-design/ant-design-pro-layout/issues/473
export const ssr = {
    // eslint-disable-next-line @typescript-eslint/require-await
    modifyGetInitialPropsCtx: async (ctx: unknown): Promise<unknown> => {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        // eslint-disable-next-line import/namespace
        useMedia.default = () => `xl`;

        return ctx;
    },
};
```

This temporary fix really messes with tsconfig and eslint, hope that use-media-antd-query will be fixed soon.
