### ISSUE TITLE
🐛[BUG] pro-layout 6.0.0-2 移动端菜单样式错乱

### ISSUE THREAD

**Issue by eiddie** [ant-design/ant-design-pro-layout#474]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
`pro-layout 6.0.0-2 `移动端菜单样式错乱

![image](https://user-images.githubusercontent.com/62737990/82624144-6ff7a100-9c14-11ea-8be3-9852a9415dc2.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
![image](https://user-images.githubusercontent.com/62737990/82624181-830a7100-9c14-11ea-9988-9469898706c7.png)

**Comment by eiddie** [comment]
layout `mix`样式还是错乱， 还有就是三种layout模式在手机端都没有菜单按钮出现
![image](https://user-images.githubusercontent.com/62737990/83089054-f0f8e180-a0c7-11ea-9de8-3d18bbfb92cd.png)

**Comment by chenshuai2144** [comment]
升级  6.0.0-5

**Comment by liangxieq** [comment]
升级 6.0.0-5 还是有问题

**Comment by eiddie** [comment]
> 升级 6.0.0-5

6.0.0.6 缺少菜单按钮
![image](https://user-images.githubusercontent.com/62737990/83934295-88ee7d80-a7e2-11ea-9dec-c358fe3e8677.png)

**Comment by chenshuai2144** [comment]
fixed
