### ISSUE TITLE
路由点击混乱🐛[BUG]

### ISSUE THREAD

**Issue by xuchao321** [ant-design/ant-design-pro-layout#476]
### 刚下载的 ant-design/pro-layout

 © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 @3.1.1
- 浏览器环境 谷歌
- 开发环境 [mac OS]
![image](https://user-images.githubusercontent.com/28084523/82772260-3d96af80-9e71-11ea-8680-7782292e705d.png)

**Comment by xuchao321** [comment]
![image](https://user-images.githubusercontent.com/28084523/82772474-cd3c5e00-9e71-11ea-9b1a-d4ab797e5d38.png)

**Comment by xuchao321** [comment]
![image](https://user-images.githubusercontent.com/28084523/82772756-c5c98480-9e72-11ea-8a59-26c6d8b5f94e.png)

**Comment by beginnerJq** [comment]
![image](https://user-images.githubusercontent.com/44048876/82797666-faa4fe00-9ea9-11ea-9179-41e8da7495e7.png)
我也出现同样的问题

**Comment by xuchao321** [comment]
请问解决了吗

**Comment by chenshuai2144** [comment]
@xuchao321把路由配置发一下我检查一下，可以能是 "/" 的问题

**Comment by xuchao321** [comment]
降低 ant-design/pro-layout 版本就好了  谢谢

**Comment by mov1er** [comment]
> 降低 ant-design/pro-layout 版本就好了 谢谢

请问要降到什么版本

**Comment by xuchao321** [comment]
@mov1er 5.0.8

**Comment by chenshuai2144** [comment]
@xuchao321 可以把路由发出来给做一下 debug 吗？
