### ISSUE TITLE
🐛[BUG] antd-pro-v5,  v6.0.0-3 

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro-layout#478]
console.log 错误

![image](https://user-images.githubusercontent.com/18542211/82857985-24f7c980-9f45-11ea-93d7-d85630d61534.png)

@chenshuai2144

**Comment by chenshuai2144** [comment]
@kaoding  antd 的锅，被透传了，我会提个 pr

**Comment by kaoding** [comment]
> @kaoding antd 的锅被透传了，还不能设置为未定义。 我会提个 pr，不会影响功能的

不影响使用，

**Comment by leesama** [comment]
我这边发现该BUG已经影响到鉴权了

**Comment by kaoding** [comment]
https://github.com/react-component/menu/pull/322https://github.com/react-component/menu/pull/322

**Comment by leesama** [comment]
@kaoding 请问下我这边该如何做来更新修复的代码呢？

**Comment by 510846** [comment]
> 我这边发现该BUG已经影响到鉴权了

https://github.com/ant-design/ant-design-pro/issues/6695

—— 我也发现 鉴权 bug，不知道是否说的是一个问题
