### ISSUE TITLE
为什么是 fixSiderbar 而不是 fixedSiderbar ？

### ISSUE THREAD

**Issue by shanlaomao** [ant-design/ant-design-pro-layout#481]
为什么是 fixSiderbar 而不是 fixedSiderbar ？

**Comment by chenshuai2144** [comment]
Siderbar  是 antd 的名字，是一个新词。
https://ant.design/components/layout/#Component-Overview

**Comment by shanlaomao** [comment]
可能我没有表达清楚，我的问题是为什么用的是 fix 而不是 fixed？因为同类的属性 fixedHeader 用的又是 fixed。
