### ISSUE TITLE
🐛[BUG] pro-layout 6.0.0-4 侧边栏收缩按钮在页面较长时下沉到底部体验不好

### ISSUE THREAD

**Issue by shanlaomao** [ant-design/ant-design-pro-layout#483]
pro-layout 6.0.0-4 侧边栏收缩按钮在页面较长时下沉到页面最底部，需要滑动滚动条才可以点击，体验十分不好。建议像之前的版本一样将收缩按钮放在顶部。

**Comment by chenshuai2144** [comment]
设计师希望默认菜单是固定的，按钮也总是会在一屏上
