### ISSUE TITLE
🐛[BUG] v6.0.0-4 侧边栏菜单“收缩”按钮跑到页底了 ~

### ISSUE THREAD

**Issue by 510846** [ant-design/ant-design-pro-layout#484]
defaultSettings.ts
layout: 'mix' => 'side'
更改后，头部的收缩菜单按钮不见了，侧边菜单的阴影也不见了，一起看看 ~

![image](https://user-images.githubusercontent.com/7681405/82984752-56e05d00-a025-11ea-9d7b-7402b9d4addc.png)

下图是之前正常的效果
![image](https://user-images.githubusercontent.com/7681405/82984786-695a9680-a025-11ea-96e5-c113ce3f0ac7.png)

**Comment by chenshuai2144** [comment]
> 头部的收缩菜单按钮不见了

这个是新设计

**Comment by 510846** [comment]
> > 头部的收缩菜单按钮不见了
> 
> 这个是新设计
> 
> > 侧边菜单的阴影也不见了
> 
> 已修复

然而并没有修复啊
`"@ant-design/pro-layout": "6.0.0-5"`
`"antd": "^4.3.1"`

defaultSettings.ts
layout: 'mix' => 'side'
更改后，头部的收缩菜单按钮不见了，侧边菜单的阴影也不见了，一起看看 ~

主贴发了图片对比 ~
