### ISSUE TITLE
🐛[BUG]6.0.0-5好像无法安装,已经几天了,使用yarn isntall的时候最多只能选择6.x-4

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro-layout#487]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by shanlaomao** [comment]
6.0.0-5 似乎没有提交到 npmjs.com @chenshuai2144

**Comment by 510846** [comment]
> 6.0.0-5 似乎没有提交到 npmjs.com @chenshuai2144

6.0.0-4 版本菜单有bug，可以先修复么？看着难受😣

https://github.com/ant-design/ant-design-pro-layout/issues/484

**Comment by chenshuai2144** [comment]
重新发布了一下，应该是网络不好挂了

**Comment by 510846** [comment]
> 重新发布了一下，应该是网络不好挂了

`yarn info @ant-design/pro-layout version`
`5.0.13`

回到解放前了？

**Comment by shanlaomao** [comment]
> > 重新发布了一下，应该是网络不好挂了
> 
> `yarn info @ant-design/pro-layout version`
> `5.0.13`
> 
> 回到解放前了？

大兄弟，两版同发的

`npm info @ant-design/pro-layout@6.0.0-5 version`

**Comment by joesdu** [comment]
> > 重新发布了一下，应该是网络不好挂了
> 
> `yarn info @ant-design/pro-layout version`
> `5.0.13`
> 
> 回到解放前了？

预览版需要指定包版本才行

**Comment by 510846** [comment]
> info @ant-design/pro-layout@6.0.0-5 version

明白了。这样的话，我就没有办法通过命令行知道 v6 最新版了？

**Comment by joesdu** [comment]
> > info @ant-design/pro-layout@6.0.0-5 version
> 
> 明白了。这样的话，我就没有办法通过命令行知道 v6 最新版了？

可以用VS Code的插件,Version Lens

**Comment by shanlaomao** [comment]
> > > info @ant-design/pro-layout@6.0.0-5 version
> > 
> > 
> > 明白了。这样的话，我就没有办法通过命令行知道 v6 最新版了？
> 
> 可以用VS Code的插件,Version Lens

npm install @ant-design/pro-layout@6.0.0-5 --save
