### ISSUE TITLE
路由前面的icon如何添加，提示下个版本删除了

### ISSUE THREAD

**Issue by xuchao321** [ant-design/ant-design-pro-layout#488]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 3
- 浏览器环境 谷歌
- 开发环境 [e.g. mac OS]

![image](https://user-images.githubusercontent.com/28084523/83623824-65e68280-a5c4-11ea-83f7-fa90e94c9d01.png)
![image](https://user-images.githubusercontent.com/28084523/83623868-7696f880-a5c4-11ea-96dd-41c2f58616a4.png)

**Comment by xuchao321** [comment]
![image](https://user-images.githubusercontent.com/28084523/83623957-98907b00-a5c4-11ea-8628-d516a4c906e6.png)

**Comment by chenshuai2144** [comment]
https://prolayout.ant.design/menu#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8A%A0%E8%BD%BD-menu-%E5%B9%B6%E4%B8%94%E4%BD%BF%E7%94%A8-icon

看这里
