### ISSUE TITLE
🐛[BUG] 5.0.13 菜单不能点击

### ISSUE THREAD

**Issue by yaoguoba** [ant-design/ant-design-pro-layout#489]
### © 版本信息

- Ant Design Pro 版本: 4.3.1
- umi 版本: 3.2.3
- 浏览器环境: Microsoft Edge
- 开发环境 windows 10 2004

**Comment by jing-wu** [comment]
+1，最新的 5.0.14 也存在同样问题

**Comment by yaoguoba** [comment]
> +1，最新的 5.0.14 也存在同样问题

我看了，5.0.14没有代码更新，只有版本号变了

**Comment by gguan** [comment]
+1

**Comment by yaoguoba** [comment]
这就关闭了，怎么解决的能告诉我吗，我的Mac点击依然没有反应。node_modules和.umijs文件夹删除也不好用
