### ISSUE TITLE
🐛[BUG]6.0.0-5 会报警告

### ISSUE THREAD

**Issue by xiexingen** [ant-design/ant-design-pro-layout#492]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
![image](https://user-images.githubusercontent.com/7939085/83855845-40d04c00-a74b-11ea-8c6f-cdccb9b35db1.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
更新 antd 的版本就好了 
https://github.com/react-component/menu/pull/322
