### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by xiaopanghhh** [ant-design/ant-design-pro-layout#5]
1：右侧删除不必要的组件后，不向面对齐。
![image](https://user-images.githubusercontent.com/24469601/56858758-64568e00-69b2-11e9-971d-48276329bda6.png)

2：当窗口变小以后，Logo显示不正确。
![image](https://user-images.githubusercontent.com/24469601/56858766-91a33c00-69b2-11e9-94e0-f6e381f2a85f.png)

3：当窗口变小以后，菜单显示不正确。   抽屉的关闭按钮被挡住一半，另外菜单感觉也是显示一半。
![image](https://user-images.githubusercontent.com/24469601/56858775-ba2b3600-69b2-11e9-8d12-514ff37b3789.png)

**Comment by chenshuai2144** [comment]
> 1：右侧删除不必要的组件后，不向面对齐。
这个需要自己处理了，layout 不包括右边那个
