### ISSUE TITLE
BasicLayout 不展示logo，title怎样加链接

### ISSUE THREAD

**Issue by zhangzhi93** [ant-design/ant-design-pro-layout#50]
```javascript
<ProLayoutComponents
      title={<Link to="/">标题</Link>}
      logo={false}
      onCollapse={false}
      collapsed={false}
      menuItemRender={(menuItemProps, defaultDom) => {
        return <Link to={menuItemProps.path.replace(/:id/, id)}>{defaultDom}</Link>;
      }}
      breadcrumbRender={false}
      footerRender={false}
      menuDataRender={menuDataRender}
      formatMessage={formatMessage}
      rightContentRender={rightProps => <RightContent {...rightProps} />}
      {...props}
      {...settings}
    >
      {children}
</ProLayoutComponents>
```

其中根路径‘/’是个dashboard，这样写从dashboard进入具体某个业务之后，PageTitle.split('-')[0]这个地方会报错，请问下怎样给title加链接？

**Comment by chenshuai2144** [comment]
PageTitle 为空吗？给你重现的代码我看看。

**Comment by zhangzhi93** [comment]
> PageTitle 为空吗？给你重现的代码我看看。

不为空，打断点看了下，pageTitle是一个对象，是不是因为title传的<Link>导致的？

**Comment by chenshuai2144** [comment]
有可能，我加个新特性。支持一下title为一个 reactNode

**Comment by chenshuai2144** [comment]
你直接在 proLayout中设置title就好了。pageTitle是根据 router中的配置算出来的

**Comment by zhangzhi93** [comment]
> 你直接在 proLayout中设置title就好了。pageTitle是根据 router中的配置算出来的

![image](https://user-images.githubusercontent.com/16435301/60763762-cf58cb00-a0ad-11e9-859b-6ff76ab6d0fc.png)
![image](https://user-images.githubusercontent.com/16435301/60763801-58700200-a0ae-11e9-8e04-f9b536d7892c.png)
![image](https://user-images.githubusercontent.com/16435301/60763806-62920080-a0ae-11e9-8298-3eb48985cc03.png)

这样加吗？就是这样加会报错

**Comment by chenshuai2144** [comment]
有个 pageTitleRender 的方法，试试这个

**Comment by xiaoshui222** [comment]
> 有个 pageTitleRender 的方法，试试这个

我试的pageTitleRender方法不会重新侧边栏的title，而是改变的当前路由页面的title，
侧边菜单上面的系统名字，怎么支持reactNode呢

**Comment by wangjianio** [comment]
目前是这么写的。

不想要 logo 的话把 `menuHeaderRender` 里的 `logoDom` 删掉就好了，但菜单收起的效果就要另处理了。

```jsx
<ProLayout
    title="左上角string"
    menuHeaderRender={(logoDom, titleDom) => <Link to="/">{logoDom}{titleDom}</Link>}
>
    {children}
</ProLayout>
```

这个文档里没有写，不确定后续更新的兼容性。

版本：`4.5.16`
