### ISSUE TITLE
🐛[BUG] PageContainer onTabChange返回的key值不是传入的tab.key，而变成了index

### ISSUE THREAD

**Issue by WangJM001** [ant-design/ant-design-pro-layout#500]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

PageContainer onTabChange返回的key值不是传入的tab.key，而变成了index

### © 版本信息

- pro-layout版本：6.0.0-7

**Comment by yunuo-tech** [comment]
同样的问题

**Comment by LeroChen** [comment]
+1

**Comment by zooeydotmango** [comment]
同样的问题，并且切换tab时tabActiveKey样式失效

**Comment by WangJM001** [comment]
@chenshuai2144

**Comment by WangJM001** [comment]
新版本已经解决
