### ISSUE TITLE
🧐[问题] 配置路由后菜单无法显示

### ISSUE THREAD

**Issue by dominicleo** [ant-design/ant-design-pro-layout#501]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
菜单无法正常显示
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
repo https://github.com/dominicleo/ijia-bi

**Comment by chenshuai2144** [comment]
router 配置要写 name，不然不知道改显示什么名字
