### ISSUE TITLE
👑 [需求]增加打开过路由渲染tabs的功能

### ISSUE THREAD

**Issue by Renderz** [ant-design/ant-design-pro-layout#507]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
- 部分中台系统会有能够通过tabs缓存已打开tabs的功能, 方便多个路由切换,  切换后的路由要能够保持之前打开的状态. 
- 能够支持通路由不同match能打开多个tabs, 比如"id"不相同的"详情页", 但是tab 的name应该能通过某种方式配置render方法, 能够区分.
- tabs的打开关闭方法能够开放调用. 比如执行某个操作后, 能够关闭其中某个tab.

**Comment by exvu** [comment]
你可以通过store除非你那个tabs记录，路由切换进行匹配，匹配成功显示，否则隐藏 react暂时没有keep-alive

**Comment by chenshuai2144** [comment]
暂时不会做的，没有 kerp-alive，react 实现性能也很差
