### ISSUE TITLE
🐛[BUG]菜单不随权限更新刷新，面包屑跳转路径错误

### ISSUE THREAD

**Issue by Hencky** [ant-design/ant-design-pro-layout#508]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
1. 权限更新后菜单不会更新（配置同antd pro v5版本）
2. 配置history模式为hash，点击面包屑跳转路由错误

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
1. clone代码，安装依赖，启动项目  yarn && yarn start
2. 点击权限切换按钮，菜单不刷新
3. 点击page1菜单下任意子菜单，点击面包屑

### 🏞 期望结果 [描述你原本期望看到的结果]
1. 权限更新后无权限菜单不可见
2. hash模式面包屑跳转正常

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

仓库地址：https://github.com/Hencky/pro-layout-test

### © 版本信息

- pro-layout: 5.0.17
- umi 版本: 3.2.7 插件都为最新版
- 浏览器环境: chrome .81
- 开发环境 : windows10

**Comment by youshao** [comment]
我也遇到这个问题，看了源码后，发现路由跳转时使用了 <a> 标签，和 href 直接取了 route 中的 path。
https://github.com/ant-design/ant-design-pro-layout/issues/531#issue-650308313

**Comment by chenshuai2144** [comment]
最后还是用了 reload ，在 pro 中解决了
