### ISSUE TITLE
🧐[问题]在basicLayout里面如何获取到路由的name值。需要用它来翻译

### ISSUE THREAD

**Issue by juewangxiansheng** [ant-design/ant-design-pro-layout#513]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
在basicLayout里面如何获取到路由的name值。需要用它来翻译

**Comment by chenshuai2144** [comment]
试试 RouteContext，里面有的

https://github.com/ant-design/ant-design-pro-layout/blob/389b6f239a97d6efce7192a379d50c8e32ac434a/src/PageContainer/index.tsx#L135

**Comment by juewangxiansheng** [comment]
谢谢好的



---原始邮件---
发件人: "陈帅"<notifications@github.com&gt;
发送时间: 2020年6月26日(周五) 下午2:13
收件人: "ant-design/ant-design-pro-layout"<ant-design-pro-layout@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"绝望先生"<493341396@qq.com&gt;;
主题: Re: [ant-design/ant-design-pro-layout] 類[问题]在basicLayout里面如何获取到路由的name值。需要用它来翻译 (#513)




 
试试 RouteContext，里面有的
 
https://github.com/ant-design/ant-design-pro-layout/blob/389b6f239a97d6efce7192a379d50c8e32ac434a/src/PageContainer/index.tsx#L135
