### ISSUE TITLE
[BUG] pro-layout 6.0.0-8 layout自适应的bug

### ISSUE THREAD

**Issue by xiexingen** [ant-design/ant-design-pro-layout#516]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
side布局模式下，小屏幕的时候左侧菜单隐藏了，而且没有地方可以操作再展现出来
![image](https://user-images.githubusercontent.com/7939085/84966494-3f882180-b144-11ea-930a-1f80ee87c079.png)
![image](https://user-images.githubusercontent.com/7939085/84966504-4747c600-b144-11ea-8424-a852caeea2e1.png)

在pro-layout5.x版本中，有个折叠的操作按钮在上方，6.x版本中这个折叠按钮在左侧菜单的下方了

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/85826368-0dfffd80-b7b7-11ea-9d53-e45868fb2b1a.png)


6.0.9 将会解决
