### ISSUE TITLE
🐛[BUG]路由配置了layout:false，safari浏览器无法隐藏菜单栏及导航栏

### ISSUE THREAD

**Issue by weiTimes** [ant-design/ant-design-pro-layout#520]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

在路由配置文件中配置了layout:false， 在谷歌浏览器可以正常隐藏，safari无法正常隐藏。

### 🏞 期望结果 [描述你原本期望看到的结果]

在safari浏览器可以隐藏导航栏和菜单栏

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

config.ts中routes的配置项如下所示
```
export default [
  {
    path: '/user',
    layout: false,
    routes: [
      {
        name: 'login',
        path: '/user/login',
        component: './user/login',
      },
    ],
  }
...
]
```

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0-alpha.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by wangjieCode** [comment]
同样问题，楼主有解决办法么

**Comment by weiTimes** [comment]
没有呢，估计是bug，兼容性问题

**Comment by justindeng0405** [comment]
还没解决的
