### ISSUE TITLE
🐛[BUG] 6.0.1版本 二级菜单的Icon永远无法显示

### ISSUE THREAD

**Issue by Nokecy** [ant-design/ant-design-pro-layout#525]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
https://github.com/ant-design/ant-design-pro-layout/blob/6d965c1b30ddf74465a6ab21ba99b209a1a5d378/src/SiderMenu/BaseMenu.tsx#L188
### © 版本信息

- Ant Design Pro 版本: V6.0.1
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by joesdu** [comment]
二级菜单不显示图标是新功能.所以不管你怎么搞,别人都不会渲染.

**Comment by chenshuai2144** [comment]
这个是设计，是故意的，就是不让你写

**Comment by phoema** [comment]
![image](https://user-images.githubusercontent.com/8730272/87223758-0e50e900-c3b2-11ea-8b33-d795ad3865dd.png)
![image](https://user-images.githubusercontent.com/8730272/87223768-2de81180-c3b2-11ea-83fb-86297052f061.png)
我的天啊，我一通查兼容性问题，原来是你们故意的！！！

**Comment by phoema** [comment]
另外，我觉得对齐方式也没以前好看了呢。

**Comment by phoema** [comment]
这个设计有点反人类，我想用图标，已经配置了，还得再render一次。
