### ISSUE TITLE
🐛[BUG] 6.0.1 菜单滚动条如何隐藏，太丑了

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro-layout#526]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

![QQ浏览器截图20200630192010](https://user-images.githubusercontent.com/3166799/86121252-4cbfeb80-bb08-11ea-8fb6-d4bead8451f8.png)

PageHeaderWrapper TabList 无法点击
![QQ浏览器截图20200630200150](https://user-images.githubusercontent.com/3166799/86123831-c1952480-bb0c-11ea-99c9-fff4d7e21cbc.png)

### © 版本信息

- Ant Design Pro 版本: 4.4.0
- umi 版本 3.2.6
- 浏览器环境 Chrome 83
- 开发环境 [e.g. mac OS] Windows 10

**Comment by chenshuai2144** [comment]
fixSiderbar={false} 你的菜单有点多，建议用用 splitMenus

**Comment by hihuangwei** [comment]
> fixSiderbar={false} 你的菜单有点多，建议用用 splitMenus

可否增加一个api，是否显示滚动条可选
