### ISSUE TITLE
🧐[问题] defaultItemRender 为什么使用 <a> 标签而不是使用 <link>

### ISSUE THREAD

**Issue by youshao** [ant-design/ant-design-pro-layout#531]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/11664572/86425558-15278e00-bd18-11ea-8a5b-7c607dcc6441.png)

项目中使用了 hash 路由，在使用 <PageContainer> 是发现面包屑并没有携带 # 号。查看源码后发现内置的地址是直接取路由配置中的 path，并且使用了 <a> 标签来跳转。

如果我需要改为 hash 路由（#）的方式，除了修改源码和重写 Breadcrumb 中的 itemRender 以外，有没有通过配置修改的方式？

"dependencies":
    "umi": "^3.2.2",
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-layout": "6.0.0-8",
    "@ant-design/pro-table": "^2.3.0",
    "@types/qrcode.react": "^1.0.1",
    "antd": "^4.0.0",

**Comment by chenshuai2144** [comment]
ProLayout 中也支持 itemRender 的设置，你可以在 ProLayout 的 props 上直接设置

**Comment by chenshuai2144** [comment]
Link 要依赖别的包，我们希望 layout 要纯粹一些

**Comment by chenshuai2144** [comment]
```
 itemRender={(route, params, routes, paths) => {
        const first = routes.indexOf(route) === 0;
        return first ? (
          <Link to={paths.join('/')}>{route.breadcrumbName}</Link>
        ) : (
          <span>{route.breadcrumbName}</span>
        );
      }}
```

**Comment by youshao** [comment]
> ```
>  itemRender={(route, params, routes, paths) => {
>         const first = routes.indexOf(route) === 0;
>         return first ? (
>           <Link to={paths.join('/')}>{route.breadcrumbName}</Link>
>         ) : (
>           <span>{route.breadcrumbName}</span>
>         );
>       }}
> ```

好的，谢谢，但是路由的跳转，建议还是使用 Link 来实现，这样能更好的适配不同的路由模式，而不是自行再封装 “PageContainer”

**Comment by justindeng0405** [comment]
mark下解决方法
