### ISSUE TITLE
🐛[BUG]6.1.0版本样式好像出现问题了,升级后部分页面出现奇怪的问题.

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro-layout#532]
🐛[BUG]

6.1.0版本样式好像出现问题了,升级后部分页面出现奇怪的问题.右边的内容container会跑到菜单后边去.

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
有截图吗？

**Comment by joesdu** [comment]
周一发给你

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by joesdu** [comment]
> 有截图吗？

![image](https://user-images.githubusercontent.com/13188169/86536596-7f5c5080-bf1b-11ea-9766-fe0fb35ab27d.png)
![image](https://user-images.githubusercontent.com/13188169/86536615-913df380-bf1b-11ea-9302-1553d5f09753.png)
![image](https://user-images.githubusercontent.com/13188169/86536619-97cc6b00-bf1b-11ea-98b6-f8d500b86dc5.png)
![image](https://user-images.githubusercontent.com/13188169/86536624-9d29b580-bf1b-11ea-9380-35926e55da6d.png)
![image](https://user-images.githubusercontent.com/13188169/86536630-a1ee6980-bf1b-11ea-86c4-b16b989e6acd.png)
![image](https://user-images.githubusercontent.com/13188169/86536634-aa46a480-bf1b-11ea-8cc3-7b06d81d4654.png)

部分页面显示OK,部分就不行了.6.0.1是完全OK的.

**Comment by joesdu** [comment]
6.2.0问题依旧.

**Comment by hihuangwei** [comment]
> 有截图吗？

这是由于 Tabel 组件 column.ellipsis: true 导致的

**Comment by hihuangwei** [comment]
> 6.2.0问题依旧.

Table 设置tableLayout="auto" 可以接解决该问题 @chenshuai2144 @joesdu

**Comment by joesdu** [comment]
> > 6.2.0问题依旧.
> 
> Table 设置tableLayout="auto" 可以接解决该问题 @chenshuai2144 @joesdu

这个按理说是个bug才对.我暂时也用这种办法解决吧.

**Comment by joesdu** [comment]
> > 6.2.0问题依旧.
> 
> Table 设置tableLayout="auto" 可以接解决该问题 @chenshuai2144 @joesdu

设置为auto后,在tab中切换页签后,依然会出现样式异常.

**Comment by kaoding** [comment]
https://github.com/ant-design/ant-design-pro/issues/6963

**Comment by chenshuai2144** [comment]
fixed in 6.2.1
