### ISSUE TITLE
MenuItem attribute title warning

### ISSUE THREAD

**Issue by yezongyang** [ant-design/ant-design-pro-layout#534]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
SiderMenu文件，Menu.Item title 属性传参类型不符合
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
![企业微信截图_accc2734-3b7b-4e16-b5eb-8fa113aef936](https://user-images.githubusercontent.com/8924156/86525959-71c5ad00-bec0-11ea-9c1a-d08a16c61b5c.png)
![企业微信截图_552e2395-9664-4bf7-bfcb-4856e30585c4](https://user-images.githubusercontent.com/8924156/86525987-afc2d100-bec0-11ea-872f-df1d7fad8089.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
没有warning提示
### © 版本信息
v6.1.0

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
等待 antd 更新吧，这是 antd 搞得
