### ISSUE TITLE
🐛[BUG]左侧导航固定，右侧内容宽度过大会挤压左侧导航

### ISSUE THREAD

**Issue by yezongyang** [ant-design/ant-design-pro-layout#536]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
![企业微信截图_83d560fb-632d-45e4-8ebf-8292dca8775a](https://user-images.githubusercontent.com/8924156/86564686-33e88780-bf99-11ea-984a-94534faeb865.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
空div增加min-width:208px 保证左侧导航宽度
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
有个截图吗？

**Comment by chenshuai2144** [comment]
应该是一个问题，修复了一下

**Comment by zhangminggeek** [comment]
> 应该是一个问题，修复了一下，试试 6.2.0

6.2.0 仍然存在这个问题
