### ISSUE TITLE
🐛[BUG]在build后,layout插件会自动打包一个logo文件到static目录中

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro-layout#541]
### 🐛 bug 描述

在build后,layout插件会自动打包一个logo文件到static目录中,即使我使用了config或者app.ts中配置了网络图片,我将所有资源文件都放到服务器了,打包后static文件夹下边还是有个logo的文件.希望能够修复一下.
我查看了那个svg文件,
![image](https://user-images.githubusercontent.com/13188169/86432875-b704a600-bd2b-11ea-9a82-b4c29eb3985a.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这个好像不好做，因为它就是 import 了一下

**Comment by joesdu** [comment]
> 这个好像不好做，因为它就是 import 了一下

可以试试替换成CDN的链接,别硬导入.

**Comment by chenshuai2144** [comment]
那对离线用户就不友好了，我试试 base64？

**Comment by joesdu** [comment]
> 那对离线用户就不友好了，我试试 base64？

可以![18291322c052161f.png](https://user-images.githubusercontent.com/13188169/87853842-3dca9d00-c940-11ea-9034-dc1125bb70a0.png)

**Comment by joesdu** [comment]
> 那对离线用户就不友好了，我试试 base64？

这个logo还是去不掉.打包后,还是存在估计是umi的问题.

**Comment by joesdu** [comment]
这个logo还是去不掉.打包后,还是存在估计是umi的问题.

> 那对离线用户就不友好了，我试试 base64？

这个logo还是去不掉.打包后,还是存在估计是umi的问题.
