### ISSUE TITLE
🧐[问题]5.0.16版本,折叠按钮是在顶栏上，能不能通过配置移到菜单栏的下方。

### ISSUE THREAD

**Issue by gugu-lee** [ant-design/ant-design-pro-layout#544]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

我的pro-layout的版本是5.0.16.菜单折叠按钮是在顶栏上，我想把它移动菜单栏的下方。怎么做？

**Comment by chenshuai2144** [comment]
升级  6.x 就好了，几乎没有兼容性问题
