### ISSUE TITLE
👑 [需求] 怎么默认选择则菜单第一项

### ISSUE THREAD

**Issue by snice** [ant-design/ant-design-pro-layout#548]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]

如下地址访问

https://preview.pro.ant.design/form
https://preview.pro.ant.design/form?splitMenus=false&navTheme=light&layout=mix

![image](https://user-images.githubusercontent.com/8744870/87117653-a9ab6680-c2ab-11ea-85c2-1a4e325962a4.png)

需求：当访问一个菜单的根路径，怎么跳转到子菜单第一项？

**Comment by 767746649zyy** [comment]
同求

**Comment by chenshuai2144** [comment]
在每个子项下面配置一下，或者写个 umi 插件
```
{
  redirect: "/welcome",
}
```
