### ISSUE TITLE
🧐[问题] layout 属性设置为 top或mix没变化。 

### ISSUE THREAD

**Issue by gugu-lee** [ant-design/ant-design-pro-layout#551]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

我想布局改为上-中-下结构，设置prolayout的layout属性，无论设成哪个值都没有为影响。
在6.2.2和5.0.8版测试都不行。

**Comment by gugu-lee** [comment]
问题解决了，在ant-design环境中，layout属性被履盖了。

**Comment by Ben56** [comment]
> 问题解决了，在ant-design环境中，layout属性被履盖了。

能说的具体点吗?具体在哪里哪个文件覆盖了?
