### ISSUE TITLE
👑 [需求] WrapContent.tsx 文件引入的ConfigProvider配置有可能覆盖项目自定义的配置

### ISSUE THREAD

**Issue by aisriver** [ant-design/ant-design-pro-layout#552]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
比如我在项目中使用
`
<ConfigProvider getPopupContainer={trigger => trigger.parentElement || document.body}>
 <ProLayout />
</ConfigProvider>
`
getPopupContainer 这个属性会被ProLayout里面的覆盖，导致弹窗里面的Select选项浮动出现问题

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
1、这样写能解决问题，但其他用户可能不容易排查到

`
<ProLayout>
  <ConfigProvider getPopupContainer={trigger => trigger.parentElement || document.body}>{props.children}</ConfigProvider>
</ProLayout>
`

2、优化WrapContent文件的写法，getPopupContainer以用户的配置优先

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/28559304/87219914-db96f880-c391-11ea-9c16-024aacb34ef8.png)

**Comment by chenshuai2144** [comment]
看一下，我应该移除掉这个东西

**Comment by aisriver** [comment]
> 看一下，我应该移除掉这个东西

OK！
