### ISSUE TITLE
🧐[问题]服务端返回主题变量本地去修改

### ISSUE THREAD

**Issue by xyy7260** [ant-design/ant-design-pro-layout#554]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
ant-d-Pro: v5版本
系统:mac
后端返回一个主题变量，然后本地去匹配更改

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
假如后端api返回的是主题变量是 result = C
本地做了个匹配
const theme = {
  A: 'dark.css',
  B: 'dust.css',
  C: 'volcano.css',
  D: 'sunset.css',
  E: 'green.css',
};
本地代码中config/theme.config.json
 "theme": [
    { "key": "dark", "fileName": "dark.css", "theme": "dark" },
    { "key": "dust", "fileName": "dust.css", "modifyVars": { "@primary-color": "#F5222D" } },
    { "key": "volcano", "fileName": "volcano.css", "modifyVars": { "@primary-color": "#FA541C" } },
    { "key": "sunset", "fileName": "sunset.css", "modifyVars": { "@primary-color": "#FAAD14" } },
    { "key": "cyan", "fileName": "cyan.css", "modifyVars": { "@primary-color": "#13C2C2" } },
    { "key": "green", "fileName": "green.css", "modifyVars": { "@primary-color": "#52C41A" } },
  ],

[请问有办法能自动修改设置吗？](https://pro.ant.design/docs/dynamic-theme-cn#header)

**Comment by chenshuai2144** [comment]
这个不支持动态的，你要试着在浏览器里编译 less 了
