### ISSUE TITLE
🐛[BUG] V6.3.2 MIX模式 点击logo无法跳转指定URL

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro-layout#560]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

V6.3.2 MIX 模式点击logo无法跳转指定URL
![mmexport1594630071919](https://user-images.githubusercontent.com/3166799/87284252-ba1c4500-c528-11ea-8718-cc7ff5fb5c9c.png)

### © 版本信息

- Ant Design Pro 版本: 6.3.2
- umi 版本 3.2.0
- 浏览器环境 Chrome 86
- 开发环境 Windows 10

**Comment by chenshuai2144** [comment]
| onMenuHeaderClick | menu header click event | `(e: React.MouseEvent<HTMLDivElement>) => void` | - |

**Comment by hihuangwei** [comment]
> 试试这个
> 
> | onMenuHeaderClick | menu header click event | `(e: React.MouseEvent<HTMLDivElement>) => void` | - |

`onMenuHeaderClick={() => history.push('/')}`
添加的了  仍然无法点击跳转
