### ISSUE TITLE
👑 [BasicLayout 怎么对content区域自定义]

### ISSUE THREAD

**Issue by CrazyOctopusDan** [ant-design/ant-design-pro-layout#561]
### 🥰 需求描述 
之前在v4版本中，我在BasicLayout中会有两种页面切换形式，在某一种形式里面是增加了 antd 的 Tabs 组件，并且记录左侧所有点击过的菜单的记录，通过可关闭的Tabs进行展示。
而在V5版本中，通过引入包的形式增加Layout，导致我现在没有办法自定义content，只能通过配置的形式去定义菜单和头部区域，非常希望多一个属性可以类似于：
```
renderContent: ReactDom | any
 
<>
    <Tabs>
        <Tabpane>{children}</Tabpane>
    </Tabs>
</>
```

**Comment by chenshuai2144** [comment]
你希望挂载到哪个 dom 上呢？ 来个截图

**Comment by CrazyOctopusDan** [comment]
> 你希望挂载到哪个 dom 上呢？ 来个截图

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/18019209/87381646-bf7c9c80-c5c7-11ea-97f9-7955b6be531a.png">

**Comment by chenshuai2144** [comment]
childrenRender 试试这个 api
