### ISSUE TITLE
🐛[BUG]PageContainer subTitle未生效

### ISSUE THREAD

**Issue by WangJM001** [ant-design/ant-design-pro-layout#562]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
RT
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Madridspark** [comment]
太不负责任了吧，这种低级错误
