### ISSUE TITLE
🧐[问题] 那么我在不升级pro v5的情况下,pro-layout能升级到最大多少版本号呢?

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design-pro-layout#563]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]

目前我的pro-layout版本为5.0.9
暂时还没升级到pro V5的版本,准备等稳定了再升级pro

然后我看到pro v5的pro-layout版本已经到了6.x

那么我在不升级pro v5的情况下,pro-layout能升级到最大多少版本号呢?

另外,pro-layout的changelog已经好久没更新了,还停留在5.0.5
https://prolayout.ant.design/ 中也没看到相关的changelog

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-layout/releases
看这里，建议升级一下 v5 和 v4 几乎没有任何区别
