### ISSUE TITLE
自定义菜单的问题

### ISSUE THREAD

**Issue by xiaopanghhh** [ant-design/ant-design-pro-layout#57]
自定义菜单，当菜单的层级关系与路由的层级关系不一至时，菜单选中没有问题，但是菜单不展开。

**Comment by xiaopanghhh** [comment]
面包屑的展示，也有这个问题。

**Comment by chenshuai2144** [comment]
现在只支持有层级关系得，比如 /list/item 和 list/menu 认为是同一级别的。建议你修改成同样得层级

**Comment by xiaopanghhh** [comment]
目前的需求，菜单是后端管理系统生成的，但路由是前端配置的。在后端菜单配置的时候，加入了前端路由的PATH对应。而且菜单是客户来定制的，所以菜单的目录很难保证和路由是一至的。菜单的展开、面包屑的数据，如果是根据路由的话，就很难保证了。

另外，ant-design-pro-layout 如何进行本地开发与调试呀，我想试着看看能不能够先根据 路由 确定 menu 节点，再根据 menu 的树型结构 反向算 展开菜单以及面包屑 。

遗憾的是，我没有将 example 跑起来。

**Comment by singleTopMonkey** [comment]
我也遇到这个问题了 请问解决了么

**Comment by effapp** [comment]
自定义菜单，当点击叶子菜单时，菜单会自动折叠起来，怎么办？

**Comment by gaorubin1990** [comment]
![image](https://user-images.githubusercontent.com/49272745/66794731-0d7b4b80-ef35-11e9-821b-32af195b43a1.png)
请问为何这样配置菜单为什么只显示一级

**Comment by chenshuai2144** [comment]
已经解耦了 path，现在允许不是嵌套路径也可以自动打开。
https://prolayout.ant.design/example?anchor=%E5%A4%9A%E4%B8%AA%E8%B7%AF%E7%94%B1%E5%AF%B9%E5%BA%94%E4%B8%80%E4%B8%AA%E8%8F%9C%E5%8D%95%E9%A1%B9#%E5%A4%9A%E4%B8%AA%E8%B7%AF%E7%94%B1%E5%AF%B9%E5%BA%94%E4%B8%80%E4%B8%AA%E8%8F%9C%E5%8D%95%E9%A1%B9

**Comment by summmmer** [comment]
> 自定义菜单，当点击叶子菜单时，菜单会自动折叠起来，怎么办？

同样的问题，解决了吗
