### ISSUE TITLE
🐛[BUG] V6.2.5 页面首次加载完，首次点击菜单会再次加载菜单，会闪烁一下

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro-layout#577]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
![QQ浏览器截图20200719092836](https://user-images.githubusercontent.com/3166799/87865030-5f5c7080-c9a2-11ea-9776-d2a533e4bf4d.png)

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
[https://preview.pro.ant.design](https://preview.pro.ant.design)

**Comment by xuchao321** [comment]
同理 页面刷新完 点击左侧路由 又会刷新一下路由数据  没有做到局部刷新

**Comment by yezongyang** [comment]
刷新进入页面， 滚动点击左侧路由，会发现导航栏会重置定位到顶部，logo图片也会闪烁下

**Comment by shaohuatsou** [comment]
mark
