### ISSUE TITLE
🐛[BUG]配置子菜单icon不显示

### ISSUE THREAD

**Issue by zhouzhiyang-git** [ant-design/ant-design-pro-layout#581]
### 🐛 bug 描述 
配置子菜单icon不显示，如配置方式未改变，那这是个bug

### 🏞 期望结果 
期望和之前版本一样，子菜单父菜单都可以配置icon

### 💻 复现代码 
![image](https://user-images.githubusercontent.com/68043832/87923737-843f0980-cab0-11ea-8fbd-cef961a2b0f8.png)

### © 版本信息

- Ant Design Pro 版本: 4.0.0
- umi 版本:3.2.10
- 浏览器环境
- 开发环境 [windows]

**Comment by joesdu** [comment]
这是新功能,二级菜单不会显示Icon.若是需要实现,可以自己修改layout那个菜单渲染的函数.

**Comment by zhouzhiyang-git** [comment]
是否可以提供一下修改函数的样例

**Comment by joesdu** [comment]
> 是否可以提供一下修改函数的样例

这个可能你需要求助于 @chenshuai2144 看看有没有什么例子.目前我也没写过.我都是用的默认没有icon的.

**Comment by chenshuai2144** [comment]
不要展示icon是最好的

**Comment by snice** [comment]
```ts
    // 自定义菜单渲染
    menuItemRender: (menuItemProps: any, defaultDom: any) => {
      if (menuItemProps.isUrl || !menuItemProps.path) {
        return defaultDom;
      }
      return (
        <Link to={menuItemProps.path}>
          {menuItemProps.icon} {menuItemProps.name}
        </Link>
      );
    }
```

icon 自己处理下，字符创转化成@ant-design/icons组件
