### ISSUE TITLE
V6.2.5 typescript报错

### ISSUE THREAD

**Issue by wocaatm** [ant-design/ant-design-pro-layout#584]
![image](https://user-images.githubusercontent.com/11764069/88024077-b6aa3e80-cb64-11ea-8efe-6020e0d8e682.png)

**Comment by felipembbraga** [comment]
Same here.

**Comment by kkak10** [comment]
+1

**Comment by chenshuai2144** [comment]
升级 ts 的版本到 3.8+

**Comment by kkak10** [comment]
@chenshuai2144 add typescript minimum version on readme file
