### ISSUE TITLE
路由国际化是只会查找第一层路由么？

### ISSUE THREAD

**Issue by zhaoyejuan** [ant-design/ant-design-pro-layout#61]
![image](https://user-images.githubusercontent.com/20035100/61276586-eb154d00-a7e2-11e9-8a1c-5c8eb287a690.png)
![image](https://user-images.githubusercontent.com/20035100/61276624-f8323c00-a7e2-11e9-9c52-0e03d1bc3538.png)
路由国际化是只会替换第一层路由么？

**Comment by chenshuai2144** [comment]
菜单中已经变化了吗? 来个重现地址吧
