### ISSUE TITLE
能否提供类似生意参谋的布局

### ISSUE THREAD

**Issue by gavingy33** [ant-design/ant-design-pro-layout#65]
![image](https://user-images.githubusercontent.com/9748357/61677621-df6ddd00-ad32-11e9-9d3f-9e214d691f49.png)

顶部有主要类别的导航条目
侧边再提供导航条目

**Comment by kzabc** [comment]
顶部改好了吗 我也在该这里  不知道你解决了吗

**Comment by hhking** [comment]
我也遇到这个需求，自己完全实现一套感觉挺麻烦的，所以我自己 fork 修改了这种布局自己用
[header-sider-layout](https://github.com/hhking/header-sider-layout)

**Comment by chenshuai2144** [comment]
@hhking  可以来个 pr 吗

**Comment by hhking** [comment]
@chenshuai2144 这个改动有点大，而且比较定制化。我后面试试能不能调整一下再 pr

**Comment by xiaohuoni** [comment]
[antd-pro-layout.zip](https://github.com/ant-design/ant-design-pro-layout/files/3776955/antd-pro-layout.zip)
看 `config/config.ts` 和 `src/layouts/*`
