### ISSUE TITLE
左上角 logo 和 title  如何添加链接

### ISSUE THREAD

**Issue by flycj** [ant-design/ant-design-pro-layout#69]
![image](https://user-images.githubusercontent.com/5103045/61924059-bcdcfd80-af98-11e9-9307-88675880cd14.png)
如上图，如何给红框中的部分添加链接
我使用
![image](https://user-images.githubusercontent.com/5103045/61924076-d8480880-af98-11e9-84e2-a8a747064ac7.png)
报错：
![image](https://user-images.githubusercontent.com/5103045/61924094-eac24200-af98-11e9-9a14-5c213807ee94.png)
我该如何做呢？

**Comment by LucaLJX** [comment]
左上角的可以通过 logo 传入一个ReactNode进行定制化渲染
楼上需要添加一个连接的需求可以这么实现：
`import { Link } from 'react-router'
<ProLayout
      logo={() => (<Link to='/'>
          <img src={require('@/assets/logo.png')} alt='' />
      </Link>)}
</ProLayout>`

**Comment by flycj** [comment]
![image](https://user-images.githubusercontent.com/5103045/61992509-fd6c7200-b091-11e9-90cc-5b6ea1e6c90c.png)
不行的因为这个组件默认外层就有一个a标签，这个a标签无法修改如上图，无论设置logo 或title 属性为任何 ReactNode 只要有 a 标签就回报下面的错误
![image](https://user-images.githubusercontent.com/5103045/61992521-21c84e80-b092-11e9-898a-429bdfccdeea.png)

**Comment by LucaLJX** [comment]
> ![image](https://user-images.githubusercontent.com/5103045/61992509-fd6c7200-b091-11e9-90cc-5b6ea1e6c90c.png)
> 不行的因为这个组件默认外层就有一个a标签，这个a标签无法修改如上图，无论设置logo 或title 属性为任何 ReactNode 只要有 a 标签就回报下面的错误
> ![image](https://user-images.githubusercontent.com/5103045/61992521-21c84e80-b092-11e9-898a-429bdfccdeea.png)

换了一个写法，这个报错好像是因为ant-d某些组件自带href属性，如果再在里面使用a标签则会报warning，我换了个写法：
```jsx
import router from 'umi/router'
<ProLayout
      logo={() => (
          <img onClick={() => {
            router.push(`/`)
          }} src={require('@/assets/logo.png')} alt='' />
      )}
</ ProLayout>
```

**Comment by flycj** [comment]
![](https://user-images.githubusercontent.com/5103045/61924059-bcdcfd80-af98-11e9-9307-88675880cd14.png)
非常感谢，这确实可以解决问题。
那么如果我想把上图中整个红框里面的都加上链接的话， 就需要分别在title 和 logo 属性中写同样的方法。 但是外层那个a 标签缺无法利用上。 希望这个地方可以改善下
