### ISSUE TITLE
在PageHeaderWrapper组件中配置 breadcrumb属性后并未按预期正常渲

### ISSUE THREAD

**Issue by qhanw** [ant-design/ant-design-pro-layout#73]
在页面PageHeaderWrapper组件中配置 breadcrumb属性后虽然正常渲染到了页面，但功能任然不足，如下图，面包屑的 url 路径是带是有 `#` 的，
实际正确地址应该为:`http://localhost:8000/customer/list`。 
虽然在BasicLayout文件中同时也配置了itemRender，但自定义的breadcrumb并未引起itemRender的执行。

最终渲染结果：
![image](https://user-images.githubusercontent.com/10607656/62223771-15245d00-b3e8-11e9-89fb-48dfa015f5fe.png)

路由页面中配置：
![image](https://user-images.githubusercontent.com/10607656/62223060-e48ff380-b3e6-11e9-88b9-82ad2653793d.png)

BasicLayout文件配置,
![image](https://user-images.githubusercontent.com/10607656/62223261-38024180-b3e7-11e9-9351-a0f1a2abd6a6.png)

**Comment by Jiangyidan** [comment]
请问解决了吗
