### ISSUE TITLE
官方预览页面各种404，没有人维护吗？

### ISSUE THREAD

**Issue by lidianhao123** [ant-design/ant-design-pro-layout#79]
访问页面 [DashBoard 分析页](https://preview.pro.ant.design/dashboard/analysis) 跳转至404页面

![image](https://user-images.githubusercontent.com/7970645/62528969-4da4ba80-b870-11e9-9a3a-3492c1157536.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/issues/4705
