### ISSUE TITLE
pro-layout中onCollapse 与collapsed属性warning一直弹

### ISSUE THREAD

**Issue by Orchild** [ant-design/ant-design-pro-layout#83]
https://github.com/ant-design/ant-design-pro-layout/blob/b94ad63530f572080f7caceb6bd19ca02e45219e/src/BasicLayout.tsx#L147

更新至ant-pro-v4后就不停地刷这个warning

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro-layout/pull/81
