### ISSUE TITLE
怎么可以让sidebar放在header下方？

### ISSUE THREAD

**Issue by BurnhamZhang** [ant-design/ant-design-pro-layout#86]
文档里貌似没看到有这样的配置
如果自己重新实现一套 basiclayout 感觉有点麻烦
如果用css改的话   sidebar是 header 的 父级兄弟元素，总感觉怪怪的
如果用两个layout嵌套，感觉又有点傻

**Comment by chenshuai2144** [comment]
现在不支持这个特性的

**Comment by hhking** [comment]
我也没找到这个配置，自己完全实现一套感觉挺麻烦的，所以我自己 fork 修改了一份
[header-sider-layout](https://github.com/hhking/header-sider-layout)

**Comment by chenshuai2144** [comment]
可以通过嵌套 layout 来实现了
