### ISSUE TITLE
引入 BasicLayout 后报错：Invalid hook call.

### ISSUE THREAD

**Issue by H5futurehreohanshuo** [ant-design/ant-design-pro-layout#87]
使用 create-react-app 创建项目，react版本：16.8.6，react-dom版本：16.8.6。
```js
import React from 'react';
import { render } from 'react-dom';
import BasicLayout from '@ant-design/pro-layout';

render(<BasicLayout />, document.getElementById('root'));
```

引入后报错，报错信息如下：
![image](https://user-images.githubusercontent.com/19237129/62835803-00b94d80-bc8f-11e9-9b91-5ed7733d3dcb.png)
请教这个错误原因是什么

**Comment by afc163** [comment]
给个重现仓库。

**Comment by H5futurehreohanshuo** [comment]
请教一下，@ant-design/pro-layout可以脱离ant-design-pro，直接下载 antd 包后开始使用吗

**Comment by chenshuai2144** [comment]
可以的

**Comment by tsaiDavid** [comment]
https://codesandbox.io/embed/basiclayout-invalid-hook-krurc

**Comment by tsaiDavid** [comment]
@H5futurehreohanshuo - you may need to update `react` and `react-dom` to 16.9
See: https://codesandbox.io/s/basiclayout-invalid-hook-krurc

In CodeSandbox, when I set it to ~16.8, I run into the issue you were. Also updated `react-scripts`
