### ISSUE TITLE
Open external tab in menu

### ISSUE THREAD

**Issue by htactive-trinhtc** [ant-design/ant-design-pro-layout#90]
In my case i couldn't pass option **target**="_blank" to menuItem when the **path** value is not http url( It's just path into app route). Take a look in below code section: 
```
  if (isHttpUrl) {
      defaultItem = (
        <a href={itemPath} target={target}>
          {icon}
          <span>{name}</span>
        </a>
      );
    }```

**Comment by chenshuai2144** [comment]
可以在 config.js 中配置
