### ISSUE TITLE
想要知道侧边栏的menu名称是怎么拿到的

### ISSUE THREAD

**Issue by amelonsamy** [ant-design/ant-design-pro-layout#91]
现在准备使用ant-pro的脚手架，但是目前的布局配置不满足我们的业务需求，所以想要在这个脚手架的基础上重写，现在知道router和local文件里面的menu.js是有联系的，但是还是想问下具体是怎样联系在一起的，在组件里面是否有方法可以直接获取到menu.js.

**Comment by chenshuai2144** [comment]
可以参考里面的代码！
import getMenuData from './utils/getMenuData'; 这个方法从 prop 中获取 menu
