### ISSUE TITLE
如何在新建的项目中单独使用 ant-design-pro-layout

### ISSUE THREAD

**Issue by xluos** [ant-design/ant-design-pro-layout#93]
我是否可以在独立的项目中单独使用ant-design-pro-layout。比如我使用了create-react-app创建了一个全新的项目。写下了下面的代码
```jsx
import React from 'react';
import BasicLayout from '@ant-design/pro-layout';
const route = {
  routes: [
    { path: '/', name: 'welcome', icon: 'smile' },
    { path: '/home', name: '主页', icon: 'home' },
  ],
};
function App() {
  return (
    <BasicLayout title="Ant Design Pro" route={route}/>
  );
}

export default App;
```

但是页面并没有正常展示，如果想要在独立的项目中使用我需要怎么做，有相关的例子吗？

![image](https://user-images.githubusercontent.com/23625189/63828143-22594b00-c998-11e9-82d8-140dee177627.png)

**Comment by afc163** [comment]
@chenshuai2144 我们文档里遗漏了 css 的引入。

**Comment by xluos** [comment]
> @chenshuai2144 我们文档里遗漏了 css 的引入。

有时间在文档上添加一下吗？

**Comment by gankbat** [comment]
css样式在哪啊 要如何引入啊  能解答下嘛？ @chenshuai2144

**Comment by forvenus** [comment]
> css样式在哪啊 要如何引入啊 能解答下嘛？ @chenshuai2144

同问，谢

**Comment by windgaucho** [comment]
Any updates on this problem? I can not figure out how to use this layout on a project

**Comment by wangjianio** [comment]
`pro-layout` 是直接引用的 less，和 `antd` 不一样，所以目前可以在 `webpack` 中配置 `less-loader`。

Not the same as `antd`, `pro-layout` imports `less` directly. Now we can configure `less-loader` in `webpack`. 

> 不用额外引入样式。
> No need to import styles additional.

```shell
npm install --save-dev less less-loader css-loader style-loader
```

```js
// webpack.config.js
module.exports = {
  module: {
    rules: [
      {
        test: /\.less$/,
        use: [
          { loader: 'style-loader' },
          { loader: 'css-loader' },
          {
            loader: 'less-loader',
            options: { javascriptEnabled: true },
          },
        ],
      }
    ]
  }
}
```

```jsx
// App.jsx
import React from 'react';
import BasicLayout from '@ant-design/pro-layout';

function App() {
  return (
    <BasicLayout title="demo" />
  );
}
```

**Comment by hanqizheng** [comment]
你好，按照antd官网的指示引入样式文件
```js
import 'antd/dist/antd.css'; // or 'antd/dist/antd.less'
```

但是依然没有正确显示
![image](https://user-images.githubusercontent.com/19874042/72029489-0b6d2280-32c1-11ea-9e0c-5b9c258a02cd.png)

应该怎么正确的引入样式呢？谢谢。

**Comment by Sean-Snow** [comment]
请教下 MenuDataItem 中的 authority 是如何使用的呢

**Comment by chenshuai2144** [comment]
已经支持了

**Comment by netcore-jroger** [comment]
什么时候提供一下 create-react-app 的示例呀？
