### ISSUE TITLE
导航栏菜单selectedKeys 失效

### ISSUE THREAD

**Issue by changero** [ant-design/ant-design-pro-layout#95]
version: "@ant-design/pro-layout": "^4.5.14",
![TIM图片20190830153755](https://user-images.githubusercontent.com/17746517/64002277-4190dd80-cb3c-11e9-8dab-ac49383cb5ed.png)
menuData添加key字段作为Menu.Item的key，导致获取的selectedKeys与设置到Menu.Item中的key不一致。使得菜单不显示选中效果

**Comment by itgjz** [comment]
我也遇到同样的问题，请问怎么解决的

**Comment by changero** [comment]
@itgjz 保证path唯一，删除key字段
