### ISSUE TITLE
ssr support for ProLayout 

### ISSUE THREAD

**Issue by Enalmada** [ant-design/ant-design-pro-layout#96]
I am trying to use Ant Design Pro 4.5.14 ProLayout in Next.js which is server side rendered and getting this error:
```
ReferenceError: window is not defined
...\node_modules\react-media-hook2\lib\index.js:17:46)
```
Could you allow the passing of something like `defaultMatches` down from `<ProLayout />` so that if window object doesn't exist, ssr rendering can pass in a value from something generated out of user agent.  Something like this:
https://github.com/ReactTraining/react-media#server-side-rendering-ssr

That would allow everyone doing ssr to benefit from this awesome project!

**Comment by nightwind2020** [comment]
@chenshuai2144 你好，这个bug又回来了。

https://github.com/chenshuai2144/useMediaQuery/blob/master/src/index.ts#L48

![image](https://user-images.githubusercontent.com/44315206/76523057-b1483380-64a2-11ea-8cd8-65584d328434.png)

**Comment by GonzaloRecioG** [comment]
Can confirm as @nightwind2020 says that this issue is happening again. We tried both 4.11.3 and 5.0.6

**Comment by NachoJusticia** [comment]
Same problem with Next v7 and ant-design-pro-layout v5.0.6

**Comment by afc163** [comment]
@chenshuai2144 We need ci for ssr.

**Comment by akshatmittal** [comment]
Importing `BasicLayout` with Next.js Dynamic Imports disabling SSR works fine at the expense of adding ~30KB to first load js.

```jsx
import dynamic from 'next/dynamic';
const BasicLayout = dynamic(() => import('@ant-design/pro-layout'), { ssr: false });
```

Once the PR in `use-media-antd-query` is merged, SSR can be enabled and breakpoints will trigger browser side as well.
